/**
 * Copyright (c) 2024 Alti.Code.Studio
 * 
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */


import { logger } from '../../../shared/logger.js';
import { GeminiAiService } from '../gemini/gemini.service.js';
import { auditService } from '../audit/audit.service.js'; // Assuming we can access logs or will mock
import fs from 'fs/promises';
import path from 'path';

class ReportService {
    constructor() {
        this.reportsDir = path.join(process.cwd(), 'reports');
    }

    /**
     * Generate a transparency report for a given time range
     * @param {string} range 'daily' | 'weekly'
     */
    async generateTransparencyReport(range = 'weekly') {
        try {
            logger.info(`📊 Generating ${range} AI Transparency Report...`);

            // 1. Fetch Audit Logs (Mocking the fetch from AuditService/DB for now)
            const logs = await this.fetchRecentLogs(range);

            if (logs.length === 0) {
                logger.info('No AI activity to report.');
                return { filePath: null, content: 'No activity.' };
            }

            // 2. Summarize with AI
            const summary = await this.summarizeLogs(logs);

            // 3. Generate Markdown
            const reportContent = this.formatReport(summary, logs.length);

            // 4. Save to Disk
            await fs.mkdir(this.reportsDir, { recursive: true });
            const filename = `transparency_report_${new Date().toISOString().split('T')[0]}.md`;
            const filePath = path.join(this.reportsDir, filename);
            await fs.writeFile(filePath, reportContent);

            logger.info(`✅ Report saved to ${filePath}`);
            return { filePath, content: reportContent };

        } catch (error) {
            logger.error(`❌ Failed to generate report: ${error.message}`);
            throw error;
        }
    }

    async fetchRecentLogs(range) {
        // Mock data representing what AuditService would return
        return [
            { timestamp: new Date().toISOString(), actor: 'OrchestratorAgent', action: 'Create File', resource: 'src/app/modules/new.service.js', outcome: 'Success' },
            { timestamp: new Date().toISOString(), actor: 'Surgeon', action: 'Fix Bug', resource: 'src/utils/helper.js', outcome: 'Success' },
            { timestamp: new Date().toISOString(), actor: 'VertexService', action: 'Generate Code', resource: 'Token Usage: 1540', outcome: 'Success' },
            { timestamp: new Date().toISOString(), actor: 'Developer', action: 'Manual Override', resource: 'config/index.js', outcome: 'Success' }
        ];
    }

    async summarizeLogs(logs) {
        const prompt = `
            You are a Compliance Officer. Summarize the following AI Audit Logs into a high-level executive summary.
            Focus on what was created, modified, or fixed.
            
            Logs:
            ${JSON.stringify(logs)}
        `;

        try {
            return await GeminiAiService.generateContent(prompt);
        } catch (e) {
            logger.warn('AI Summary failed, using raw logs count.');
            return `AI processed ${logs.length} actions. Detailed summary unavailable due to AI service interruption.`;
        }
    }

    formatReport(summary, count) {
        return `
# 🤖 AI Transparency Report
**Date**: ${new Date().toLocaleDateString()}
**Total Actions**: ${count}

## Executive Summary
${summary}

## Compliance Footer
Generated by Alti.Code.Studio Governor Module.
        `;
    }
}

export const reportService = new ReportService();
