kind: pipeline
name: default

steps:
- name: backend-test
  image: node:20
  commands:
  - cd Inso.Code.Backend
  - git submodule update --init --recursive
  - npm ci
  - npm test

- name: frontend-build
  image: node:20
  commands:
  - cd Inso.Code.Frontend
  - git submodule update --init --recursive
  - npm ci
  - npm run build

- name: build-backend-image
  image: plugins/docker
  settings:
    dry_run: true
    repo: inso-backend
    dockerfile: Inso.Code.Backend/Dockerfile
    context: Inso.Code.Backend
    tags: latest

- name: build-frontend-image
  image: plugins/docker
  settings:
    dry_run: true
    repo: inso-frontend
    dockerfile: Inso.Code.Frontend/Dockerfile
    context: Inso.Code.Frontend
    tags: latest
