import express from 'express';
import pptxgen from 'pptxgenjs/dist/pptxgen.cjs.js';

const router = express.Router();

// Generate Slide Deck and return pptx as a downloadable binary file
router.post('/generate', async (req, res) => {
  try {
    const {
      title = 'Untitled Presentation',
      subtitle = 'Alti Code Studio Deck',
      prompt = '',
      strategistMode = 'Technical Deep Dive',
      visualStyle = 'Sleek Dark Mode',
      selectedContext = [],
    } = req.body;

    const pptx = new pptxgen();
    pptx.title = title;

    // Define colors based on the visual style
    const isDark = visualStyle === 'Sleek Dark Mode';
    
    // Background and Accent Colors
    const bgHex = isDark ? '0A0A0B' : 'F8FAFC';
    const cardBgHex = isDark ? '121218' : 'FFFFFF';
    const textHex = isDark ? 'FFFFFF' : '0F172A';
    const mutedTextHex = isDark ? '94A3B8' : '64748B';
    
    let accentHex = '8B5CF6'; // Default Purple
    if (visualStyle === 'Corporate Grid') accentHex = '2563EB'; // Corporate Blue
    if (visualStyle === 'Sovereign Minimalist') accentHex = '111827'; // Midnight Black

    // ──────────────── SLIDE 1: TITLE SLIDE ────────────────
    const slide1 = pptx.addSlide();
    slide1.background = { fill: bgHex };

    // Accent line/shape on the left
    slide1.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 0.4,
      h: 5.625, // standard 16:9 height
      fill: { color: accentHex },
    });

    // Subtitle top-label
    slide1.addText(strategistMode.toUpperCase(), {
      x: 1.0,
      y: 1.5,
      w: 8.0,
      h: 0.4,
      fontSize: 11,
      bold: true,
      color: accentHex,
      fontFace: 'Helvetica Neue',
    });

    // Main Title
    slide1.addText(title, {
      x: 1.0,
      y: 2.0,
      w: 8.0,
      h: 1.2,
      fontSize: 36,
      bold: true,
      color: textHex,
      fontFace: 'Helvetica Neue',
    });

    // Subtitle
    slide1.addText(subtitle, {
      x: 1.0,
      y: 3.3,
      w: 8.0,
      h: 0.6,
      fontSize: 16,
      color: mutedTextHex,
      fontFace: 'Helvetica Neue',
    });

    // Brand Label
    slide1.addText('Generated by Alti Code Studio', {
      x: 1.0,
      y: 4.8,
      w: 5.0,
      h: 0.4,
      fontSize: 10,
      color: mutedTextHex,
      fontFace: 'Helvetica Neue',
      italic: true,
    });

    // ──────────────── SLIDE 2: EXECUTIVE SUMMARY ────────────────
    const slide2 = pptx.addSlide();
    slide2.background = { fill: bgHex };

    // Slide Header
    slide2.addText('Executive Overview', {
      x: 0.8,
      y: 0.6,
      w: 8.0,
      h: 0.6,
      fontSize: 24,
      bold: true,
      color: textHex,
      fontFace: 'Helvetica Neue',
    });

    // Summary Card 1 (Objectives)
    slide2.addShape(pptx.ShapeType.rect, {
      x: 0.8,
      y: 1.5,
      w: 4.0,
      h: 3.2,
      fill: { color: cardBgHex },
      line: { color: isDark ? '2A2A35' : 'E2E8F0', width: 1 },
    });
    slide2.addText('Core Objectives', {
      x: 1.1,
      y: 1.8,
      w: 3.4,
      h: 0.4,
      fontSize: 16,
      bold: true,
      color: accentHex,
    });
    slide2.addText(prompt || 'Synthesize technical project specs and compile actionable targets.', {
      x: 1.1,
      y: 2.3,
      w: 3.4,
      h: 2.0,
      fontSize: 12,
      color: textHex,
      bullet: false,
    });

    // Summary Card 2 (Targets)
    slide2.addShape(pptx.ShapeType.rect, {
      x: 5.2,
      y: 1.5,
      w: 4.0,
      h: 3.2,
      fill: { color: cardBgHex },
      line: { color: isDark ? '2A2A35' : 'E2E8F0', width: 1 },
    });
    slide2.addText('Key Targets', {
      x: 5.5,
      y: 1.8,
      w: 3.4,
      h: 0.4,
      fontSize: 16,
      bold: true,
      color: accentHex,
    });
    
    const targets = [
      { text: 'Deploy scalable infrastructure layers' },
      { text: 'Enforce enterprise security guardrails' },
      { text: 'Automate testing & release integrations' }
    ];
    slide2.addText(targets, {
      x: 5.5,
      y: 2.3,
      w: 3.4,
      h: 2.0,
      fontSize: 12,
      color: textHex,
      bullet: true,
      lineSpacing: 28,
    });

    // ──────────────── SLIDE 3: SYSTEM CONTEXT ────────────────
    const slide3 = pptx.addSlide();
    slide3.background = { fill: bgHex };

    slide3.addText('Architecture & Connected Context', {
      x: 0.8,
      y: 0.6,
      w: 8.0,
      h: 0.6,
      fontSize: 24,
      bold: true,
      color: textHex,
      fontFace: 'Helvetica Neue',
    });

    // Render list of attached items
    const contextItems = selectedContext.length > 0 ? selectedContext : ['Default Workspace Project', 'Active Database Layer', 'Secure Sandbox API'];
    
    contextItems.forEach((item, index) => {
      const yOffset = 1.5 + (index * 1.0);
      if (index < 3) { // limit to 3 items
        slide3.addShape(pptx.ShapeType.rect, {
          x: 0.8,
          y: yOffset,
          w: 8.4,
          h: 0.8,
          fill: { color: cardBgHex },
          line: { color: isDark ? '2A2A35' : 'E2E8F0', width: 1 },
        });

        // Accent check
        slide3.addShape(pptx.ShapeType.rect, {
          x: 0.8,
          y: yOffset,
          w: 0.15,
          h: 0.8,
          fill: { color: accentHex },
        });

        // Item text
        slide3.addText(item, {
          x: 1.2,
          y: yOffset + 0.15,
          w: 4.5,
          h: 0.5,
          fontSize: 14,
          bold: true,
          color: textHex,
        });

        slide3.addText('Active Configuration Layer', {
          x: 5.8,
          y: yOffset + 0.15,
          w: 3.0,
          h: 0.5,
          fontSize: 12,
          color: mutedTextHex,
          align: 'right',
        });
      }
    });

    // ──────────────── SLIDE 4: OPERATIONS & GUARDRAILS ────────────────
    const slide4 = pptx.addSlide();
    slide4.background = { fill: bgHex };

    slide4.addText('Operational Safety & Guardrails', {
      x: 0.8,
      y: 0.6,
      w: 8.0,
      h: 0.6,
      fontSize: 24,
      bold: true,
      color: textHex,
      fontFace: 'Helvetica Neue',
    });

    // Large card
    slide4.addShape(pptx.ShapeType.rect, {
      x: 0.8,
      y: 1.5,
      w: 8.4,
      h: 3.2,
      fill: { color: cardBgHex },
      line: { color: isDark ? '2A2A35' : 'E2E8F0', width: 1 },
    });

    const guardrailRules = [
      { text: 'Programmatic input validation scrubs query scripts before compiler executions.' },
      { text: 'Strict sovereign boundary routes block foundational cloud data leaks.' },
      { text: 'Automated policy evaluations trigger container rolling updates on failure.' }
    ];

    slide4.addText(guardrailRules, {
      x: 1.2,
      y: 1.8,
      w: 7.6,
      h: 2.6,
      fontSize: 13,
      color: textHex,
      bullet: true,
      lineSpacing: 36,
    });

    // ──────────────── SLIDE 5: ROADMAP ────────────────
    const slide5 = pptx.addSlide();
    slide5.background = { fill: bgHex };

    slide5.addText('Implementation Roadmap', {
      x: 0.8,
      y: 0.6,
      w: 8.0,
      h: 0.6,
      fontSize: 24,
      bold: true,
      color: textHex,
      fontFace: 'Helvetica Neue',
    });

    // Draw 3 horizontal steps
    const steps = [
      { num: '01', title: 'Compile & Test', desc: 'Verify schemas and build mocks.' },
      { num: '02', title: 'Stitch Token Contracts', desc: 'Deploy visual constraints.' },
      { num: '03', title: 'Swarm Provisioning', desc: 'Configure cloud workloads.' }
    ];

    steps.forEach((step, index) => {
      const xOffset = 0.8 + (index * 2.9);
      
      // Step Card
      slide5.addShape(pptx.ShapeType.rect, {
        x: xOffset,
        y: 1.6,
        w: 2.6,
        h: 3.0,
        fill: { color: cardBgHex },
        line: { color: isDark ? '2A2A35' : 'E2E8F0', width: 1 },
      });

      // Step Number
      slide5.addText(step.num, {
        x: xOffset + 0.2,
        y: 1.8,
        w: 1.5,
        h: 0.5,
        fontSize: 28,
        bold: true,
        color: accentHex,
      });

      // Step Title
      slide5.addText(step.title, {
        x: xOffset + 0.2,
        y: 2.4,
        w: 2.2,
        h: 0.4,
        fontSize: 14,
        bold: true,
        color: textHex,
      });

      // Step Desc
      slide5.addText(step.desc, {
        x: xOffset + 0.2,
        y: 2.9,
        w: 2.2,
        h: 1.4,
        fontSize: 11,
        color: mutedTextHex,
      });
    });

    // Write Presentation file buffer
    const buffer = await pptx.write('nodebuffer');

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.presentationml.presentation');
    res.setHeader('Content-Disposition', `attachment; filename="${encodeURIComponent(title.replace(/\s+/g, '_'))}.pptx"`);
    res.send(buffer);

  } catch (error) {
    console.error('[PresentationRoutes] PPTX generation error:', error);
    res.status(500).json({ error: 'Failed to compile PowerPoint presentation.' });
  }
});

export const presentationRoutes = router;
