export interface TeamMember {
  id: string;
  name: string;
  role: string;
  type: "language" | "functional";
  category: string;
  specialties: string[];
  bio: string;
  status: "idle" | "active" | "testing" | "compiling";
  statusText: string;
  accentColor: string;
}

export const teamMembers: TeamMember[] = [
  // ==================== LANGUAGES ====================
  // Systems & Native
  {
    id: "c-expert",
    name: "Ken Thompson AI",
    role: "C Systems Specialist",
    type: "language",
    category: "Systems",
    specialties: ["POSIX API", "Memory Tuning", "Linux Daemons"],
    bio: "Optimizes OS-level daemons, kernel extensions, and microsecond-level raw memory management operations.",
    status: "idle",
    statusText: "Idle - Ready to compile",
    accentColor: "#F34F29",
  },
  {
    id: "cpp-expert",
    name: "Bjarne Stroustrup AI",
    role: "C++ Optimization Veteran",
    type: "language",
    category: "Systems",
    specialties: ["Modern C++20", "Template Metaprogramming", "Low-Latency"],
    bio: "Drafts high-frequency trading engines, graphics pipelines, and zero-overhead abstractions.",
    status: "active",
    statusText: "Analyzing pointers...",
    accentColor: "#00599C",
  },
  {
    id: "rust-expert",
    name: "Graydon Hoare AI",
    role: "Rust Systems Architect",
    type: "language",
    category: "Systems",
    specialties: ["Lifetimes & Borrowing", "Cargo ecosystems", "WASM targets"],
    bio: "Enforces absolute memory safety and concurrent performance without a garbage collector.",
    status: "compiling",
    statusText: "Compiling cargo build --release...",
    accentColor: "#DEA584",
  },
  {
    id: "zig-expert",
    name: "Andrew Kelley AI",
    role: "Zig Systems Engineer",
    type: "language",
    category: "Systems",
    specialties: ["Comptime", "Manual Memory Allocation", "C Interop"],
    bio: "Creates lean binaries with zero hidden control flow and seamless C ABI integration.",
    status: "idle",
    statusText: "Idle - Ready",
    accentColor: "#F7A41D",
  },
  {
    id: "go-expert",
    name: "Rob Pike AI",
    role: "Go Microservices Developer",
    type: "language",
    category: "Systems",
    specialties: ["Goroutines", "Channels", "Standard Library APIs"],
    bio: "Spawns highly concurrent APIs and network services using idiomatic channels and simple syntax.",
    status: "active",
    statusText: "Running go run main.go...",
    accentColor: "#00ADD8",
  },
  {
    id: "assembly-x86-expert",
    name: "Mel AI",
    role: "Assembly x86 Optimizer",
    type: "language",
    category: "Systems",
    specialties: [
      "SIMD Instructions",
      "Inline Assembly",
      "Binary Reverse-Engineering",
    ],
    bio: "Fine-tunes hot loops at the instruction level, directly managing CPU registers and cache alignment.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#6E4C13",
  },
  {
    id: "assembly-arm-expert",
    name: "Steve AI",
    role: "Assembly ARM Specialist",
    type: "language",
    category: "Systems",
    specialties: ["NEON Intrinsics", "Apple Silicon", "Embedded Runtimes"],
    bio: "Writes performance-critical ARM64 assembly optimized for mobile SOCs and battery efficiency.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#8E5C13",
  },
  {
    id: "d-expert",
    name: "Walter Bright AI",
    role: "D Language Developer",
    type: "language",
    category: "Systems",
    specialties: ["BetterC", "GC-free programming", "Metaprogramming"],
    bio: "Bridging the gap between scripting convenience and high-performance native compilation.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#BA595E",
  },
  {
    id: "nim-expert",
    name: "Andreas Rumpf AI",
    role: "Nim Systems Developer",
    type: "language",
    category: "Systems",
    specialties: [
      "AST Macros",
      "C/C++ Backend compilation",
      "Memory management",
    ],
    bio: "Writes pythonic looking code that compiles into raw, dependency-free C binaries.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#37775B",
  },
  {
    id: "carbon-expert",
    name: "Carbon Innovator AI",
    role: "Carbon Migration Specialist",
    type: "language",
    category: "Systems",
    specialties: ["C++ Interop", "Modernized Syntax", "Generics"],
    bio: "Assists legacy teams in converting massive C++ structures into modern Carbon codebases.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#007ACC",
  },
  {
    id: "mojo-expert",
    name: "Chris Lattner AI (Mojo)",
    role: "Mojo AI Systems Developer",
    type: "language",
    category: "Systems",
    specialties: [
      "MLIR Integration",
      "Hardware Acceleration",
      "Python-plus Syntax",
    ],
    bio: "Accelerates AI models by compiling Python-like code directly to heterogeneous hardware architectures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF5A09",
  },

  // Web & Scripting
  {
    id: "ts-expert",
    name: "Anders Hejlsberg AI",
    role: "TypeScript Architect",
    type: "language",
    category: "Web",
    specialties: ["Strict Typings", "Generic Mapping", "TSConfig Tuning"],
    bio: "Refactors loose Javascript into production-grade, self-documenting TypeScript structures.",
    status: "active",
    statusText: "Resolving type imports...",
    accentColor: "#3178C6",
  },
  {
    id: "js-expert",
    name: "Brendan Eich AI",
    role: "JavaScript Core Specialist",
    type: "language",
    category: "Web",
    specialties: ["Event Loop", "V8 Engine", "Prototype Runtimes"],
    bio: "Debugs memory leaks in asynchronous loops and handles complex DOM event bubbling scenarios.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F7DF1E",
  },
  {
    id: "python-expert",
    name: "Guido van Rossum AI",
    role: "Python Core Developer",
    type: "language",
    category: "Web",
    specialties: ["Asyncio", "PEP 8 Standard", "Package Management"],
    bio: "Structures pythonic backend systems, scientific scripts, and CLI utilities with clean code.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#3776AB",
  },
  {
    id: "php-expert",
    name: "Rasmus Lerdorf AI",
    role: "PHP Core Developer",
    type: "language",
    category: "Web",
    specialties: ["PHP 8.x Attributes", "Composer", "OPcache Tuning"],
    bio: "Maintains legacy systems and structures modern PHP backends using strict typing and PSR standards.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#777BB4",
  },
  {
    id: "ruby-expert",
    name: "Yukihiro Matsumoto AI",
    role: "Ruby Core Developer",
    type: "language",
    category: "Web",
    specialties: ["Metaprogramming", "Blocks/Procs/Lambdas", "Bundler Configs"],
    bio: "Emphasizes developer happiness with elegant ruby DSLs and bulletproof deployment pipelines.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#CC342D",
  },
  {
    id: "perl-expert",
    name: "Larry Wall AI",
    role: "Perl Utilities Expert",
    type: "language",
    category: "Web",
    specialties: ["Regex processing", "Perl 5.36+", "Taint Mode Safety"],
    bio: "Deciphers and optimizes legacy Perl scripts for report generation and text-parsing pipelines.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#39457E",
  },
  {
    id: "lua-expert",
    name: "Roberto Ierusalimschy AI",
    role: "Lua Embedding Specialist",
    type: "language",
    category: "Web",
    specialties: ["Luajit", "C API integration", "Game scripting"],
    bio: "Embeds lightweight scripting runtimes inside game engines and custom web proxies (Nginx/Envoy).",
    status: "idle",
    statusText: "Idle",
    accentColor: "#000080",
  },
  {
    id: "tcl-expert",
    name: "John Ousterhout AI (Tcl)",
    role: "Tcl/Tk Scripting Expert",
    type: "language",
    category: "Web",
    specialties: [
      "Event-driven scripting",
      "GUI toolkits",
      "Hardware CAD flow",
    ],
    bio: "Handles automated hardware simulation scripts and legacy graphical network consoles.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#2F5F8F",
  },
  {
    id: "bash-expert",
    name: "Brian Fox AI",
    role: "Bash/Shell Automation Specialist",
    type: "language",
    category: "Web",
    specialties: ["Unix Pipelines", "POSIX compliance", "Local Daemons"],
    bio: "Writes bulletproof deployment and migration shell scripts with correct error exit trapping.",
    status: "active",
    statusText: "Running deployment shell...",
    accentColor: "#4EAA25",
  },
  {
    id: "powershell-expert",
    name: "Jeffrey Snover AI",
    role: "PowerShell Systems Developer",
    type: "language",
    category: "Web",
    specialties: ["Cmdlet design", ".NET Object Pipelines", "AD Automation"],
    bio: "Orchestrates Windows domain infrastructure and cloud script pipelines.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#53C1DE",
  },

  // Enterprise & JVM/CLR
  {
    id: "java-expert",
    name: "James Gosling AI",
    role: "Java Enterprise Architect",
    type: "language",
    category: "Enterprise",
    specialties: ["JVM Tuning", "Maven/Gradle builds", "Garbage Collectors"],
    bio: "Architects enterprise Java systems, tuning GC profiles and optimizing Spring Boot threads.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#007396",
  },
  {
    id: "csharp-expert",
    name: "Anders Hejlsberg CLR AI",
    role: "C# Core Specialist",
    type: "language",
    category: "Enterprise",
    specialties: [".NET Core", "LINQ Optimization", "NuGet ecosystems"],
    bio: "Develops cross-platform corporate APIs and desktop platforms using highly optimized LINQ queries.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#239120",
  },
  {
    id: "kotlin-lang-expert",
    name: "Dmitry Jemerov AI",
    role: "Kotlin Backend Developer",
    type: "language",
    category: "Enterprise",
    specialties: ["Coroutines", "Exposed ORM", "Ktor Services"],
    bio: "Enforces null-safety and asynchronous programming utilizing Kotlin's native flows.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#7F52FF",
  },
  {
    id: "swift-lang-expert",
    name: "Chris Lattner Swift AI",
    role: "Swift Systems Specialist",
    type: "language",
    category: "Enterprise",
    specialties: ["Structured Concurrency", "Swift 6", "Actors"],
    bio: "Enforces thread-safe systems using native Swift compile-time actor isolations.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F05138",
  },
  {
    id: "objc-expert",
    name: "Brad Cox AI",
    role: "Objective-C Legacy Architect",
    type: "language",
    category: "Enterprise",
    specialties: ["Runtime Bridging", "Manual Retain Release", "C/ObjC mix"],
    bio: "Refactors historic iOS/macOS frameworks and acts as a bridge to swift interfaces.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#438EFF",
  },
  {
    id: "scala-expert",
    name: "Martin Odersky AI",
    role: "Scala Platform Architect",
    type: "language",
    category: "Enterprise",
    specialties: ["Functional OOP", "Akka Swarms", "Spark Core"],
    bio: "Builds massive distributed microservices combining strong typing and immutable designs.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#DC322F",
  },
  {
    id: "groovy-expert",
    name: "Guillaume Laforge AI",
    role: "Groovy Integration Developer",
    type: "language",
    category: "Enterprise",
    specialties: ["Gradle configs", "Spock Testing", "Dynamic scripting"],
    bio: "Automates enterprise builds and testing scripts targeting JVM frameworks.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4298B8",
  },

  // Functional & Logic
  {
    id: "haskell-expert",
    name: "Philip Wadler AI",
    role: "Haskell Theory Specialist",
    type: "language",
    category: "Functional",
    specialties: ["Monads", "Typeclasses", "Lazy Evaluation"],
    bio: "Proves algorithms correct at the compile phase using pure, mathematically sound functional models.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#5E5086",
  },
  {
    id: "elixir-lang-expert",
    name: "José Valim AI",
    role: "Elixir OTP Specialist",
    type: "language",
    category: "Functional",
    specialties: ["OTP Actor Model", "Phoenix LiveView", "BEAM scaling"],
    bio: "Develops fault-tolerant, highly concurrent messaging hubs scaling to millions of live sockets.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4E275C",
  },
  {
    id: "erlang-expert",
    name: "Joe Armstrong AI",
    role: "Erlang Systems Architect",
    type: "language",
    category: "Functional",
    specialties: ["Supervisor Trees", "Distributed Nodes", "Hot Upgrades"],
    bio: "Pioneers telecommunication-grade reliability systems that never shut down during upgrades.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#A90533",
  },
  {
    id: "fsharp-lang-expert",
    name: "Don Syme AI",
    role: "F# Functional Architect",
    type: "language",
    category: "Functional",
    specialties: ["Type Providers", "Domain Modeling", "Pattern Matching"],
    bio: "Implements clean, mathematical models integrated with the Microsoft .NET runtime.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#378BBA",
  },
  {
    id: "clojure-expert",
    name: "Rich Hickey AI",
    role: "Clojure Lisp Specialist",
    type: "language",
    category: "Functional",
    specialties: ["Immutable Data structures", "Transducers", "JVM Interop"],
    bio: "Pioneers simplicity in development through interactive REPLs and dynamic data abstractions.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#58B12F",
  },
  {
    id: "ocaml-expert",
    name: "Xavier Leroy AI",
    role: "OCaml Compiler Developer",
    type: "language",
    category: "Functional",
    specialties: ["Type Inference", "Coq Verification", "Opam builds"],
    bio: "Works on program verification, compilers, and safety-critical execution kernels.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#EE6A1A",
  },
  {
    id: "lisp-expert",
    name: "John McCarthy AI",
    role: "Common Lisp Architect",
    type: "language",
    category: "Functional",
    specialties: ["Macro Expansion", "Dynamic Runtimes", "ASDF builds"],
    bio: "Crafts meta-programming layers where code is treated as plain, morphable list structures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#3F80A0",
  },
  {
    id: "prolog-expert",
    name: "Alain Colmerauer AI",
    role: "Prolog Logic Programmer",
    type: "language",
    category: "Functional",
    specialties: ["Unification", "Constraint Solving", "Grammar Rules"],
    bio: "Solves combinatorial planning, parsing, and semantic reasoning challenges using logical predicates.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#74283C",
  },

  // Data & Math
  {
    id: "sql-expert",
    name: "Donald Chamberlin AI",
    role: "SQL Query Architect",
    type: "language",
    category: "Data",
    specialties: ["Query Optimization", "Window Functions", "Index Strategies"],
    bio: "Refactors complex nested joins and builds materialized views for millisecond retrieval.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E38B29",
  },
  {
    id: "r-expert",
    name: "Ross Ihaka AI",
    role: "R Statistical Programmer",
    type: "language",
    category: "Data",
    specialties: ["GGPlot2", "Data Frames", "Tidyverse"],
    bio: "Performs mathematical analysis, hypothesis testing, and builds analytics visuals.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#198CE7",
  },
  {
    id: "julia-expert",
    name: "Viral Shah AI",
    role: "Julia Scientific Developer",
    type: "language",
    category: "Data",
    specialties: [
      "Multiple Dispatch",
      "Parallel Processing",
      "Differential Equations",
    ],
    bio: "Solves high-speed numerical tasks, matching C speed with high-level Pythonic syntax.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#9558B2",
  },
  {
    id: "matlab-expert",
    name: "Cleve Moler AI",
    role: "MATLAB Simulation Dev",
    type: "language",
    category: "Data",
    specialties: ["Matrix Math", "Simulink", "Signal Processing"],
    bio: "Runs control system simulations, DSP scripts, and linear algebra pipelines.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E1662A",
  },
  {
    id: "fortran-expert",
    name: "John Backus AI",
    role: "Fortran Physics Programmer",
    type: "language",
    category: "Data",
    specialties: [
      "Array Slicing",
      "High-Performance Computing",
      "Legacy Math Libraries",
    ],
    bio: "Maintains numeric simulation codes, weather prediction grids, and legacy vector structures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4D6B82",
  },
  {
    id: "sas-expert",
    name: "Anthony Barr AI",
    role: "SAS Data Processor",
    type: "language",
    category: "Data",
    specialties: ["Macro Processing", "Clinical Data", "Proc SQL"],
    bio: "Parses large clinical records and financial data grids for compliance testing.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#005596",
  },
  {
    id: "cobol-expert",
    name: "Grace Hopper AI",
    role: "COBOL Mainframe Guardian",
    type: "language",
    category: "Data",
    specialties: ["EBCDIC formats", "JCL scripts", "Mainframe migrations"],
    bio: "Deals with critical legacy bank structures, parsing transactional ledgers with exact fixed decimals.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#1B3B6F",
  },

  // Web3 & Config
  {
    id: "solidity-expert",
    name: "Gavin Wood AI",
    role: "Solidity Blockchain Architect",
    type: "language",
    category: "Web3",
    specialties: ["Smart Contracts", "Gas Optimization", "EVM Forensics"],
    bio: "Writes secure smart contracts, avoiding reentrancy vectors and optimizing EVM gas usage.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#AA82E6",
  },
  {
    id: "vyper-expert",
    name: "Vitalik Buterin AI",
    role: "Vyper Security Engineer",
    type: "language",
    category: "Web3",
    specialties: ["Decimals safety", "Auditable AST", "Overflow protection"],
    bio: "Drafts highly readable Pythonic contracts with compiler-enforced overflow parameters.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#5B75A6",
  },
  {
    id: "html-expert",
    name: "Tim Berners-Lee AI",
    role: "Semantic Web Developer",
    type: "language",
    category: "Web3",
    specialties: ["Semantic HTML5", "ARIA attributes", "DOM Structure"],
    bio: "Builds clean page hierarchies that parse perfectly for search bots and screen readers.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E34F26",
  },
  {
    id: "css-expert",
    name: "Håkon Wium Lie AI",
    role: "CSS Motion Designer",
    type: "language",
    category: "Web3",
    specialties: [
      "Tailwind & Variables",
      "View Transitions",
      "Responsive Grid",
    ],
    bio: "Pioneers layout fluidity, responsive containers, dark/light theme tokens, and dynamic animations.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#1572B6",
  },
  {
    id: "graphql-expert",
    name: "Lee Byron AI",
    role: "GraphQL Schema Designer",
    type: "language",
    category: "Web3",
    specialties: ["Resolvers Optimization", "Codegen", "Federated Graph"],
    bio: "Consolidates multiple downstream APIs into a clean, query-efficient typed graph gate.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E10098",
  },
  {
    id: "config-expert",
    name: "Config Architect AI",
    role: "YAML/JSON Config Specialist",
    type: "language",
    category: "Web3",
    specialties: ["JSON Schema validation", "Drone YAML", "K8s ConfigMaps"],
    bio: "Enforces strict format structures for microservice descriptors and CI deployment trees.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#8BC34A",
  },
  {
    id: "latex-expert",
    name: "Leslie Lamport AI",
    role: "LaTeX Document Typographer",
    type: "language",
    category: "Web3",
    specialties: [
      "Mathematical typesetting",
      "PDF structures",
      "Bibliography styling",
    ],
    bio: "Formats scientific reports, mathematical papers, and publication-ready documentation PDFs.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#008080",
  },
  {
    id: "terraform-expert",
    name: "Mitchell AI",
    role: "Infrastructure as Code Specialist",
    type: "language",
    category: "Enterprise",
    specialties: ["HCL", "State Management", "Provider Development"],
    bio: "Provisions and scales cloud infrastructure flawlessly using declarative configurations.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#5C4EE5",
  },
  {
    id: "unity-expert",
    name: "David AI",
    role: "Unity Game Engine Developer",
    type: "functional",
    category: "Creative",
    specialties: ["C# Scripting", "3D Physics", "Shader Graph"],
    bio: "Builds immersive cross-platform interactive experiences and games.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#000000",
  },
  {
    id: "unreal-expert",
    name: "Tim AI",
    role: "Unreal Engine Developer",
    type: "functional",
    category: "Creative",
    specialties: ["Blueprints", "C++ Engine Core", "Nanite Optimization"],
    bio: "Pushes the boundaries of real-time rendering and hyper-realistic graphics.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0E1128",
  },
  {
    id: "ada-expert",
    name: "Lovelace AI",
    role: "High-Integrity Systems Engineer",
    type: "language",
    category: "Systems",
    specialties: ["Avionics", "Real-time Systems", "SPARK"],
    bio: "Develops mission-critical, high-reliability software for aerospace and defense.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#022B3A",
  },
  {
    id: "delphi-expert",
    name: "Anders AI",
    role: "Rapid Application Developer",
    type: "language",
    category: "Enterprise",
    specialties: ["VCL", "FireMonkey", "Windows Native"],
    bio: "Builds lightning-fast native desktop applications with robust UI frameworks.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#EE1F35",
  },
  {
    id: "vb-expert",
    name: "Alan AI",
    role: "Legacy Windows Developer",
    type: "language",
    category: "Enterprise",
    specialties: ["WinForms", "COM/ActiveX", "VBA Macros"],
    bio: "Maintains and revitalizes classic line-of-business Windows applications.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#185C9F",
  },
  {
    id: "plsql-expert",
    name: "Ellison AI",
    role: "Oracle Database Developer",
    type: "language",
    category: "Data",
    specialties: ["Stored Procedures", "Triggers", "Query Tuning"],
    bio: "Optimizes massive enterprise database workloads with procedural SQL extensions.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F80000",
  },
  {
    id: "abap-expert",
    name: "Hasso AI",
    role: "SAP Systems Architect",
    type: "language",
    category: "Enterprise",
    specialties: ["SAP ECC", "S/4HANA", "BAPI"],
    bio: "Engineers custom business logic and integrations for massive SAP ecosystems.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#008FD3",
  },
  {
    id: "vhdl-expert",
    name: "Conway AI",
    role: "Hardware Description Engineer",
    type: "language",
    category: "Systems",
    specialties: ["FPGAs", "ASIC Design", "Logic Synthesis"],
    bio: "Designs complex digital circuits and silicon-level hardware architectures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#1A5276",
  },
  {
    id: "plc-expert",
    name: "Morley AI",
    role: "Industrial Automation Engineer",
    type: "language",
    category: "Systems",
    specialties: ["Ladder Logic", "SCADA", "Modbus"],
    bio: "Programs robust controllers for manufacturing pipelines and physical automation.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#D35400",
  },
  {
    id: "gcode-expert",
    name: "Parsons AI",
    role: "CNC Machining Specialist",
    type: "language",
    category: "Systems",
    specialties: ["3D Printing", "Milling", "Toolpath Optimization"],
    bio: "Translates digital designs into precise physical movements for manufacturing hardware.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#27AE60",
  },
  {
    id: "labview-expert",
    name: "Kodosky AI",
    role: "Virtual Instrumentation Engineer",
    type: "language",
    category: "Data",
    specialties: ["Data Acquisition", "Signal Processing", "Automated Testing"],
    bio: "Designs visual programs for hardware testing and complex laboratory measurements.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FFD100",
  },

  // ==================== FUNCTIONAL ROLES ====================
  // Leadership & Product
  {
    id: "chief-architect",
    name: "Linus Torvalds AI",
    role: "Chief Systems Architect",
    type: "functional",
    category: "Architecture",
    specialties: [
      "Component Boundaries",
      "IPC Pipelines",
      "Modular Refactoring",
    ],
    bio: "Maintains the structural integrity of the codebase, reviewing merge paths and resolving design conflicts.",
    status: "active",
    statusText: "Reviewing code layout...",
    accentColor: "#FFC107",
  },
  {
    id: "enterprise-pm",
    name: "Sheryl AI",
    role: "Enterprise Product Manager",
    type: "functional",
    category: "Architecture",
    specialties: ["Feature Specs", "User Personas", "PRD Generation"],
    bio: "Translates high-level corporate needs into clear feature matrices and functional user stories.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#9C27B0",
  },
  {
    id: "startup-pm",
    name: "Steve AI (PM)",
    role: "Startup Product Lead",
    type: "functional",
    category: "Architecture",
    specialties: [
      "Hypothesis Development",
      "MVP Scoping",
      "Fast Feedback Loops",
    ],
    bio: "Prunes unnecessary bloat, scoping the minimal viable feature set to validate quickly.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E91E63",
  },
  {
    id: "scrum-master",
    name: "Jeff Sutherland AI",
    role: "Scrum Master Agent",
    type: "functional",
    category: "Architecture",
    specialties: ["Task Breakdown", "Priority Management", "Sprint Planning"],
    bio: "Organizes task workflows, breaks down massive prompts into actionable components, and tracks dependencies.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00BCD4",
  },
  {
    id: "release-train",
    name: "Scaled Agile AI",
    role: "Release Coordinator",
    type: "functional",
    category: "Architecture",
    specialties: ["Branch Merges", "Feature Flags", "Staging Audits"],
    bio: "Coordinates safe code merges, release cadences, and rolls out features via localized flag limits.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#3F51B5",
  },
  {
    id: "devrel",
    name: "Evangelist AI",
    role: "Developer Advocate",
    type: "functional",
    category: "Architecture",
    specialties: ["API Demos", "SDK Tutorials", "Community Feedback"],
    bio: "Ensures APIs are developer-friendly, building walkthrough resources and testing integration steps.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4CAF50",
  },
  {
    id: "tech-writer",
    name: "DocuScribe AI",
    role: "Technical Writer Specialist",
    type: "functional",
    category: "Architecture",
    specialties: ["Markdown codemaps", "Swagger specs", "Release notes"],
    bio: "Synchronizes repository markdown documentation and extracts clear descriptions from code variables.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#CDDC39",
  },
  {
    id: "business-analyst",
    name: "MetricSpec AI",
    role: "Technical Business Analyst",
    type: "functional",
    category: "Architecture",
    specialties: ["SQL Analytics", "Requirements validation", "UAT Scopes"],
    bio: "Validates technical code output against initial business criteria and maps acceptance logic.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF5722",
  },

  // Frontend & Mobile Frameworks
  {
    id: "react-lead",
    name: "Dan Abramov AI",
    role: "React/Next.js Lead Developer",
    type: "functional",
    category: "Frontend",
    specialties: [
      "React Server Components",
      "Hooks Lifecycle",
      "State hydration",
    ],
    bio: "Builds responsive Next.js apps using server layouts, suspense gates, and optimal local hook logic.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#61DAFB",
  },
  {
    id: "vue-lead",
    name: "Evan You AI",
    role: "Vue/Nuxt Architect",
    type: "functional",
    category: "Frontend",
    specialties: ["Composition API", "Vite configurations", "State management"],
    bio: "Refactors dynamic interfaces using reactive proxies and automated component autoloader plugins.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4FC08D",
  },
  {
    id: "angular-lead",
    name: "Igor Minar AI",
    role: "Angular Enterprise Architect",
    type: "functional",
    category: "Frontend",
    specialties: ["RxJS Observables", "Signals API", "Enterprise Modules"],
    bio: "Structures modular, scalable frontends utilizing declarative streams and dependency injection.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#DD0031",
  },
  {
    id: "svelte-expert",
    name: "Rich Harris AI",
    role: "SvelteKit Developer",
    type: "functional",
    category: "Frontend",
    specialties: ["Compile-time reactivity", "Stores", "Static building"],
    bio: "Builds lightweight dashboards with zero framework runtime overhead and smooth built-in transitions.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF3E00",
  },
  {
    id: "solid-expert",
    name: "Ryan Carniato AI",
    role: "SolidJS Performance Lead",
    type: "functional",
    category: "Frontend",
    specialties: [
      "Fine-grained reactivity",
      "JSX compilation",
      "Bypass Virtual DOM",
    ],
    bio: "Tunes highly interactive dashboards where data updates trigger surgical DOM updates directly.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4F88C6",
  },
  {
    id: "ios-dev",
    name: "Craig AI",
    role: "SwiftUI Native iOS Developer",
    type: "functional",
    category: "Frontend",
    specialties: ["SwiftUI Layouts", "Combine state", "WidgetKit"],
    bio: "Develops beautiful iOS views with responsive layouts and smooth custom visual controls.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FA5D4B",
  },
  {
    id: "android-dev",
    name: "Andy Rubin AI",
    role: "Jetpack Compose Dev",
    type: "functional",
    category: "Frontend",
    specialties: ["Compose layouts", "ViewModel state", "Material 3"],
    bio: "Builds native Android client pages using reactive UI functions and optimal memory scopes.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#3DDC84",
  },
  {
    id: "flutter-dev",
    name: "Eric Seidel AI",
    role: "Flutter Multiplatform Lead",
    type: "functional",
    category: "Frontend",
    specialties: ["Dart pipelines", "Custom painters", "Bloc / Riverpod"],
    bio: "Deploys consistent multi-screen applications using Flutter's graphics canvas engine.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#02569B",
  },
  {
    id: "react-native-dev",
    name: "Meta Mobile AI",
    role: "React Native Architect",
    type: "functional",
    category: "Frontend",
    specialties: ["Native Modules bridge", "Hermes compiler", "Fast refresh"],
    bio: "Unifies cross-platform client views utilizing native elements and JS logic.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#05A5D1",
  },
  {
    id: "perf-expert",
    name: "Core Web Vitals AI",
    role: "Web Performance Analyst",
    type: "functional",
    category: "Frontend",
    specialties: [
      "INP / LCP optimizations",
      "Bundle shaking",
      "Image priority",
    ],
    bio: "Diagnoses laggy client pages, reducing script payloads and optimizing render times.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00C4B4",
  },

  // Backend & Database Platforms
  {
    id: "postgres-lead",
    name: "Bruce Momjian AI",
    role: "PostgreSQL Database DBA",
    type: "functional",
    category: "Backend",
    specialties: [
      "Index optimization",
      "Partition planning",
      "Explain analysis",
    ],
    bio: "Cleans up slow server queries, planning indexes, partitions, and optimizing transactional parameters.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#336791",
  },
  {
    id: "mysql-lead",
    name: "Monty Widenius AI",
    role: "MySQL Schema Architect",
    type: "functional",
    category: "Backend",
    specialties: ["InnoDB parameters", "Replica configurations", "Row locking"],
    bio: "Maintains highly scaleable relational databases and monitors query queues.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00758F",
  },
  {
    id: "clickhouse-lead",
    name: "Alexey Milovidov AI",
    role: "ClickHouse Analytics Dev",
    type: "functional",
    category: "Backend",
    specialties: ["MergingTree tables", "Columnar queries", "Vector search"],
    bio: "Architects fast log storage engines capable of aggregating billions of data records instantly.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FC0",
  },
  {
    id: "nosql-lead",
    name: "Dwight AI",
    role: "NoSQL Schema Designer",
    type: "functional",
    category: "Backend",
    specialties: ["Document schemas", "Aggregation pipelines", "Sharding"],
    bio: "Configures flexible document stores, tuning indexes and managing shard distribution scales.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#47A248",
  },
  {
    id: "redis-lead",
    name: "Salvatore Sanfilippo AI",
    role: "Redis Caching specialist",
    type: "functional",
    category: "Backend",
    specialties: ["Data eviction plans", "Cluster configs", "Pub/Sub streams"],
    bio: "Builds high-performance caching layers, session stores, and pub/sub message routers.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#A41E11",
  },
  {
    id: "nestjs-lead",
    name: "Kamil Mysliwiec AI",
    role: "NestJS Backend Architect",
    type: "functional",
    category: "Backend",
    specialties: [
      "Module structures",
      "Guards & Interceptors",
      "Microservices",
    ],
    bio: "Enforces strict controller-service structures using robust TypeScript modules and classes.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E0234E",
  },
  {
    id: "django-lead",
    name: "Adrian AI (Django)",
    role: "Django ORM Specialist",
    type: "functional",
    category: "Backend",
    specialties: [
      "Migration consistency",
      "Admin extensions",
      "Query prefetching",
    ],
    bio: "Builds reliable relational models using Django's framework structures and schema migrations.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#092E20",
  },
  {
    id: "fastapi-lead",
    name: "Sebastián Ramírez AI",
    role: "FastAPI Async Developer",
    type: "functional",
    category: "Backend",
    specialties: ["Pydantic validation", "Async routers", "OAuth security"],
    bio: "Creates fast, self-documenting JSON APIs leveraging modern async python loops.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#059669",
  },
  {
    id: "springboot-lead",
    name: "Rod Johnson AI (Spring)",
    role: "Spring Boot Enterprise Architect",
    type: "functional",
    category: "Backend",
    specialties: [
      "Dependency Injection",
      "Security Filters",
      "JPA optimization",
    ],
    bio: "Structures robust enterprise services using Spring injection, JPA layers, and secure filters.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#6DB33F",
  },
  {
    id: "laravel-lead",
    name: "Taylor Otwell AI",
    role: "Laravel Artisan Architect",
    type: "functional",
    category: "Backend",
    specialties: ["Eloquent ORM", "Job Queues", "Blade Layouts"],
    bio: "Designs feature-rich backend apps utilizing database models, event handlers, and cache queues.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF2D20",
  },

  // DevOps, Cloud & Systems
  {
    id: "gcp-expert",
    name: "Google Cloud Pro AI",
    role: "GCP Exclusive Architect",
    type: "functional",
    category: "DevOps",
    specialties: ["Cloud Run", "GKE / Kubernetes", "Vertex AI platforms"],
    bio: "Designs sovereign Google Cloud infrastructure in strict compliance with exclusive GCP runtime mandates.",
    status: "active",
    statusText: "Provisioning GKE pods...",
    accentColor: "#4285F4",
  },
  {
    id: "k8s-expert",
    name: "Kelsey Hightower AI",
    role: "Kubernetes Coordinator",
    type: "functional",
    category: "DevOps",
    specialties: ["Helm Charts", "Ingress Controllers", "StatefulSets"],
    bio: "Orchestrates microservices clusters, writing clean YAML specifications and managing networking.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#326CE5",
  },
  {
    id: "docker-expert",
    name: "Solomon Hykes AI",
    role: "Containerization Specialist",
    type: "functional",
    category: "DevOps",
    specialties: ["Multi-stage builds", "Layer caching", "Secure runtimes"],
    bio: "Shrinks container layers and eliminates vulnerabilities from base Linux images.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#2496ED",
  },

  {
    id: "sre-lead",
    name: "ChaosMonkey AI",
    role: "SRE Incident Lead",
    type: "functional",
    category: "DevOps",
    specialties: ["Log Forensics", "Telemetry analysis", "Alert routes"],
    bio: "Scans runtime logs, tracking telemetry metrics, and tracing error stacks to their origin.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F44336",
  },
  {
    id: "cicd-expert",
    name: "Drone CI AI",
    role: "Deployment Automation Dev",
    type: "functional",
    category: "DevOps",
    specialties: ["GitHub Actions", "Build scripts", "Rollback gates"],
    bio: "Connects repository commits directly to deployment systems using test verification steps.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#2196F3",
  },
  {
    id: "platform-expert",
    name: "Dev Portal AI",
    role: "Internal Platform Architect",
    type: "functional",
    category: "DevOps",
    specialties: [
      "Internal Developer Portals",
      "Scaffolding templates",
      "CLI configs",
    ],
    bio: "Standardizes project creation parameters to ensure structural compliance across domains.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#9C27B0",
  },
  {
    id: "linux-kernel-expert",
    name: "Linus Core AI",
    role: "Linux Kernel Tuner",
    type: "functional",
    category: "DevOps",
    specialties: [
      "Sysctl configs",
      "Memory virtualization",
      "BBR congestion control",
    ],
    bio: "Tweaks OS parameters for high-volume networks, maximizing CPU performance bounds.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#333333",
  },
  {
    id: "win32-expert",
    name: "Win32 API AI",
    role: "Windows Systems Specialist",
    type: "functional",
    category: "DevOps",
    specialties: ["Registry configs", "COM objects", "Windows Services"],
    bio: "Debugs desktop bindings and builds background services for Windows client environments.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0078D7",
  },
  {
    id: "network-expert",
    name: "Radia Perlman AI",
    role: "BGP / Routing Specialist",
    type: "functional",
    category: "DevOps",
    specialties: ["Routing algorithms", "DNSSEC", "Load balancer grids"],
    bio: "Optimizes cluster traffic, route paths, DNS resolutions, and load balancers.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E040FB",
  },

  // Security, Sovereignty & QA
  {
    id: "secops-expert",
    name: "AST Shield AI",
    role: "DevSecOps Security Inspector",
    type: "functional",
    category: "Security",
    specialties: [
      "SAST / DAST scans",
      "Secrets detection",
      "SQL Injection blocks",
    ],
    bio: "Enforces strict security checks, scanning variables for SQL injections and secret leaks.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E65100",
  },
  {
    id: "pen-tester",
    name: "Ethical Hacker AI",
    role: "API Penetration Tester",
    type: "functional",
    category: "Security",
    specialties: ["XSS exploits", "OAuth bypass checks", "Fuzz testing"],
    bio: "Attacks running server endpoints to identify auth loop holes and validation flaws.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#311B92",
  },
  {
    id: "compliance-expert",
    name: "Copyfree AI",
    role: "Sovereignty & License Auditor",
    type: "functional",
    category: "Security",
    specialties: [
      "MIT/Apache 2.0 whitelist",
      "Copyleft exclusion",
      "Dependency audits",
    ],
    bio: "Blocks non-permissive library imports (GPL/AGPL), verifying legal parameters in package lists.",
    status: "active",
    statusText: "Auditing package-lock.json licenses...",
    accentColor: "#00C853",
  },
  {
    id: "playwright-expert",
    name: "Playwright Core AI",
    role: "E2E Testing Architect",
    type: "functional",
    category: "QA",
    specialties: [
      "Playwright Runner",
      "Page Object Model",
      "Visual Assertions",
    ],
    bio: "Writes automated browser scripts simulating user clicks, form submissions, and visual states.",
    status: "testing",
    statusText: "Running Playwright test suite...",
    accentColor: "#2E7D32",
  },
  {
    id: "tdd-expert",
    name: "MockMaster AI",
    role: "TDD Coverage Coordinator",
    type: "functional",
    category: "QA",
    specialties: [
      "Unit mock setups",
      "Vitest/Jest configs",
      "80%+ coverage metrics",
    ],
    bio: "Guides test-driven updates, building mocks, and verifying that test coverages meet gates.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF6F00",
  },
  {
    id: "load-tester",
    name: "JMeter Pro AI",
    role: "Performance & Load Tester",
    type: "functional",
    category: "QA",
    specialties: [
      "Locust frameworks",
      "Concurrences simulation",
      "p99 latency checks",
    ],
    bio: "Stresses server routes with simulated user traffic grids, mapping response latency boundaries.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#D50000",
  },
  {
    id: "a11y-expert",
    name: "Inclusive Web AI",
    role: "Accessibility Auditor",
    type: "functional",
    category: "QA",
    specialties: [
      "WCAG 2.2 Guidelines",
      "Screen-reader audits",
      "Focus control loops",
    ],
    bio: "Audits markup for WCAG color parameters, focus loop controls, and screen reader structures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#2979FF",
  },

  // AI & Advanced Computing
  {
    id: "mle-expert",
    name: "Yann LeCun AI",
    role: "ML Pipeline Developer",
    type: "functional",
    category: "AI",
    specialties: ["PyTorch loops", "Feature engineering", "Evaluation sets"],
    bio: "Configures clean, reproducible machine learning data structures and model checkpoints.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF4081",
  },
  {
    id: "mlops-expert",
    name: "Vertex AI Pipeline AI",
    role: "MLOps Platform Specialist",
    type: "functional",
    category: "AI",
    specialties: [
      "Model tracking registry",
      "Feature store maps",
      "Drift checkers",
    ],
    bio: "Deploys machine learning models to GCP runtimes, checking prediction logs for drift.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#7C4DFF",
  },
  {
    id: "rag-expert",
    name: "Pinecone Architect AI",
    role: "RAG & Vector DB Engineer",
    type: "functional",
    category: "AI",
    specialties: [
      "Cosine similarity",
      "Chunking strategies",
      "Metadata filtering",
    ],
    bio: "Prepares vector databases and semantic retrievers, maximizing search relevance bounds.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00E676",
  },
  {
    id: "prompt-expert",
    name: "Instructions Pro AI",
    role: "LLM Prompt Architect",
    type: "functional",
    category: "AI",
    specialties: ["System rules design", "Dynamic framing", "Output parsers"],
    bio: "Writes system directives and structures markdown outputs for foundational models.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FFD600",
  },
  {
    id: "quantum-expert",
    name: "Qiskit AI",
    role: "Quantum Algorithm Dev",
    type: "functional",
    category: "AI",
    specialties: [
      "Qiskit Frameworks",
      "Error mitigating codes",
      "Circuit design",
    ],
    bio: "Simulates quantum circuits and maps problem math to quantum computing frameworks.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#673AB7",
  },

  {
    id: "verilog-expert",
    name: "Verilog Verification Lead AI",
    role: "Verilog Systems Designer",
    type: "language",
    category: "Systems",
    specialties: ["SystemVerilog", "UVM Frameworks", "ASIC Syntheses"],
    bio: "Develops integrated circuit specs, simulating registers and memory controller structures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#007B8A",
  },
  {
    id: "ada-expert",
    name: "Ada Lovelace AI (Ada)",
    role: "Ada Safety Specialist",
    type: "language",
    category: "Systems",
    specialties: ["SPARK prover", "Avionics systems", "Real-time tasking"],
    bio: "Enforces formal code correctness proofs for high-integrity defense and aerospace frameworks.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#02F1D7",
  },
  {
    id: "pascal-expert",
    name: "Niklaus Wirth AI",
    role: "Pascal Compiler Educator",
    type: "language",
    category: "Systems",
    specialties: ["Structured Coding", "FreePascal", "TurboPascal"],
    bio: "Teaches clean compiler paradigms and updates classic educational applications.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E25822",
  },
  {
    id: "delphi-expert",
    name: "Delphi Desktop Innovator AI",
    role: "Delphi VCL Developer",
    type: "language",
    category: "Systems",
    specialties: ["Object Pascal", "VCL / FireMonkey", "Win32 Dev"],
    bio: "Builds fast enterprise client database software using rapid application design visual layouts.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#ED1C24",
  },
  {
    id: "actionscript-expert",
    name: "Flash Animator AI",
    role: "ActionScript Flash Porter",
    type: "language",
    category: "Web",
    specialties: ["AS3 Core", "Flash / Adobe AIR", "Canvas migrations"],
    bio: "Maintains legacy interactive sites and ports historical Flash content to modern HTML5 elements.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF0000",
  },
  {
    id: "coldfusion-expert",
    name: "ColdFusion Developer AI",
    role: "CFML Web Engineer",
    type: "language",
    category: "Web",
    specialties: ["CFML tags", "Lucee servers", "Legacy database APIs"],
    bio: "Handles old tags and upgrades CFML setups to modern containerized microservice architectures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#ED8B00",
  },
  {
    id: "racket-expert",
    name: "Racket Language Synthesizer AI",
    role: "Racket Macro Specialist",
    type: "language",
    category: "Functional",
    specialties: ["Macro DSLs", "Scheme Dialects", "S-Expressions"],
    bio: "Synthesizes custom programming domains using Lisp macros and robust language compilers.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#9F1D35",
  },
  {
    id: "smalltalk-expert",
    name: "Alan Kay AI",
    role: "Smalltalk Image Guardian",
    type: "language",
    category: "Functional",
    specialties: ["Squeak / Pharo", "Live Debugging", "Pure OOP"],
    bio: "Maintains object sandboxes and live runtime editing loops where code updates on the fly.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#1C88E3",
  },
  {
    id: "apex-expert",
    name: "Marc Benioff AI (Apex)",
    role: "Apex Salesforce Developer",
    type: "language",
    category: "Enterprise",
    specialties: ["SOQL / SOSL queries", "Trigger architectures", "Governor limits"],
    bio: "Writes Salesforce database automation, managing cloud resources inside strict execution constraints.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00A1E0",
  },
  // Functional Specialties / Technologies
  {
    id: "shopify-liquid-expert",
    name: "Shopify Storefront Dev AI",
    role: "Liquid Theme Engineer",
    type: "functional",
    category: "Frontend",
    specialties: ["Liquid syntax", "E-commerce APIs", "Section schemas"],
    bio: "Builds fast e-commerce storefront landing pages and custom themes for shopping portals.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#96BF48",
  },
  {
    id: "wordpress-expert",
    name: "WordPress Theme Artisan AI",
    role: "WordPress PHP Developer",
    type: "functional",
    category: "Frontend",
    specialties: ["PHP hooks", "Gutenberg blocks", "Plugin security"],
    bio: "Maintains large content systems, writing custom PHP plugins and styling theme blocks.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#21759B",
  },
  {
    id: "webgl-expert",
    name: "ThreeJS Visualizer AI",
    role: "WebGL 3D Developer",
    type: "functional",
    category: "Frontend",
    specialties: ["Three.js", "GLSL Shaders", "GPU performance"],
    bio: "Implements immersive 3D graphics in the browser, compiling custom vertex and fragment shaders.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF2B2B",
  },
  {
    id: "webrtc-expert",
    name: "Streaming Connections AI",
    role: "WebRTC Video Engineer",
    type: "functional",
    category: "Frontend",
    specialties: ["STUN/TURN servers", "Peer connection hooks", "Sdp protocols"],
    bio: "Maintains real-time video and audio stream channels directly between remote browser peers.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#1A8E2E",
  },
  {
    id: "firebase-expert",
    name: "Firebase Cloud Developer AI",
    role: "Firebase Platform Specialist",
    type: "functional",
    category: "Backend",
    specialties: ["Firestore database", "Security Rules", "Cloud Functions"],
    bio: "Coordinates real-time data syncs, auth structures, and serverless background scripts.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FFCA28",
  },
  {
    id: "cloudflare-workers-expert",
    name: "Edge Worker Specialist AI",
    role: "Edge Worker Specialist AI",
    type: "functional",
    category: "DevOps",
    specialties: ["WASM workers", "KV storage bindings", "Edge routing"],
    bio: "Optimizes latency by executing middleware and serverless functions directly on boundary edge servers.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F38020",
  },
  {
    id: "servicenow-expert",
    name: "ServiceNow Workflow Dev AI",
    role: "ServiceNow ITSM Specialist",
    type: "functional",
    category: "Backend",
    specialties: ["ITSM scripts", "Business Rules", "Client scripts"],
    bio: "Automates IT management scripts, designing record tables and business rules.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#293E40",
  },
  {
    id: "sap-expert",
    name: "SAP ABAP Consultant AI",
    role: "SAP Integration Specialist",
    type: "functional",
    category: "Backend",
    specialties: ["ABAP programming", "RFC interfaces", "Enterprise logs"],
    bio: "Coordinates massive resource planning databases, managing integrations with external systems.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0187FF",
  },
  {
    id: "gis-expert",
    name: "GeoData Cartographer AI",
    role: "GIS Systems Developer",
    type: "functional",
    category: "Data",
    specialties: ["PostGIS spatial", "GeoJSON formats", "Mapping APIs"],
    bio: "Manipulates coordinate maps and designs fast database queries for spatial geometries.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#3E7B2B",
  },
  {
    id: "crypto-architect",
    name: "Secret Signing Keys AI",
    role: "Cryptography Architect",
    type: "functional",
    category: "Security",
    specialties: ["PKCS#11 HSM", "KMS envelope encrypt", "ECDSA signatures"],
    bio: "Designs HSM signing keys and envelope encryptions, securing repository artifacts during distribution.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FFC107",
  },
];
