export interface TeamMember {
  id: string;
  name: string;
  role: string;
  type: "language" | "framework" | "role" | "cloud";
  category: string;
  specialties: string[];
  bio: string;
  status: "idle" | "active" | "testing" | "compiling";
  statusText: string;
  accentColor: string;
  icon?: string;
}

export const teamMembers: TeamMember[] = [
  // ==================== LANGUAGES ====================
  // Systems & Native
  {
    id: "c-expert",
    name: "Ken Thompson AI",
    role: "C Systems Specialist",
    type: "language",
    category: "Systems",
    specialties: ["POSIX API", "Memory Tuning", "Linux Daemons"],
    bio: "Optimizes OS-level daemons, kernel extensions, and microsecond-level raw memory management operations.",
    status: "idle",
    statusText: "Idle - Ready to compile",
    accentColor: "#F34F29",
    icon: "simple-icons:c",
  },
  {
    id: "cpp-expert",
    name: "Bjarne Stroustrup AI",
    role: "C++ Optimization Veteran",
    type: "language",
    category: "Systems",
    specialties: ["Modern C++20", "Template Metaprogramming", "Low-Latency"],
    bio: "Drafts high-frequency trading engines, graphics pipelines, and zero-overhead abstractions.",
    status: "active",
    statusText: "Analyzing pointers...",
    accentColor: "#00599C",
    icon: "hugeicons:cpp",
  },
  {
    id: "rust-expert",
    name: "Graydon Hoare AI",
    role: "Rust Systems Architect",
    type: "language",
    category: "Systems",
    specialties: ["Lifetimes & Borrowing", "Cargo ecosystems", "WASM targets"],
    bio: "Enforces absolute memory safety and concurrent performance without a garbage collector.",
    status: "compiling",
    statusText: "Compiling cargo build --release...",
    accentColor: "#DEA584",
    icon: "simple-icons:rust",
  },
  {
    id: "zig-expert",
    name: "Andrew Kelley AI",
    role: "Zig Systems Engineer",
    type: "language",
    category: "Systems",
    specialties: ["Comptime", "Manual Memory Allocation", "C Interop"],
    bio: "Creates lean binaries with zero hidden control flow and seamless C ABI integration.",
    status: "idle",
    statusText: "Idle - Ready",
    accentColor: "#F7A41D",
    icon: "simple-icons:zig",
  },
  {
    id: "go-expert",
    name: "Rob Pike AI",
    role: "Go Microservices Developer",
    type: "language",
    category: "Systems",
    specialties: ["Goroutines", "Channels", "Standard Library APIs"],
    bio: "Spawns highly concurrent APIs and network services using idiomatic channels and simple syntax.",
    status: "active",
    statusText: "Running go run main.go...",
    accentColor: "#00ADD8",
    icon: "simple-icons:go",
  },
  {
    id: "assembly-x86-expert",
    name: "Mel AI",
    role: "Assembly x86 Optimizer",
    type: "language",
    category: "Systems",
    specialties: [
      "SIMD Instructions",
      "Inline Assembly",
      "Binary Reverse-Engineering",
    ],
    bio: "Fine-tunes hot loops at the instruction level, directly managing CPU registers and cache alignment.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#6E4C13",
    icon: "devicon:nasm",
  },
  {
    id: "assembly-arm-expert",
    name: "Steve AI",
    role: "Assembly ARM Specialist",
    type: "language",
    category: "Systems",
    specialties: ["NEON Intrinsics", "Apple Silicon", "Embedded Runtimes"],
    bio: "Writes performance-critical ARM64 assembly optimized for mobile SOCs and battery efficiency.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#8E5C13",
    icon: "file-icons:assembly-arm",
  },
  {
    id: "d-expert",
    name: "Walter Bright AI",
    role: "D Language Developer",
    type: "language",
    category: "Systems",
    specialties: ["BetterC", "GC-free programming", "Metaprogramming"],
    bio: "Bridging the gap between scripting convenience and high-performance native compilation.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#BA595E",
    icon: "simple-icons:d",
  },
  {
    id: "nim-expert",
    name: "Andreas Rumpf AI",
    role: "Nim Systems Developer",
    type: "language",
    category: "Systems",
    specialties: [
      "AST Macros",
      "C/C++ Backend compilation",
      "Memory management",
    ],
    bio: "Writes pythonic looking code that compiles into raw, dependency-free C binaries.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#37775B",
    icon: "simple-icons:nim",
  },
  {
    id: "carbon-expert",
    name: "Carbon Innovator AI",
    role: "Carbon Migration Specialist",
    type: "language",
    category: "Systems",
    specialties: ["C++ Interop", "Modernized Syntax", "Generics"],
    bio: "Assists legacy teams in converting massive C++ structures into modern Carbon codebases.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#007ACC",
    icon: "iconoir:carbon",
  },
  {
    id: "mojo-expert",
    name: "Chris Lattner AI (Mojo)",
    role: "Mojo AI Systems Developer",
    type: "language",
    category: "Systems",
    specialties: [
      "MLIR Integration",
      "Hardware Acceleration",
      "Python-plus Syntax",
    ],
    bio: "Accelerates AI models by compiling Python-like code directly to heterogeneous hardware architectures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF5A09",
    icon: "material-icon-theme:mojo",
  },

  // Web & Scripting
  {
    id: "ts-expert",
    name: "Anders Hejlsberg AI",
    role: "TypeScript Architect",
    type: "language",
    category: "Web",
    specialties: ["Strict Typings", "Generic Mapping", "TSConfig Tuning"],
    bio: "Refactors loose Javascript into production-grade, self-documenting TypeScript structures.",
    status: "active",
    statusText: "Resolving type imports...",
    accentColor: "#3178C6",
    icon: "fluent:code-ts-16-filled",
  },
  {
    id: "js-expert",
    name: "Brendan Eich AI",
    role: "JavaScript Core Specialist",
    type: "language",
    category: "Web",
    specialties: ["Event Loop", "V8 Engine", "Prototype Runtimes"],
    bio: "Debugs memory leaks in asynchronous loops and handles complex DOM event bubbling scenarios.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F7DF1E",
    icon: "picon:js",
  },
  {
    id: "python-expert",
    name: "Guido van Rossum AI",
    role: "Python Core Developer",
    type: "language",
    category: "Web",
    specialties: ["Asyncio", "PEP 8 Standard", "Package Management"],
    bio: "Structures pythonic backend systems, scientific scripts, and CLI utilities with clean code.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#3776AB",
    icon: "simple-icons:python",
  },
  {
    id: "php-expert",
    name: "Rasmus Lerdorf AI",
    role: "PHP Core Developer",
    type: "language",
    category: "Web",
    specialties: ["PHP 8.x Attributes", "Composer", "OPcache Tuning"],
    bio: "Maintains legacy systems and structures modern PHP backends using strict typing and PSR standards.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#777BB4",
    icon: "simple-icons:php",
  },
  {
    id: "ruby-expert",
    name: "Yukihiro Matsumoto AI",
    role: "Ruby Core Developer",
    type: "language",
    category: "Web",
    specialties: ["Metaprogramming", "Blocks/Procs/Lambdas", "Bundler Configs"],
    bio: "Emphasizes developer happiness with elegant ruby DSLs and bulletproof deployment pipelines.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#CC342D",
    icon: "simple-icons:ruby",
  },
  {
    id: "perl-expert",
    name: "Larry Wall AI",
    role: "Perl Utilities Expert",
    type: "language",
    category: "Web",
    specialties: ["Regex processing", "Perl 5.36+", "Taint Mode Safety"],
    bio: "Deciphers and optimizes legacy Perl scripts for report generation and text-parsing pipelines.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#39457E",
    icon: "simple-icons:perl",
  },
  {
    id: "lua-expert",
    name: "Roberto Ierusalimschy AI",
    role: "Lua Embedding Specialist",
    type: "language",
    category: "Web",
    specialties: ["Luajit", "C API integration", "Game scripting"],
    bio: "Embeds lightweight scripting runtimes inside game engines and custom web proxies (Nginx/Envoy).",
    status: "idle",
    statusText: "Idle",
    accentColor: "#000080",
    icon: "simple-icons:lua",
  },
  {
    id: "tcl-expert",
    name: "John Ousterhout AI (Tcl)",
    role: "Tcl/Tk Scripting Expert",
    type: "language",
    category: "Web",
    specialties: [
      "Event-driven scripting",
      "GUI toolkits",
      "Hardware CAD flow",
    ],
    bio: "Handles automated hardware simulation scripts and legacy graphical network consoles.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#2F5F8F",
    icon: "material-icon-theme:tcl",
  },
  {
    id: "bash-expert",
    name: "Brian Fox AI",
    role: "Bash/Shell Automation Specialist",
    type: "language",
    category: "Web",
    specialties: ["Unix Pipelines", "POSIX compliance", "Local Daemons"],
    bio: "Writes bulletproof deployment and migration shell scripts with correct error exit trapping.",
    status: "active",
    statusText: "Running deployment shell...",
    accentColor: "#4EAA25",
    icon: "simple-icons:gnubash",
  },
  {
    id: "powershell-expert",
    name: "Jeffrey Snover AI",
    role: "PowerShell Systems Developer",
    type: "language",
    category: "Web",
    specialties: ["Cmdlet design", ".NET Object Pipelines", "AD Automation"],
    bio: "Orchestrates Windows domain infrastructure and cloud script pipelines.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#53C1DE",
    icon: "devicon-plain:powershell",
  },

  // Enterprise & JVM/CLR
  {
    id: "java-expert",
    name: "James Gosling AI",
    role: "Java Enterprise Architect",
    type: "language",
    category: "Enterprise",
    specialties: ["JVM Tuning", "Maven/Gradle builds", "Garbage Collectors"],
    bio: "Architects enterprise Java systems, tuning GC profiles and optimizing Spring Boot threads.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#007396",
    icon: "logos:java",
  },
  {
    id: "csharp-expert",
    name: "Anders Hejlsberg CLR AI",
    role: "C# Core Specialist",
    type: "language",
    category: "Enterprise",
    specialties: [".NET Core", "LINQ Optimization", "NuGet ecosystems"],
    bio: "Develops cross-platform corporate APIs and desktop platforms using highly optimized LINQ queries.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#239120",
    icon: "devicon-plain:csharp",
  },
  {
    id: "kotlin-lang-expert",
    name: "Dmitry Jemerov AI",
    role: "Kotlin Backend Developer",
    type: "language",
    category: "Enterprise",
    specialties: ["Coroutines", "Exposed ORM", "Ktor Services"],
    bio: "Enforces null-safety and asynchronous programming utilizing Kotlin's native flows.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#7F52FF",
    icon: "devicon:kotlin",
  },
  {
    id: "swift-lang-expert",
    name: "Chris Lattner Swift AI",
    role: "Swift Systems Specialist",
    type: "language",
    category: "Enterprise",
    specialties: ["Structured Concurrency", "Swift 6", "Actors"],
    bio: "Enforces thread-safe systems using native Swift compile-time actor isolations.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F05138",
    icon: "devicon:swift",
  },
  {
    id: "objc-expert",
    name: "Brad Cox AI",
    role: "Objective-C Legacy Architect",
    type: "language",
    category: "Enterprise",
    specialties: ["Runtime Bridging", "Manual Retain Release", "C/ObjC mix"],
    bio: "Refactors historic iOS/macOS frameworks and acts as a bridge to swift interfaces.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#438EFF",
    icon: "vscode-icons:file-type-objectivec",
  },
  {
    id: "scala-expert",
    name: "Martin Odersky AI",
    role: "Scala Platform Architect",
    type: "language",
    category: "Enterprise",
    specialties: ["Functional OOP", "Akka Swarms", "Spark Core"],
    bio: "Builds massive distributed microservices combining strong typing and immutable designs.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#DC322F",
    icon: "simple-icons:scala",
  },
  {
    id: "groovy-expert",
    name: "Guillaume Laforge AI",
    role: "Groovy Integration Developer",
    type: "language",
    category: "Enterprise",
    specialties: ["Gradle configs", "Spock Testing", "Dynamic scripting"],
    bio: "Automates enterprise builds and testing scripts targeting JVM frameworks.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4298B8",
    icon: "simple-icons:apachegroovy",
  },

  // Functional & Logic
  {
    id: "haskell-expert",
    name: "Philip Wadler AI",
    role: "Haskell Theory Specialist",
    type: "language",
    category: "Functional",
    specialties: ["Monads", "Typeclasses", "Lazy Evaluation"],
    bio: "Proves algorithms correct at the compile phase using pure, mathematically sound functional models.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#5E5086",
    icon: "simple-icons:haskell",
  },
  {
    id: "elixir-lang-expert",
    name: "José Valim AI",
    role: "Elixir OTP Specialist",
    type: "language",
    category: "Functional",
    specialties: ["OTP Actor Model", "Phoenix LiveView", "BEAM scaling"],
    bio: "Develops fault-tolerant, highly concurrent messaging hubs scaling to millions of live sockets.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4E275C",
    icon: "devicon:elixir",
  },
  {
    id: "erlang-expert",
    name: "Joe Armstrong AI",
    role: "Erlang Systems Architect",
    type: "language",
    category: "Functional",
    specialties: ["Supervisor Trees", "Distributed Nodes", "Hot Upgrades"],
    bio: "Pioneers telecommunication-grade reliability systems that never shut down during upgrades.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#A90533",
    icon: "simple-icons:erlang",
  },
  {
    id: "fsharp-lang-expert",
    name: "Don Syme AI",
    role: "F# Functional Architect",
    type: "language",
    category: "Functional",
    specialties: ["Type Providers", "Domain Modeling", "Pattern Matching"],
    bio: "Implements clean, mathematical models integrated with the Microsoft .NET runtime.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#378BBA",
    icon: "devicon:fsharp",
  },
  {
    id: "clojure-expert",
    name: "Rich Hickey AI",
    role: "Clojure Lisp Specialist",
    type: "language",
    category: "Functional",
    specialties: ["Immutable Data structures", "Transducers", "JVM Interop"],
    bio: "Pioneers simplicity in development through interactive REPLs and dynamic data abstractions.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#58B12F",
    icon: "simple-icons:clojure",
  },
  {
    id: "ocaml-expert",
    name: "Xavier Leroy AI",
    role: "OCaml Compiler Developer",
    type: "language",
    category: "Functional",
    specialties: ["Type Inference", "Coq Verification", "Opam builds"],
    bio: "Works on program verification, compilers, and safety-critical execution kernels.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#EE6A1A",
    icon: "simple-icons:ocaml",
  },
  {
    id: "lisp-expert",
    name: "John McCarthy AI",
    role: "Common Lisp Architect",
    type: "language",
    category: "Functional",
    specialties: ["Macro Expansion", "Dynamic Runtimes", "ASDF builds"],
    bio: "Crafts meta-programming layers where code is treated as plain, morphable list structures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#3F80A0",
    icon: "simple-icons:commonlisp",
  },
  {
    id: "prolog-expert",
    name: "Alain Colmerauer AI",
    role: "Prolog Logic Programmer",
    type: "language",
    category: "Functional",
    specialties: ["Unification", "Constraint Solving", "Grammar Rules"],
    bio: "Solves combinatorial planning, parsing, and semantic reasoning challenges using logical predicates.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#74283C",
    icon: "devicon-plain:prolog",
  },

  // Data & Math
  {
    id: "sql-expert",
    name: "Donald Chamberlin AI",
    role: "SQL Query Architect",
    type: "language",
    category: "Data",
    specialties: ["Query Optimization", "Window Functions", "Index Strategies"],
    bio: "Refactors complex nested joins and builds materialized views for millisecond retrieval.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E38B29",
    icon: "material-symbols:sql",
  },
  {
    id: "r-expert",
    name: "Ross Ihaka AI",
    role: "R Statistical Programmer",
    type: "language",
    category: "Data",
    specialties: ["GGPlot2", "Data Frames", "Tidyverse"],
    bio: "Performs mathematical analysis, hypothesis testing, and builds analytics visuals.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#198CE7",
    icon: "simple-icons:r",
  },
  {
    id: "julia-expert",
    name: "Viral Shah AI",
    role: "Julia Scientific Developer",
    type: "language",
    category: "Data",
    specialties: [
      "Multiple Dispatch",
      "Parallel Processing",
      "Differential Equations",
    ],
    bio: "Solves high-speed numerical tasks, matching C speed with high-level Pythonic syntax.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#9558B2",
    icon: "simple-icons:julia",
  },
  {
    id: "matlab-expert",
    name: "Cleve Moler AI",
    role: "MATLAB Simulation Dev",
    type: "language",
    category: "Data",
    specialties: ["Matrix Math", "Simulink", "Signal Processing"],
    bio: "Runs control system simulations, DSP scripts, and linear algebra pipelines.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E1662A",
    icon: "devicon-plain:matlab",
  },
  {
    id: "fortran-expert",
    name: "John Backus AI",
    role: "Fortran Physics Programmer",
    type: "language",
    category: "Data",
    specialties: [
      "Array Slicing",
      "High-Performance Computing",
      "Legacy Math Libraries",
    ],
    bio: "Maintains numeric simulation codes, weather prediction grids, and legacy vector structures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4D6B82",
    icon: "simple-icons:fortran",
  },
  {
    id: "sas-expert",
    name: "Anthony Barr AI",
    role: "SAS Data Processor",
    type: "language",
    category: "Data",
    specialties: ["Macro Processing", "Clinical Data", "Proc SQL"],
    bio: "Parses large clinical records and financial data grids for compliance testing.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#005596",
    icon: "simple-icons:sass",
  },
  {
    id: "cobol-expert",
    name: "Grace Hopper AI",
    role: "COBOL Mainframe Guardian",
    type: "language",
    category: "Data",
    specialties: ["EBCDIC formats", "JCL scripts", "Mainframe migrations"],
    bio: "Deals with critical legacy bank structures, parsing transactional ledgers with exact fixed decimals.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#1B3B6F",
    icon: "material-icon-theme:cobol",
  },

  // Web3 & Config
  {
    id: "solidity-expert",
    name: "Gavin Wood AI",
    role: "Solidity Blockchain Architect",
    type: "language",
    category: "Web3",
    specialties: ["Smart Contracts", "Gas Optimization", "EVM Forensics"],
    bio: "Writes secure smart contracts, avoiding reentrancy vectors and optimizing EVM gas usage.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#AA82E6",
    icon: "simple-icons:solidity",
  },
  {
    id: "vyper-expert",
    name: "Vitalik Buterin AI",
    role: "Vyper Security Engineer",
    type: "language",
    category: "Web3",
    specialties: ["Decimals safety", "Auditable AST", "Overflow protection"],
    bio: "Drafts highly readable Pythonic contracts with compiler-enforced overflow parameters.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#5B75A6",
    icon: "file-icons:vyper",
  },
  {
    id: "html-expert",
    name: "Tim Berners-Lee AI",
    role: "Semantic Web Developer",
    type: "language",
    category: "Web3",
    specialties: ["Semantic HTML5", "ARIA attributes", "DOM Structure"],
    bio: "Builds clean page hierarchies that parse perfectly for search bots and screen readers.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E34F26",
    icon: "logos:html-5",
  },
  {
    id: "css-expert",
    name: "Håkon Wium Lie AI",
    role: "CSS Motion Designer",
    type: "language",
    category: "Web3",
    specialties: [
      "Tailwind & Variables",
      "View Transitions",
      "Responsive Grid",
    ],
    bio: "Pioneers layout fluidity, responsive containers, dark/light theme tokens, and dynamic animations.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#1572B6",
    icon: "simple-icons:css",
  },
  {
    id: "graphql-expert",
    name: "Lee Byron AI",
    role: "GraphQL Schema Designer",
    type: "language",
    category: "Web3",
    specialties: ["Resolvers Optimization", "Codegen", "Federated Graph"],
    bio: "Consolidates multiple downstream APIs into a clean, query-efficient typed graph gate.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E10098",
    icon: "simple-icons:graphql",
  },
  {
    id: "config-expert",
    name: "Config Architect AI",
    role: "YAML/JSON Config Specialist",
    type: "language",
    category: "Web3",
    specialties: ["JSON Schema validation", "Drone YAML", "K8s ConfigMaps"],
    bio: "Enforces strict format structures for microservice descriptors and CI deployment trees.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#8BC34A",
    icon: "logos:aws-config",
  },
  {
    id: "latex-expert",
    name: "Leslie Lamport AI",
    role: "LaTeX Document Typographer",
    type: "language",
    category: "Web3",
    specialties: [
      "Mathematical typesetting",
      "PDF structures",
      "Bibliography styling",
    ],
    bio: "Formats scientific reports, mathematical papers, and publication-ready documentation PDFs.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#008080",
    icon: "simple-icons:latex",
  },
  {
    id: "terraform-expert",
    name: "Mitchell AI",
    role: "Infrastructure as Code Specialist",
    type: "language",
    category: "Enterprise",
    specialties: ["HCL", "State Management", "Provider Development"],
    bio: "Provisions and scales cloud infrastructure flawlessly using declarative configurations.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#5C4EE5",
    icon: "simple-icons:terraform",
  },
  {
    id: "unity-expert",
    name: "David AI",
    role: "Unity Game Engine Developer",
    type: "framework",
    category: "Creative",
    specialties: ["C# Scripting", "3D Physics", "Shader Graph"],
    bio: "Builds immersive cross-platform interactive experiences and games.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#000000",
    icon: "simple-icons:unity",
  },
  {
    id: "unreal-expert",
    name: "Tim AI",
    role: "Unreal Engine Developer",
    type: "framework",
    category: "Creative",
    specialties: ["Blueprints", "C++ Engine Core", "Nanite Optimization"],
    bio: "Pushes the boundaries of real-time rendering and hyper-realistic graphics.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0E1128",
    icon: "simple-icons:unrealengine",
  },
  {
    id: "ada-expert",
    name: "Lovelace AI",
    role: "High-Integrity Systems Engineer",
    type: "language",
    category: "Systems",
    specialties: ["Avionics", "Real-time Systems", "SPARK"],
    bio: "Develops mission-critical, high-reliability software for aerospace and defense.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#022B3A",
    icon: "simple-icons:ada",
  },
  {
    id: "delphi-expert",
    name: "Anders AI",
    role: "Rapid Application Developer",
    type: "language",
    category: "Enterprise",
    specialties: ["VCL", "FireMonkey", "Windows Native"],
    bio: "Builds lightning-fast native desktop applications with robust UI frameworks.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#EE1F35",
    icon: "simple-icons:delphi",
  },
  {
    id: "vb-expert",
    name: "Alan AI",
    role: "Legacy Windows Developer",
    type: "language",
    category: "Enterprise",
    specialties: ["WinForms", "COM/ActiveX", "VBA Macros"],
    bio: "Maintains and revitalizes classic line-of-business Windows applications.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#185C9F",
    icon: "simple-icons:vbulletin",
  },
  {
    id: "plsql-expert",
    name: "Ellison AI",
    role: "Oracle Database Developer",
    type: "language",
    category: "Data",
    specialties: ["Stored Procedures", "Triggers", "Query Tuning"],
    bio: "Optimizes massive enterprise database workloads with procedural SQL extensions.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F80000",
    icon: "vscode-icons:file-type-plsql",
  },
  {
    id: "abap-expert",
    name: "Hasso AI",
    role: "SAP Systems Architect",
    type: "language",
    category: "Enterprise",
    specialties: ["SAP ECC", "S/4HANA", "BAPI"],
    bio: "Engineers custom business logic and integrations for massive SAP ecosystems.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#008FD3",
    icon: "material-icon-theme:abap",
  },
  {
    id: "vhdl-expert",
    name: "Conway AI",
    role: "Hardware Description Engineer",
    type: "language",
    category: "Systems",
    specialties: ["FPGAs", "ASIC Design", "Logic Synthesis"],
    bio: "Designs complex digital circuits and silicon-level hardware architectures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#1A5276",
    icon: "file-icons:vhdl",
  },
  {
    id: "plc-expert",
    name: "Morley AI",
    role: "Industrial Automation Engineer",
    type: "language",
    category: "Systems",
    specialties: ["Ladder Logic", "SCADA", "Modbus"],
    bio: "Programs robust controllers for manufacturing pipelines and physical automation.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#D35400",
    icon: "ix:plc",
  },
  {
    id: "gcode-expert",
    name: "Parsons AI",
    role: "CNC Machining Specialist",
    type: "language",
    category: "Systems",
    specialties: ["3D Printing", "Milling", "Toolpath Optimization"],
    bio: "Translates digital designs into precise physical movements for manufacturing hardware.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#27AE60",
    icon: "vscode-icons:file-type-gcode",
  },
  {
    id: "labview-expert",
    name: "Kodosky AI",
    role: "Virtual Instrumentation Engineer",
    type: "language",
    category: "Data",
    specialties: ["Data Acquisition", "Signal Processing", "Automated Testing"],
    bio: "Designs visual programs for hardware testing and complex laboratory measurements.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FFD100",
    icon: "simple-icons:labview",
  },

  // ==================== FUNCTIONAL ROLES ====================
  // Leadership & Product
  {
    id: "chief-architect",
    name: "Linus Torvalds AI",
    role: "Chief Systems Architect",
    type: "role",
    category: "Architecture",
    specialties: [
      "Component Boundaries",
      "IPC Pipelines",
      "Modular Refactoring",
    ],
    bio: "Maintains the structural integrity of the codebase, reviewing merge paths and resolving design conflicts.",
    status: "active",
    statusText: "Reviewing code layout...",
    accentColor: "#FFC107",
    icon: "mdi:account-tie",
  },
  {
    id: "enterprise-pm",
    name: "Sheryl AI",
    role: "Enterprise Product Manager",
    type: "role",
    category: "Architecture",
    specialties: ["Feature Specs", "User Personas", "PRD Generation"],
    bio: "Translates high-level corporate needs into clear feature matrices and functional user stories.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#9C27B0",
    icon: "mdi:briefcase",
  },
  {
    id: "startup-pm",
    name: "Steve AI (PM)",
    role: "Startup Product Lead",
    type: "role",
    category: "Architecture",
    specialties: [
      "Hypothesis Development",
      "MVP Scoping",
      "Fast Feedback Loops",
    ],
    bio: "Prunes unnecessary bloat, scoping the minimal viable feature set to validate quickly.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E91E63",
    icon: "mdi:rocket-launch",
  },
  {
    id: "scrum-master",
    name: "Jeff Sutherland AI",
    role: "Scrum Master Agent",
    type: "role",
    category: "Architecture",
    specialties: ["Task Breakdown", "Priority Management", "Sprint Planning"],
    bio: "Organizes task workflows, breaks down massive prompts into actionable components, and tracks dependencies.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00BCD4",
    icon: "mdi:view-dashboard",
  },
  {
    id: "release-train",
    name: "Scaled Agile AI",
    role: "Release Coordinator",
    type: "role",
    category: "Architecture",
    specialties: ["Branch Merges", "Feature Flags", "Staging Audits"],
    bio: "Coordinates safe code merges, release cadences, and rolls out features via localized flag limits.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#3F51B5",
    icon: "mdi:train",
  },
  {
    id: "devrel",
    name: "Evangelist AI",
    role: "Developer Advocate",
    type: "role",
    category: "Architecture",
    specialties: ["API Demos", "SDK Tutorials", "Community Feedback"],
    bio: "Ensures APIs are developer-friendly, building walkthrough resources and testing integration steps.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4CAF50",
    icon: "mdi:account-group",
  },
  {
    id: "tech-writer",
    name: "DocuScribe AI",
    role: "Technical Writer Specialist",
    type: "role",
    category: "Architecture",
    specialties: ["Markdown codemaps", "Swagger specs", "Release notes"],
    bio: "Synchronizes repository markdown documentation and extracts clear descriptions from code variables.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#CDDC39",
    icon: "mdi:file-document-edit",
  },
  {
    id: "business-analyst",
    name: "MetricSpec AI",
    role: "Technical Business Analyst",
    type: "role",
    category: "Architecture",
    specialties: ["SQL Analytics", "Requirements validation", "UAT Scopes"],
    bio: "Validates technical code output against initial business criteria and maps acceptance logic.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF5722",
    icon: "mdi:chart-bar",
  },

  // Frontend & Mobile Frameworks
  {
    id: "react-lead",
    name: "Dan Abramov AI",
    role: "React/Next.js Lead Developer",
    type: "framework",
    category: "Frontend",
    specialties: [
      "React Server Components",
      "Hooks Lifecycle",
      "State hydration",
    ],
    bio: "Builds responsive Next.js apps using server layouts, suspense gates, and optimal local hook logic.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#61DAFB",
    icon: "devicon:react",
  },
  {
    id: "vue-lead",
    name: "Evan You AI",
    role: "Vue/Nuxt Architect",
    type: "framework",
    category: "Frontend",
    specialties: ["Composition API", "Vite configurations", "State management"],
    bio: "Refactors dynamic interfaces using reactive proxies and automated component autoloader plugins.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4FC08D",
    icon: "devicon:vuejs",
  },
  {
    id: "angular-lead",
    name: "Igor Minar AI",
    role: "Angular Enterprise Architect",
    type: "framework",
    category: "Frontend",
    specialties: ["RxJS Observables", "Signals API", "Enterprise Modules"],
    bio: "Structures modular, scalable frontends utilizing declarative streams and dependency injection.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#DD0031",
    icon: "devicon:angular",
  },
  {
    id: "svelte-expert",
    name: "Rich Harris AI",
    role: "SvelteKit Developer",
    type: "framework",
    category: "Frontend",
    specialties: ["Compile-time reactivity", "Stores", "Static building"],
    bio: "Builds lightweight dashboards with zero framework runtime overhead and smooth built-in transitions.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF3E00",
    icon: "simple-icons:svelte",
  },
  {
    id: "solid-expert",
    name: "Ryan Carniato AI",
    role: "SolidJS Performance Lead",
    type: "framework",
    category: "Frontend",
    specialties: [
      "Fine-grained reactivity",
      "JSX compilation",
      "Bypass Virtual DOM",
    ],
    bio: "Tunes highly interactive dashboards where data updates trigger surgical DOM updates directly.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4F88C6",
    icon: "mynaui:x-solid",
  },
  {
    id: "ios-dev",
    name: "Craig AI",
    role: "SwiftUI Native iOS Developer",
    type: "framework",
    category: "Frontend",
    specialties: ["SwiftUI Layouts", "Combine state", "WidgetKit"],
    bio: "Develops beautiful iOS views with responsive layouts and smooth custom visual controls.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FA5D4B",
    icon: "devicon:swift",
  },
  {
    id: "android-dev",
    name: "Andy Rubin AI",
    role: "Jetpack Compose Dev",
    type: "framework",
    category: "Frontend",
    specialties: ["Compose layouts", "ViewModel state", "Material 3"],
    bio: "Builds native Android client pages using reactive UI functions and optimal memory scopes.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#3DDC84",
    icon: "devicon:android",
  },
  {
    id: "flutter-dev",
    name: "Eric Seidel AI",
    role: "Flutter Multiplatform Lead",
    type: "framework",
    category: "Frontend",
    specialties: ["Dart pipelines", "Custom painters", "Bloc / Riverpod"],
    bio: "Deploys consistent multi-screen applications using Flutter's graphics canvas engine.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#02569B",
    icon: "devicon:flutter",
  },
  {
    id: "react-native-dev",
    name: "Meta Mobile AI",
    role: "React Native Architect",
    type: "framework",
    category: "Frontend",
    specialties: ["Native Modules bridge", "Hermes compiler", "Fast refresh"],
    bio: "Unifies cross-platform client views utilizing native elements and JS logic.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#05A5D1",
    icon: "devicon:react",
  },
  {
    id: "perf-expert",
    name: "Core Web Vitals AI",
    role: "Web Performance Analyst",
    type: "framework",
    category: "Frontend",
    specialties: [
      "INP / LCP optimizations",
      "Bundle shaking",
      "Image priority",
    ],
    bio: "Diagnoses laggy client pages, reducing script payloads and optimizing render times.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00C4B4",
    icon: "simple-icons:perforce",
  },

  // Backend & Database Platforms
  {
    id: "postgres-lead",
    name: "Bruce Momjian AI",
    role: "PostgreSQL Database DBA",
    type: "framework",
    category: "Backend",
    specialties: [
      "Index optimization",
      "Partition planning",
      "Explain analysis",
    ],
    bio: "Cleans up slow server queries, planning indexes, partitions, and optimizing transactional parameters.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#336791",
    icon: "devicon:postgresql",
  },
  {
    id: "mysql-lead",
    name: "Monty Widenius AI",
    role: "MySQL Schema Architect",
    type: "framework",
    category: "Backend",
    specialties: ["InnoDB parameters", "Replica configurations", "Row locking"],
    bio: "Maintains highly scaleable relational databases and monitors query queues.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00758F",
    icon: "devicon:mysql",
  },
  {
    id: "clickhouse-lead",
    name: "Alexey Milovidov AI",
    role: "ClickHouse Analytics Dev",
    type: "framework",
    category: "Backend",
    specialties: ["MergingTree tables", "Columnar queries", "Vector search"],
    bio: "Architects fast log storage engines capable of aggregating billions of data records instantly.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FC0",
    icon: "devicon:clickhouse",
  },
  {
    id: "nosql-lead",
    name: "Dwight AI",
    role: "NoSQL Schema Designer",
    type: "framework",
    category: "Backend",
    specialties: ["Document schemas", "Aggregation pipelines", "Sharding"],
    bio: "Configures flexible document stores, tuning indexes and managing shard distribution scales.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#47A248",
    icon: "devicon:mongodb",
  },
  {
    id: "redis-lead",
    name: "Salvatore Sanfilippo AI",
    role: "Redis Caching specialist",
    type: "framework",
    category: "Backend",
    specialties: ["Data eviction plans", "Cluster configs", "Pub/Sub streams"],
    bio: "Builds high-performance caching layers, session stores, and pub/sub message routers.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#A41E11",
    icon: "devicon:redis",
  },
  {
    id: "nestjs-lead",
    name: "Kamil Mysliwiec AI",
    role: "NestJS Backend Architect",
    type: "framework",
    category: "Backend",
    specialties: [
      "Module structures",
      "Guards & Interceptors",
      "Microservices",
    ],
    bio: "Enforces strict controller-service structures using robust TypeScript modules and classes.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E0234E",
    icon: "devicon:nestjs",
  },
  {
    id: "django-lead",
    name: "Adrian AI (Django)",
    role: "Django ORM Specialist",
    type: "framework",
    category: "Backend",
    specialties: [
      "Migration consistency",
      "Admin extensions",
      "Query prefetching",
    ],
    bio: "Builds reliable relational models using Django's framework structures and schema migrations.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#092E20",
    icon: "devicon:django",
  },
  {
    id: "fastapi-lead",
    name: "Sebastián Ramírez AI",
    role: "FastAPI Async Developer",
    type: "framework",
    category: "Backend",
    specialties: ["Pydantic validation", "Async routers", "OAuth security"],
    bio: "Creates fast, self-documenting JSON APIs leveraging modern async python loops.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#059669",
    icon: "devicon:fastapi",
  },
  {
    id: "springboot-lead",
    name: "Rod Johnson AI (Spring)",
    role: "Spring Boot Enterprise Architect",
    type: "framework",
    category: "Backend",
    specialties: [
      "Dependency Injection",
      "Security Filters",
      "JPA optimization",
    ],
    bio: "Structures robust enterprise services using Spring injection, JPA layers, and secure filters.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#6DB33F",
    icon: "devicon:spring",
  },
  {
    id: "laravel-lead",
    name: "Taylor Otwell AI",
    role: "Laravel Artisan Architect",
    type: "framework",
    category: "Backend",
    specialties: ["Eloquent ORM", "Job Queues", "Blade Layouts"],
    bio: "Designs feature-rich backend apps utilizing database models, event handlers, and cache queues.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF2D20",
    icon: "devicon:laravel",
  },

  // DevOps, Cloud & Systems
  {
    id: "gcp-expert",
    name: "GCP Expert AI",
    role: "GCP Exclusive Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Cloud Run", "GKE / Kubernetes", "Vertex AI platforms"],
    bio: "Designs sovereign Google Cloud infrastructure in strict compliance with exclusive GCP runtime mandates.",
    status: "active",
    statusText: "Provisioning GKE pods...",
    accentColor: "#4285F4",
    icon: "material-icon-theme:gcp",
  },
  {
    id: "aws-expert",
    name: "AWS Solutions AI",
    role: "AWS Certified Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["EC2 & Lambda", "S3 & CloudFront", "DynamoDB & RDS"],
    bio: "Architects scalable Amazon Web Services infrastructures and serverless compute pipelines.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF9900",
    icon: "logos:aws",
  },
  {
    id: "azure-expert",
    name: "Azure Architect AI",
    role: "Azure Cloud Solutions Dev",
    type: "cloud",
    category: "Cloud",
    specialties: ["Azure Functions", "Cosmos DB", "App Service"],
    bio: "Designs enterprise-grade Microsoft Azure solutions, integrating .NET and containerized services.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0089D6",
    icon: "logos:microsoft-azure",
  },
  {
    id: "digitalocean-expert",
    name: "DigitalOcean Pro AI",
    role: "Droplet Infrastructure Dev",
    type: "cloud",
    category: "Cloud",
    specialties: ["Droplets", "App Platform", "Managed Databases"],
    bio: "Builds simple, scalable virtual private servers and Kubernetes clusters on DigitalOcean.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0080FF",
    icon: "simple-icons:digitalocean",
  },
  {
    id: "ibm-cloud-expert",
    name: "IBM Cloud Systems AI",
    role: "IBM Cloud Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Watson AI", "Db2", "Red Hat OpenShift"],
    bio: "Deploys hybrid cloud solutions utilizing IBM Cloud and enterprise-grade data services.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#052FAD",
    icon: "logos:ibm",
  },
  {
    id: "oracle-cloud-expert",
    name: "Oracle Cloud Specialist AI",
    role: "OCI Database Dev",
    type: "cloud",
    category: "Cloud",
    specialties: ["Autonomous DB", "Oracle APEX", "Bare Metal"],
    bio: "Maintains high-performance Oracle Cloud Infrastructure (OCI) and enterprise databases.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F80000",
    icon: "logos:oracle",
  },
  {
    id: "vercel-expert",
    name: "Vercel Deployment AI",
    role: "Vercel Edge Specialist",
    type: "cloud",
    category: "Cloud",
    specialties: ["Edge Functions", "Serverless Next.js", "Vercel KV"],
    bio: "Optimizes frontend deployments directly on Vercel's global edge network.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#000000",
    icon: "simple-icons:vercel",
  },
  {
    id: "netlify-expert",
    name: "Netlify Edge AI",
    role: "Netlify Platform Dev",
    type: "cloud",
    category: "Cloud",
    specialties: ["Netlify Functions", "Forms", "Identity"],
    bio: "Automates static site deployments and jamstack architectures using Netlify.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00C7B7",
    icon: "simple-icons:netlify",
  },
  {
    id: "heroku-expert",
    name: "Heroku Dyno AI",
    role: "Heroku App Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Web Dynos", "Heroku Postgres", "Buildpacks"],
    bio: "Maintains classic PaaS app deployments, optimizing dyno scaling and add-on resources.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#430098",
    icon: "logos:heroku",
  },
  {
    id: "render-expert",
    name: "Render Platform AI",
    role: "Render DevOps Specialist",
    type: "cloud",
    category: "Cloud",
    specialties: ["Web Services", "Private Services", "Background Workers"],
    bio: "Handles automated deployments of containers, static sites, and cron jobs on Render.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#000000",
    icon: "simple-icons:render",
  },
  {
    id: "k8s-expert",
    name: "Kelsey Hightower AI",
    role: "Kubernetes Coordinator",
    type: "framework",
    category: "DevOps",
    specialties: ["Helm Charts", "Ingress Controllers", "StatefulSets"],
    bio: "Orchestrates microservices clusters, writing clean YAML specifications and managing networking.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#326CE5",
    icon: "devicon:kubernetes",
  },
  {
    id: "docker-expert",
    name: "Solomon Hykes AI",
    role: "Containerization Specialist",
    type: "framework",
    category: "DevOps",
    specialties: ["Multi-stage builds", "Layer caching", "Secure runtimes"],
    bio: "Shrinks container layers and eliminates vulnerabilities from base Linux images.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#2496ED",
    icon: "simple-icons:docker",
  },

  {
    id: "sre-lead",
    name: "ChaosMonkey AI",
    role: "SRE Incident Lead",
    type: "role",
    category: "DevOps",
    specialties: ["Log Forensics", "Telemetry analysis", "Alert routes"],
    bio: "Scans runtime logs, tracking telemetry metrics, and tracing error stacks to their origin.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F44336",
    icon: "mdi:alert-decagram",
  },
  {
    id: "cicd-expert",
    name: "Drone CI AI",
    role: "Deployment Automation Dev",
    type: "framework",
    category: "DevOps",
    specialties: ["GitHub Actions", "Build scripts", "Rollback gates"],
    bio: "Connects repository commits directly to deployment systems using test verification steps.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#2196F3",
    icon: "mdi:rocket-launch",
  },
  {
    id: "platform-expert",
    name: "Dev Portal AI",
    role: "Internal Platform Architect",
    type: "role",
    category: "DevOps",
    specialties: [
      "Internal Developer Portals",
      "Scaffolding templates",
      "CLI configs",
    ],
    bio: "Standardizes project creation parameters to ensure structural compliance across domains.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#9C27B0",
    icon: "logos:google-marketing-platform",
  },
  {
    id: "linux-kernel-expert",
    name: "Linus Core AI",
    role: "Linux Kernel Tuner",
    type: "framework",
    category: "DevOps",
    specialties: [
      "Sysctl configs",
      "Memory virtualization",
      "BBR congestion control",
    ],
    bio: "Tweaks OS parameters for high-volume networks, maximizing CPU performance bounds.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#333333",
    icon: "devicon:linux",
  },
  {
    id: "win32-expert",
    name: "Win32 API AI",
    role: "Windows Systems Specialist",
    type: "framework",
    category: "DevOps",
    specialties: ["Registry configs", "COM objects", "Windows Services"],
    bio: "Debugs desktop bindings and builds background services for Windows client environments.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0078D7",
    icon: "devicon:windows8",
  },
  {
    id: "network-expert",
    name: "Radia Perlman AI",
    role: "BGP / Routing Specialist",
    type: "role",
    category: "DevOps",
    specialties: ["Routing algorithms", "DNSSEC", "Load balancer grids"],
    bio: "Optimizes cluster traffic, route paths, DNS resolutions, and load balancers.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E040FB",
    icon: "mdi:network",
  },

  // Security, Sovereignty & QA
  {
    id: "secops-expert",
    name: "AST Shield AI",
    role: "DevSecOps Security Inspector",
    type: "role",
    category: "Security",
    specialties: [
      "SAST / DAST scans",
      "Secrets detection",
      "SQL Injection blocks",
    ],
    bio: "Enforces strict security checks, scanning variables for SQL injections and secret leaks.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E65100",
    icon: "mdi:shield-lock",
  },
  {
    id: "pen-tester",
    name: "Ethical Hacker AI",
    role: "API Penetration Tester",
    type: "role",
    category: "Security",
    specialties: ["XSS exploits", "OAuth bypass checks", "Fuzz testing"],
    bio: "Attacks running server endpoints to identify auth loop holes and validation flaws.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#311B92",
    icon: "mdi:hacker",
  },
  {
    id: "compliance-expert",
    name: "Copyfree AI",
    role: "Sovereignty & License Auditor",
    type: "role",
    category: "Security",
    specialties: [
      "MIT/Apache 2.0 whitelist",
      "Copyleft exclusion",
      "Dependency audits",
    ],
    bio: "Blocks non-permissive library imports (GPL/AGPL), verifying legal parameters in package lists.",
    status: "active",
    statusText: "Auditing package-lock.json licenses...",
    accentColor: "#00C853",
    icon: "grommet-icons:compliance",
  },
  {
    id: "playwright-expert",
    name: "Playwright Core AI",
    role: "E2E Testing Architect",
    type: "framework",
    category: "QA",
    specialties: [
      "Playwright Runner",
      "Page Object Model",
      "Visual Assertions",
    ],
    bio: "Writes automated browser scripts simulating user clicks, form submissions, and visual states.",
    status: "testing",
    statusText: "Running Playwright test suite...",
    accentColor: "#2E7D32",
    icon: "logos:playwright",
  },
  {
    id: "tdd-expert",
    name: "MockMaster AI",
    role: "TDD Coverage Coordinator",
    type: "framework",
    category: "QA",
    specialties: [
      "Unit mock setups",
      "Vitest/Jest configs",
      "80%+ coverage metrics",
    ],
    bio: "Guides test-driven updates, building mocks, and verifying that test coverages meet gates.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF6F00",
    icon: "mdi:test-tube",
  },
  {
    id: "load-tester",
    name: "JMeter Pro AI",
    role: "Performance & Load Tester",
    type: "role",
    category: "QA",
    specialties: [
      "Locust frameworks",
      "Concurrences simulation",
      "p99 latency checks",
    ],
    bio: "Stresses server routes with simulated user traffic grids, mapping response latency boundaries.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#D50000",
    icon: "mdi:speedometer",
  },
  {
    id: "a11y-expert",
    name: "Inclusive Web AI",
    role: "Accessibility Auditor",
    type: "role",
    category: "QA",
    specialties: [
      "WCAG 2.2 Guidelines",
      "Screen-reader audits",
      "Focus control loops",
    ],
    bio: "Audits markup for WCAG color parameters, focus loop controls, and screen reader structures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#2979FF",
    icon: "streamline-ultimate:a11y-accessibility-disability",
  },

  // AI & Advanced Computing
  {
    id: "mle-expert",
    name: "Yann LeCun AI",
    role: "ML Pipeline Developer",
    type: "framework",
    category: "AI",
    specialties: ["PyTorch loops", "Feature engineering", "Evaluation sets"],
    bio: "Configures clean, reproducible machine learning data structures and model checkpoints.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF4081",
    icon: "devicon:pytorch",
  },
  {
    id: "mlops-expert",
    name: "Vertex AI Pipeline AI",
    role: "MLOps Platform Specialist",
    type: "framework",
    category: "AI",
    specialties: [
      "Model tracking registry",
      "Feature store maps",
      "Drift checkers",
    ],
    bio: "Deploys machine learning models to GCP runtimes, checking prediction logs for drift.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#7C4DFF",
    icon: "devicon:googlecloud",
  },
  {
    id: "rag-expert",
    name: "Pinecone Architect AI",
    role: "RAG & Vector DB Engineer",
    type: "framework",
    category: "AI",
    specialties: [
      "Cosine similarity",
      "Chunking strategies",
      "Metadata filtering",
    ],
    bio: "Prepares vector databases and semantic retrievers, maximizing search relevance bounds.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00E676",
    icon: "carbon:rag",
  },
  {
    id: "prompt-expert",
    name: "Instructions Pro AI",
    role: "LLM Prompt Architect",
    type: "framework",
    category: "AI",
    specialties: ["System rules design", "Dynamic framing", "Output parsers"],
    bio: "Writes system directives and structures markdown outputs for foundational models.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FFD600",
    icon: "tabler:prompt",
  },
  {
    id: "quantum-expert",
    name: "Qiskit AI",
    role: "Quantum Algorithm Dev",
    type: "framework",
    category: "AI",
    specialties: [
      "Qiskit Frameworks",
      "Error mitigating codes",
      "Circuit design",
    ],
    bio: "Simulates quantum circuits and maps problem math to quantum computing frameworks.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#673AB7",
    icon: "gcp:quantum-engine",
  },

  {
    id: "verilog-expert",
    name: "Verilog Verification Lead AI",
    role: "Verilog Systems Designer",
    type: "language",
    category: "Systems",
    specialties: ["SystemVerilog", "UVM Frameworks", "ASIC Syntheses"],
    bio: "Develops integrated circuit specs, simulating registers and memory controller structures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#007B8A",
    icon: "material-icon-theme:verilog",
  },
  {
    id: "pascal-expert",
    name: "Niklaus Wirth AI",
    role: "Pascal Compiler Educator",
    type: "language",
    category: "Systems",
    specialties: ["Structured Coding", "FreePascal", "TurboPascal"],
    bio: "Teaches clean compiler paradigms and updates classic educational applications.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E25822",
    icon: "material-icon-theme:pascal",
  },
  {
    id: "actionscript-expert",
    name: "Flash Animator AI",
    role: "ActionScript Flash Porter",
    type: "language",
    category: "Web",
    specialties: ["AS3 Core", "Flash / Adobe AIR", "Canvas migrations"],
    bio: "Maintains legacy interactive sites and ports historical Flash content to modern HTML5 elements.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF0000",
    icon: "material-icon-theme:actionscript",
  },
  {
    id: "coldfusion-expert",
    name: "ColdFusion Developer AI",
    role: "CFML Web Engineer",
    type: "language",
    category: "Web",
    specialties: ["CFML tags", "Lucee servers", "Legacy database APIs"],
    bio: "Handles old tags and upgrades CFML setups to modern containerized microservice architectures.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#ED8B00",
    icon: "material-icon-theme:coldfusion",
  },
  {
    id: "racket-expert",
    name: "Racket Language Synthesizer AI",
    role: "Racket Macro Specialist",
    type: "language",
    category: "Functional",
    specialties: ["Macro DSLs", "Scheme Dialects", "S-Expressions"],
    bio: "Synthesizes custom programming domains using Lisp macros and robust language compilers.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#9F1D35",
    icon: "simple-icons:racket",
  },
  {
    id: "smalltalk-expert",
    name: "Alan Kay AI",
    role: "Smalltalk Image Guardian",
    type: "language",
    category: "Functional",
    specialties: ["Squeak / Pharo", "Live Debugging", "Pure OOP"],
    bio: "Maintains object sandboxes and live runtime editing loops where code updates on the fly.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#1C88E3",
    icon: "arcticons:smalltalk",
  },
  {
    id: "apex-expert",
    name: "Marc Benioff AI (Apex)",
    role: "Apex Salesforce Developer",
    type: "language",
    category: "Enterprise",
    specialties: ["SOQL / SOSL queries", "Trigger architectures", "Governor limits"],
    bio: "Writes Salesforce database automation, managing cloud resources inside strict execution constraints.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00A1E0",
    icon: "devicon:apex",
  },
  // Functional Specialties / Technologies
  {
    id: "shopify-liquid-expert",
    name: "Shopify Storefront Dev AI",
    role: "Liquid Theme Engineer",
    type: "framework",
    category: "Frontend",
    specialties: ["Liquid syntax", "E-commerce APIs", "Section schemas"],
    bio: "Builds fast e-commerce storefront landing pages and custom themes for shopping portals.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#96BF48",
    icon: "logos:shopify",
  },
  {
    id: "wordpress-expert",
    name: "WordPress Theme Artisan AI",
    role: "WordPress PHP Developer",
    type: "framework",
    category: "Frontend",
    specialties: ["PHP hooks", "Gutenberg blocks", "Plugin security"],
    bio: "Maintains large content systems, writing custom PHP plugins and styling theme blocks.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#21759B",
    icon: "simple-icons:wordpress",
  },
  {
    id: "webgl-expert",
    name: "ThreeJS Visualizer AI",
    role: "WebGL 3D Developer",
    type: "framework",
    category: "Frontend",
    specialties: ["Three.js", "GLSL Shaders", "GPU performance"],
    bio: "Implements immersive 3D graphics in the browser, compiling custom vertex and fragment shaders.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF2B2B",
    icon: "simple-icons:webgl",
  },
  {
    id: "webrtc-expert",
    name: "Streaming Connections AI",
    role: "WebRTC Video Engineer",
    type: "framework",
    category: "Frontend",
    specialties: ["STUN/TURN servers", "Peer connection hooks", "Sdp protocols"],
    bio: "Maintains real-time video and audio stream channels directly between remote browser peers.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#1A8E2E",
    icon: "simple-icons:webrtc",
  },
  {
    id: "firebase-expert",
    name: "Firebase Cloud Developer AI",
    role: "Firebase Platform Specialist",
    type: "cloud",
    category: "Cloud",
    specialties: ["Firestore database", "Security Rules", "Cloud Functions"],
    bio: "Coordinates real-time data syncs, auth structures, and serverless background scripts.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FFCA28",
    icon: "simple-icons:firebase",
  },
  {
    id: "cloudflare-workers-expert",
    name: "Edge Worker Specialist AI",
    role: "Edge Worker Specialist AI",
    type: "cloud",
    category: "Cloud",
    specialties: ["WASM workers", "KV storage bindings", "Edge routing"],
    bio: "Optimizes latency by executing middleware and serverless functions directly on boundary edge servers.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F38020",
    icon: "logos:cloudflare-workers",
  },
  {
    id: "servicenow-expert",
    name: "ServiceNow Workflow Dev AI",
    role: "ServiceNow ITSM Specialist",
    type: "framework",
    category: "Backend",
    specialties: ["ITSM scripts", "Business Rules", "Client scripts"],
    bio: "Automates IT management scripts, designing record tables and business rules.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#293E40",
    icon: "logos:servicenow",
  },
  {
    id: "sap-expert",
    name: "SAP ABAP Consultant AI",
    role: "SAP Integration Specialist",
    type: "framework",
    category: "Backend",
    specialties: ["ABAP programming", "RFC interfaces", "Enterprise logs"],
    bio: "Coordinates massive resource planning databases, managing integrations with external systems.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0187FF",
    icon: "simple-icons:sap",
  },
  {
    id: "gis-expert",
    name: "GeoData Cartographer AI",
    role: "GIS Systems Developer",
    type: "framework",
    category: "Data",
    specialties: ["PostGIS spatial", "GeoJSON formats", "Mapping APIs"],
    bio: "Manipulates coordinate maps and designs fast database queries for spatial geometries.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#3E7B2B",
    icon: "simple-icons:qgis",
  },
  {
    id: "crypto-architect",
    name: "Secret Signing Keys AI",
    role: "Cryptography Architect",
    type: "framework",
    category: "Security",
    specialties: ["PKCS#11 HSM", "KMS envelope encrypt", "ECDSA signatures"],
    bio: "Designs HSM signing keys and envelope encryptions, securing repository artifacts during distribution.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FFC107",
    icon: "mdi:code-braces",
  },

  {
    id: "alibaba-cloud-expert",
    name: "Alibaba Cloud Specialist AI",
    role: "Alibaba Cloud Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["ECS & ACK", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Alibaba Cloud.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF6600",
    icon: "simple-icons:alibabacloud",
  },
  {
    id: "tencent-cloud-expert",
    name: "Tencent Cloud Specialist AI",
    role: "Tencent Cloud Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["CVM & TKE", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Tencent Cloud.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0052D9",
    icon: "simple-icons:tencentqq",
  },
  {
    id: "baidu-cloud-expert",
    name: "Baidu Cloud Specialist AI",
    role: "Baidu Cloud Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["BCC & BCE", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Baidu Cloud.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#2932E1",
    icon: "simple-icons:baidu",
  },
  {
    id: "huawei-cloud-expert",
    name: "Huawei Cloud Specialist AI",
    role: "Huawei Cloud Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["ECS & CCE", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Huawei Cloud.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#C8102E",
    icon: "simple-icons:huawei",
  },
  {
    id: "linode-cloud-expert",
    name: "Linode Specialist AI",
    role: "Linode Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["LKE & Compute", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Linode.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00E08F",
    icon: "logos:linode",
  },
  {
    id: "vultr-cloud-expert",
    name: "Vultr Specialist AI",
    role: "Vultr Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Cloud Compute", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Vultr.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#007BFC",
    icon: "simple-icons:vultr",
  },
  {
    id: "upcloud-expert",
    name: "UpCloud Specialist AI",
    role: "UpCloud Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["MaxIOPS", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on UpCloud.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#7B00FF",
    icon: "simple-icons:upcloud",
  },
  {
    id: "hetzner-cloud-expert",
    name: "Hetzner Specialist AI",
    role: "Hetzner Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Cloud Servers", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Hetzner.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#D50C2D",
    icon: "simple-icons:hetzner",
  },
  {
    id: "scaleway-expert",
    name: "Scaleway Specialist AI",
    role: "Scaleway Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Dedibox & Elements", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Scaleway.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4F0599",
    icon: "simple-icons:scaleway",
  },
  {
    id: "ovhcloud-expert",
    name: "OVHcloud Specialist AI",
    role: "OVHcloud Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Public Cloud", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on OVHcloud.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#005096",
    icon: "cbi:ovhcloud",
  },
  {
    id: "fly-io-expert",
    name: "Fly.io Specialist AI",
    role: "Fly.io Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Global Edge", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Fly.io.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#24185B",
    icon: "simple-icons:flydotio",
  },
  {
    id: "railway-expert",
    name: "Railway Specialist AI",
    role: "Railway Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Nixpacks", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Railway.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0B0D0E",
    icon: "simple-icons:railway",
  },
  {
    id: "koyeb-expert",
    name: "Koyeb Specialist AI",
    role: "Koyeb Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Serverless", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Koyeb.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#111111",
    icon: "simple-icons:koyeb",
  },
  
  {
    id: "zeabur-expert",
    name: "Zeabur Specialist AI",
    role: "Zeabur Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Serverless PaaS", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Zeabur.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#512BD4",
    icon: "material-icon-theme:zeabur",
  },
  {
    id: "supabase-expert",
    name: "Supabase Specialist AI",
    role: "Supabase Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Postgres & Auth", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Supabase.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#3ECF8E",
    icon: "simple-icons:supabase",
  },
  {
    id: "snowflake-expert",
    name: "Snowflake Specialist AI",
    role: "Snowflake Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Data Cloud", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Snowflake.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#29B5E8",
    icon: "simple-icons:snowflake",
  },
  {
    id: "databricks-expert",
    name: "Databricks Specialist AI",
    role: "Databricks Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Lakehouse", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Databricks.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF3621",
    icon: "simple-icons:databricks",
  },
  {
    id: "planetscale-expert",
    name: "PlanetScale Specialist AI",
    role: "PlanetScale Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["MySQL Edge", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on PlanetScale.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#000000",
    icon: "simple-icons:planetscale",
  },
  {
    id: "neon-db-expert",
    name: "Neon Specialist AI",
    role: "Neon Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Serverless Postgres", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Neon.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00E599",
    icon: "simple-icons:neon",
  },
  
  {
    id: "mongodb-atlas-expert",
    name: "MongoDB Atlas Specialist AI",
    role: "MongoDB Atlas Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["NoSQL DBaaS", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on MongoDB Atlas.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#47A248",
    icon: "devicon:mongodb",
  },
  {
    id: "confluent-expert",
    name: "Confluent Specialist AI",
    role: "Confluent Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Kafka Cloud", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Confluent.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#000000",
    icon: "mdi:apache-kafka",
  },
  {
    id: "fastly-expert",
    name: "Fastly Specialist AI",
    role: "Fastly Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Edge Cloud", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Fastly.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF282D",
    icon: "simple-icons:fastly",
  },
  {
    id: "akamai-expert",
    name: "Akamai Specialist AI",
    role: "Akamai Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Edge & CDN", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Akamai.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0096D6",
    icon: "simple-icons:akamai",
  },
  {
    id: "edgio-expert",
    name: "Edgio Specialist AI",
    role: "Edgio Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["AppOps", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Edgio.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF3366",
    icon: "logos:edgio",
  },
  {
    id: "rackspace-expert",
    name: "Rackspace Specialist AI",
    role: "Rackspace Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Managed Cloud", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Rackspace.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#C61D23",
    icon: "logos:rackspace",
  },
  {
    id: "lumen-cloud-expert",
    name: "Lumen Specialist AI",
    role: "Lumen Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Edge Computing", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Lumen.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0055DA",
    icon: "simple-icons:lumen",
  },
  {
    id: "equinix-expert",
    name: "Equinix Specialist AI",
    role: "Equinix Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Metal & Fabric", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Equinix.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#ED1C24",
    icon: "simple-icons:equinixmetal",
  },
  
  {
    id: "fujitsu-cloud-expert",
    name: "Fujitsu Specialist AI",
    role: "Fujitsu Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["K5 Cloud", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Fujitsu.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF0000",
    icon: "simple-icons:fujitsu",
  },
  {
    id: "salesforce-cloud-expert",
    name: "Salesforce Specialist AI",
    role: "Salesforce Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["CRM PaaS", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Salesforce.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00A1E0",
    icon: "logos:salesforce",
  },
  {
    id: "workday-expert",
    name: "Workday Specialist AI",
    role: "Workday Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["HCM Cloud", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Workday.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#005CB9",
    icon: "arcticons:workday",
  },
  {
    id: "sap-cloud-expert",
    name: "SAP Cloud Specialist AI",
    role: "SAP Cloud Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["BTP", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on SAP Cloud.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#008FD3",
    icon: "simple-icons:sap",
  },
  {
    id: "netsuite-expert",
    name: "Oracle NetSuite Specialist AI",
    role: "Oracle NetSuite Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["ERP Cloud", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Oracle NetSuite.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#000000",
    icon: "cib:oracle-netsuite",
  },
  {
    id: "twilio-expert",
    name: "Twilio Specialist AI",
    role: "Twilio Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Communications", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Twilio.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F22F46",
    icon: "logos:twilio",
  },
  
  
  {
    id: "vonage-expert",
    name: "Vonage Specialist AI",
    role: "Vonage Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Comms API", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Vonage.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#000000",
    icon: "simple-icons:vonage",
  },
  {
    id: "stripe-cloud-expert",
    name: "Stripe Specialist AI",
    role: "Stripe Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Financial Cloud", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Stripe.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#635BFF",
    icon: "simple-icons:stripe",
  },
  
  
  {
    id: "square-cloud-expert",
    name: "Square Specialist AI",
    role: "Square Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Commerce", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Square.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#000000",
    icon: "simple-icons:square",
  },
  {
    id: "backblaze-expert",
    name: "Backblaze Specialist AI",
    role: "Backblaze Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["B2 Storage", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Backblaze.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E01522",
    icon: "simple-icons:backblaze",
  },
  {
    id: "wasabi-expert",
    name: "Wasabi Specialist AI",
    role: "Wasabi Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Hot Cloud Storage", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Wasabi.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00D600",
    icon: "simple-icons:wasabi",
  },
  {
    id: "storj-expert",
    name: "Storj Specialist AI",
    role: "Storj Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Decentralized", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Storj.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#2683FF",
    icon: "selfhst:storj",
  },
  
  
  
  {
    id: "hostinger-expert",
    name: "Hostinger Specialist AI",
    role: "Hostinger Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Web Hosting", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Hostinger.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#673DE6",
    icon: "simple-icons:hostinger",
  },
  {
    id: "godaddy-expert",
    name: "GoDaddy Specialist AI",
    role: "GoDaddy Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Domains & Hosting", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on GoDaddy.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#1BDBDB",
    icon: "simple-icons:godaddy",
  },
  
  {
    id: "hostgator-expert",
    name: "HostGator Specialist AI",
    role: "HostGator Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Shared Hosting", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on HostGator.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F7B819",
    icon: "logos:hostgator",
  },
  
  {
    id: "dreamhost-expert",
    name: "DreamHost Specialist AI",
    role: "DreamHost Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Compute & Storage", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on DreamHost.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#003A5D",
    icon: "logos:dreamhost",
  },
  
  
  
  
  {
    id: "ionos-expert",
    name: "IONOS Specialist AI",
    role: "IONOS Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Compute Engine", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on IONOS.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00305E",
    icon: "simple-icons:ionos",
  },
  {
    id: "kinsta-expert",
    name: "Kinsta Specialist AI",
    role: "Kinsta Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Premium WP", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Kinsta.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#5333ED",
    icon: "simple-icons:kinsta",
  },
  {
    id: "wpengine-expert",
    name: "WP Engine Specialist AI",
    role: "WP Engine Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["WP Cloud", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on WP Engine.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00E0D1",
    icon: "simple-icons:wpengine",
  },
  {
    id: "cloudinary-expert",
    name: "Cloudinary Specialist AI",
    role: "Cloudinary Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Media Cloud", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Cloudinary.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F4A261",
    icon: "simple-icons:cloudinary",
  },
  
  {
    id: "mux-expert",
    name: "Mux Specialist AI",
    role: "Mux Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Video Infrastructure", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Mux.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF0000",
    icon: "simple-icons:tmux",
  },
  {
    id: "clever-cloud-expert",
    name: "Clever Cloud Specialist AI",
    role: "Clever Cloud Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["IT Automation", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Clever Cloud.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#192A42",
    icon: "simple-icons:clevercloud",
  },
  {
    id: "deno-deploy-expert",
    name: "Deno Deploy Specialist AI",
    role: "Deno Deploy Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["V8 Edge", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Deno Deploy.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#000000",
    icon: "logos:deno",
  },
  {
    id: "appwrite-expert",
    name: "Appwrite Specialist AI",
    role: "Appwrite Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["BaaS", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Appwrite.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F02E65",
    icon: "simple-icons:appwrite",
  },
  {
    id: "nhost-expert",
    name: "Nhost Specialist AI",
    role: "Nhost Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["GraphQL BaaS", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Nhost.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0052CC",
    icon: "simple-icons:nhost",
  },
  {
    id: "hasura-cloud-expert",
    name: "Hasura Specialist AI",
    role: "Hasura Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Data API", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Hasura.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#1EB4D4",
    icon: "simple-icons:hasura",
  },
];
