version: '3.8'

services:
  gitness:
    image: harness/gitness
    container_name: gitness
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001" # Git SSH
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitness_data:/data
    environment:
      - "GITNESS_DEBUG=true"
    networks:
      - inso_code_network

volumes:
  gitness_data:

networks:
  inso_code_network:
    external: true
