apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: inso-code
build:
  artifacts:
    - image: inso-backend
      docker:
        dockerfile: Inso.Code.Backend/Dockerfile
  googleCloudBuild:
    projectId: '{{.GCP_PROJECT_ID}}'
    machineType: E2_HIGHCPU_8
    timeout: 1200s
profiles:
  - name: dev
    deploy:
      cloudrun:
        projectid: '{{.GCP_PROJECT_ID}}'
        region: us-central1
  - name: staging
    deploy:
      cloudrun:
        projectid: '{{.GCP_PROJECT_ID}}'
        region: us-central1
  - name: production
    deploy:
      cloudrun:
        projectid: '{{.GCP_PROJECT_ID}}'
        region: us-central1
