export type ExtensionCategory =
  | "Cloud"
  | "Dev Tools"
  | "Security"
  | "Databases"
  | "AI/ML"
  | "Productivity"
  | "Integrations"
  | "Frameworks"
  | "Observability"
  | "Media"
  | "Other";

export interface GeminiExtension {
  name: string;
  description: string;
  githubUrl: string;
  category: ExtensionCategory;
  spotlight?: boolean;
  official?: boolean;
}

export const GEMINI_EXTENSIONS: GeminiExtension[] = [
  // ── Spotlight / Official Google ─────────────────────────────────────
  {
    name: "gemini-docs-ext",
    description: "Up-to-date Gemini API docs and MCP for any prompt.",
    githubUrl: "https://github.com/markmcd/gemini-docs-ext",
    category: "Dev Tools",
    spotlight: true,
    official: true,
  },
  {
    name: "context7",
    description: "Up-to-date code docs for any prompt.",
    githubUrl: "https://github.com/upstash/context7",
    category: "Dev Tools",
    spotlight: true,
  },
  {
    name: "dynatrace-mcp-server",
    description: "MCP server for Dynatrace Observability.",
    githubUrl: "https://github.com/dynatrace-oss/dynatrace-mcp",
    category: "Observability",
    spotlight: true,
  },
  {
    name: "github",
    description: "GitHub's official MCP Server.",
    githubUrl: "https://github.com/github/github-mcp-server",
    category: "Integrations",
    spotlight: true,
    official: true,
  },
  {
    name: "chrome-devtools-mcp",
    description: "Chrome DevTools for coding agents.",
    githubUrl: "https://github.com/ChromeDevTools/chrome-devtools-mcp",
    category: "Dev Tools",
    spotlight: true,
    official: true,
  },
  {
    name: "mcp-toolbox-for-databases",
    description: "Open-source MCP server for 30+ datasources.",
    githubUrl: "https://github.com/googleapis/genai-toolbox",
    category: "Databases",
    spotlight: true,
    official: true,
  },
  {
    name: "conductor",
    description: "Specify, plan, and implement software features.",
    githubUrl: "https://github.com/gemini-cli-extensions/conductor",
    category: "Dev Tools",
    spotlight: true,
    official: true,
  },
  {
    name: "grafana",
    description: "MCP server for Grafana.",
    githubUrl: "https://github.com/grafana/mcp-grafana",
    category: "Observability",
    spotlight: true,
  },

  {
    name: "mcp-server-kubernetes",
    description: "MCP Server for Kubernetes management.",
    githubUrl: "https://github.com/Flux159/mcp-server-kubernetes",
    category: "Cloud",
    spotlight: true,
  },
  {
    name: "stripe",
    description: "AI-powered Stripe integration for payments.",
    githubUrl: "https://github.com/stripe/ai",
    category: "Integrations",
    spotlight: true,
  },
  {
    name: "terraform",
    description: "MCP server for Terraform IaC development.",
    githubUrl: "https://github.com/hashicorp/terraform-mcp-server",
    category: "Cloud",
    spotlight: true,
  },

  {
    name: "mcp-neo4j",
    description: "Neo4j Labs MCP servers.",
    githubUrl: "https://github.com/neo4j-contrib/mcp-neo4j",
    category: "Databases",
    spotlight: true,
  },
  {
    name: "code-review",
    description: "Google's code review extension for Gemini CLI.",
    githubUrl: "https://github.com/gemini-cli-extensions/code-review",
    category: "Dev Tools",
    spotlight: true,
    official: true,
  },
  {
    name: "gemini-cli-security",
    description: "Google's security extension — finds vulnerabilities in code.",
    githubUrl: "https://github.com/gemini-cli-extensions/security",
    category: "Security",
    spotlight: true,
    official: true,
  },
  {
    name: "google-workspace",
    description: "Access Google Workspace from Gemini CLI.",
    githubUrl: "https://github.com/gemini-cli-extensions/workspace",
    category: "Integrations",
    spotlight: true,
    official: true,
  },
  {
    name: "gcloud",
    description: "Enable AI agents to interact with Google Cloud.",
    githubUrl: "https://github.com/gemini-cli-extensions/gcloud",
    category: "Cloud",
    spotlight: true,
    official: true,
  },
  {
    name: "firebase",
    description: "Build and run modern apps with Firebase.",
    githubUrl: "https://github.com/gemini-cli-extensions/firebase",
    category: "Cloud",
    spotlight: true,
    official: true,
  },
  {
    name: "Figma",
    description: "Generate code from Figma frames, extract design context.",
    githubUrl: "https://github.com/figma/figma-gemini-cli-extension",
    category: "Dev Tools",
    spotlight: true,
  },

  // ── Cloud / GCP ──────────────────────────────────────────────────────
  {
    name: "GeminiCloudAssist",
    description: "MCP Server for Gemini Cloud Assist on GCP.",
    githubUrl: "https://github.com/GoogleCloudPlatform/gemini-cloud-assist-mcp",
    category: "Cloud",
    official: true,
  },
  {
    name: "gke-mcp",
    description: "Gemini CLI extension for Google Kubernetes Engine.",
    githubUrl: "https://github.com/GoogleCloudPlatform/gke-mcp",
    category: "Cloud",
    official: true,
  },
  {
    name: "cloud-run",
    description: "MCP server to deploy apps to Cloud Run.",
    githubUrl: "https://github.com/GoogleCloudPlatform/cloud-run-mcp",
    category: "Cloud",
    official: true,
  },
  {
    name: "bigquery-data-analytics",
    description: "Connect, query, and generate insights for BigQuery.",
    githubUrl:
      "https://github.com/gemini-cli-extensions/bigquery-data-analytics",
    category: "Cloud",
    official: true,
  },
  {
    name: "bigquery-conversational-analytics",
    description: "Conversational analytics for BigQuery.",
    githubUrl:
      "https://github.com/gemini-cli-extensions/bigquery-conversational-analytics",
    category: "Cloud",
    official: true,
  },
  {
    name: "spanner",
    description: "Interact with Spanner data using natural language.",
    githubUrl: "https://github.com/gemini-cli-extensions/spanner",
    category: "Cloud",
    official: true,
  },
  {
    name: "dataplex",
    description: "Connect to Dataplex Universal Catalog.",
    githubUrl: "https://github.com/gemini-cli-extensions/dataplex",
    category: "Cloud",
    official: true,
  },
  {
    name: "cloud-sql-postgresql",
    description: "Create and interact with Cloud SQL for PostgreSQL.",
    githubUrl: "https://github.com/gemini-cli-extensions/cloud-sql-postgresql",
    category: "Cloud",
    official: true,
  },
  {
    name: "cloud-sql-mysql",
    description: "Connect and interact with Cloud SQL for MySQL.",
    githubUrl: "https://github.com/gemini-cli-extensions/cloud-sql-mysql",
    category: "Cloud",
    official: true,
  },
  {
    name: "cloud-sql-sqlserver",
    description: "Connect to Cloud SQL for SQL Server.",
    githubUrl: "https://github.com/gemini-cli-extensions/cloud-sql-sqlserver",
    category: "Cloud",
    official: true,
  },
  {
    name: "cloud-sql-postgresql-observability",
    description: "Monitor Cloud SQL PostgreSQL performance.",
    githubUrl:
      "https://github.com/gemini-cli-extensions/cloud-sql-postgresql-observability",
    category: "Cloud",
    official: true,
  },
  {
    name: "cloud-sql-mysql-observability",
    description: "Monitor Cloud SQL MySQL performance.",
    githubUrl:
      "https://github.com/gemini-cli-extensions/cloud-sql-mysql-observability",
    category: "Cloud",
    official: true,
  },
  {
    name: "cloud-sql-sqlserver-observability",
    description: "Monitor Cloud SQL SQL Server performance.",
    githubUrl:
      "https://github.com/gemini-cli-extensions/cloud-sql-sqlserver-observability",
    category: "Cloud",
    official: true,
  },
  {
    name: "alloydb",
    description: "Create and interact with AlloyDB for PostgreSQL.",
    githubUrl: "https://github.com/gemini-cli-extensions/alloydb",
    category: "Cloud",
    official: true,
  },
  {
    name: "alloydb-observability",
    description: "Monitor AlloyDB performance and health.",
    githubUrl: "https://github.com/gemini-cli-extensions/alloydb-observability",
    category: "Cloud",
    official: true,
  },
  {
    name: "looker",
    description: "Connect to Looker for data analytics.",
    githubUrl: "https://github.com/gemini-cli-extensions/looker",
    category: "Cloud",
    official: true,
  },
  {
    name: "looker-conversational-analytics",
    description: "Conversational analytics for Looker.",
    githubUrl:
      "https://github.com/gemini-cli-extensions/looker-conversational-analytics",
    category: "Cloud",
    official: true,
  },
  {
    name: "vertex",
    description: "Manage prompts in Vertex AI.",
    githubUrl: "https://github.com/gemini-cli-extensions/vertex",
    category: "Cloud",
    official: true,
  },
  {
    name: "devops",
    description: "AI-assisted CI/CD with Cloud Run and Cloud Storage.",
    githubUrl: "https://github.com/gemini-cli-extensions/devops",
    category: "Cloud",
    official: true,
  },
  {
    name: "observability",
    description: "MCP-compatible agents with Google Cloud observability.",
    githubUrl: "https://github.com/gemini-cli-extensions/observability",
    category: "Observability",
    official: true,
  },
  {
    name: "datacommons",
    description: "Query Data Commons public datasets using natural language.",
    githubUrl: "https://github.com/gemini-cli-extensions/datacommons",
    category: "Cloud",
    official: true,
  },
  {
    name: "google-adk-agent-extension",
    description: "Gemini CLI extension for Google ADK AI Agent Application.",
    githubUrl: "https://github.com/simonliu-ai-product/adk-agent-extension",
    category: "Cloud",
  },
  {
    name: "adk-docs-ext",
    description: "Up-to-date ADK documentation for your AI agent.",
    githubUrl: "https://github.com/derailed-dash/adk-docs-ext",
    category: "Cloud",
  },
  {
    name: "adk-expert",
    description: "Up-to-date ADK knowledge for your AI agent.",
    githubUrl: "https://github.com/danistrebel/adk-expert-skill",
    category: "Cloud",
  },
  {
    name: "gcp-release-notes",
    description: "GCP release notes extension for Gemini CLI.",
    githubUrl: "https://github.com/danistrebel/gcp-release-notes",
    category: "Cloud",
  },
  {
    name: "google-ads-api-developer-assistant",
    description: "Google Ads API developer assistant.",
    githubUrl:
      "https://github.com/googleads/google-ads-api-developer-assistant",
    category: "Cloud",
    official: true,
  },
  {
    name: "google-maps-platform",
    description: "Google Maps Platform documentation and code samples.",
    githubUrl: "https://github.com/googlemaps/platform-ai",
    category: "Cloud",
    official: true,
  },
  {
    name: "google-workspace-developer-tools",
    description: "Google Workspace Developer Tools.",
    githubUrl: "https://github.com/googleworkspace/developer-tools",
    category: "Integrations",
    official: true,
  },
  {
    name: "google-workspace-inbox",
    description: "Tools for managing your Google Workspace Inbox.",
    githubUrl: "https://github.com/jduncan-rva/google-workspace-inbox",
    category: "Integrations",
  },
  {
    name: "google-secops",
    description:
      "Security Operations skills for Triage, Investigation, and Hunting.",
    githubUrl: "https://github.com/dandye/secops-gemini-extension",
    category: "Security",
  },
  {
    name: "google-automation-mcp",
    description:
      "Headless Google Workspace automation — Apps Script, Gmail, Drive.",
    githubUrl: "https://github.com/sam-ent/google-automation-mcp",
    category: "Integrations",
  },
  {
    name: "firebase-rules",
    description: "Firebase security rules snippets.",
    githubUrl: "https://github.com/firebase/snippets-rules",
    category: "Cloud",
    official: true,
  },
  {
    name: "firestore-native",
    description: "Connect and interact with Firestore databases.",
    githubUrl: "https://github.com/gemini-cli-extensions/firestore-native",
    category: "Cloud",
    official: true,
  },
  {
    name: "notebooklm-enterprise",
    description: "Manage Google Cloud NotebookLM Enterprise notebooks.",
    githubUrl: "https://github.com/dandye/notebooklm_sdk",
    category: "Cloud",
  },
  {
    name: "cloudflare-mcp",
    description: "Gemini CLI extension for Cloudflare MCP servers.",
    githubUrl: "https://github.com/ZhanZiyuan/cloudflare-mcp",
    category: "Cloud",
  },
  {
    name: "vercel-mcp",
    description: "Gemini CLI extension for Vercel's official MCP server.",
    githubUrl: "https://github.com/ZhanZiyuan/vercel-mcp",
    category: "Cloud",
  },
  {
    name: "genkit",
    description: "Build full-stack AI-powered apps using Genkit.",
    githubUrl: "https://github.com/gemini-cli-extensions/genkit",
    category: "Cloud",
    official: true,
  },
  {
    name: "async-remote-agent-extension",
    description: "Managing remote agent sandboxes on GKE.",
    githubUrl: "https://github.com/derrickchwong/remote-agent-extension",
    category: "Cloud",
  },

  // ── Dev Tools ─────────────────────────────────────────────────────────
  {
    name: "flutter",
    description: "Flutter and Dart-related commands and context.",
    githubUrl: "https://github.com/gemini-cli-extensions/flutter",
    category: "Frameworks",
    official: true,
  },
  {
    name: "angular",
    description: "Angular extension for Gemini CLI.",
    githubUrl: "https://github.com/gemini-cli-extensions/angular",
    category: "Frameworks",
    official: true,
  },
  {
    name: "postgres",
    description: "Connect and interact with a PostgreSQL database.",
    githubUrl: "https://github.com/gemini-cli-extensions/postgres",
    category: "Databases",
    official: true,
  },
  {
    name: "mysql",
    description: "Connect and interact with a MySQL database.",
    githubUrl: "https://github.com/gemini-cli-extensions/mysql",
    category: "Databases",
    official: true,
  },
  {
    name: "sql-server",
    description: "Connect to SQL Server.",
    githubUrl: "https://github.com/gemini-cli-extensions/sql-server",
    category: "Databases",
    official: true,
  },
  {
    name: "oracledb",
    description: "Connect to Oracle Databases within Gemini CLI.",
    githubUrl: "https://github.com/gemini-cli-extensions/oracledb",
    category: "Databases",
    official: true,
  },
  {
    name: "gemini-cli-git",
    description: "Convenient Git commands for Gemini CLI.",
    githubUrl: "https://github.com/ox01024/gemini-cli-git",
    category: "Dev Tools",
  },
  {
    name: "git-tools",
    description: "AI-generated commit messages and PR drafts.",
    githubUrl: "https://github.com/paufortiana/geminicli-git-tools-extension",
    category: "Dev Tools",
  },
  {
    name: "git-conventional-commits",
    description: "Enforce conventional commits and feature branching.",
    githubUrl: "https://github.com/jorelcb/git-conventional-commits",
    category: "Dev Tools",
  },
  {
    name: "geminicli-gitcommit",
    description: "Automate Git commit messages with AI.",
    githubUrl: "https://github.com/samucodesh/geminicli-gitcommit",
    category: "Dev Tools",
  },
  {
    name: "git-versioning",
    description: "Git release manager with Semantic Versioning.",
    githubUrl: "https://github.com/jorelcb/git-versioning",
    category: "Dev Tools",
  },
  {
    name: "git-prompts-helpers",
    description: "Generate prompts based on Git repository content.",
    githubUrl: "https://github.com/ceshine/git-prompts-mcp-server",
    category: "Dev Tools",
  },
  {
    name: "git-expert",
    description: "GitHub Workflow Specialist for commits, PRs, issues.",
    githubUrl: "https://github.com/ankitchiplunkar/git-expert",
    category: "Dev Tools",
  },
  {
    name: "gitops",
    description: "GitOps extension for Gemini CLI.",
    githubUrl: "https://github.com/mikebz/gitops-extension",
    category: "Dev Tools",
  },
  {
    name: "gitlab",
    description: "Connects Gemini CLI to GitLab MCP server.",
    githubUrl: "https://github.com/GitLab-Ecosystem/Gemini-CLI-Extensions",
    category: "Integrations",
  },
  {
    name: "github-issue",
    description: "GitHub Issues AI Agent.",
    githubUrl: "https://github.com/enola-dev/github-issue-agent",
    category: "Dev Tools",
  },
  {
    name: "jira-autofix",
    description: "Automates resolving Jira issues to PRs.",
    githubUrl: "https://github.com/weitzer-org/jira-autofix-extension",
    category: "Integrations",
  },
  {
    name: "spec-flow",
    description: "Spec-Driven Development workflow toolkit.",
    githubUrl: "https://github.com/marcusgoll/Spec-Flow",
    category: "Dev Tools",
  },
  {
    name: "dev-flow",
    description: "Structured development workflow for feature dev.",
    githubUrl: "https://github.com/shrwnsan/clix-dev-flow",
    category: "Dev Tools",
  },
  {
    name: "blueprint",
    description: "Guide software from concept to implementation.",
    githubUrl: "https://github.com/gplasky/gemini-cli-blueprint-extension",
    category: "Dev Tools",
  },
  {
    name: "plan",
    description: "Custom commands for plan, refine, implement.",
    githubUrl: "https://github.com/jjdelorme/plan-commands",
    category: "Dev Tools",
  },
  {
    name: "gemini-plan-commands",
    description: "Create, refine, implement and deploy a plan.",
    githubUrl: "https://github.com/ddobrin/gemini-plan-commands",
    category: "Dev Tools",
  },
  {
    name: "gemini-sdlc",
    description:
      "30+ tools for full software development lifecycle automation.",
    githubUrl: "https://github.com/BaboonLabs/gemini-sdlc",
    category: "Dev Tools",
  },
  {
    name: "ai-driven-engineering",
    description: "AI-Driven Engineering: issues, tasks, implementation, PRs.",
    githubUrl: "https://github.com/SaschaHeyer/ai-driven-engineering",
    category: "Dev Tools",
  },
  {
    name: "gemini-review",
    description: "Code review with sub-agent delegation, P0–P3 severity.",
    githubUrl: "https://github.com/ShravanSunder/gemini-review-agents",
    category: "Dev Tools",
  },
  {
    name: "refactor",
    description: "Senior Software Architect for intelligent code refactoring.",
    githubUrl: "https://github.com/ankitchiplunkar/refactor",
    category: "Dev Tools",
  },
  {
    name: "web-accessibility",
    description: "Find and fix web accessibility violations.",
    githubUrl: "https://github.com/gemini-cli-extensions/web-accessibility",
    category: "Dev Tools",
    official: true,
  },
  {
    name: "outline-driven-development",
    description: "AST analysis and modern CLI tools with context engineering.",
    githubUrl: "https://github.com/OutlineDriven/odin-gemini-cli-extension",
    category: "Dev Tools",
  },
  {
    name: "gemini-safety-net",
    description:
      "Catches destructive git and filesystem commands before execution.",
    githubUrl: "https://github.com/kenryu42/gemini-safety-net",
    category: "Security",
  },
  {
    name: "extensions-creator",
    description: "Scaffold new Gemini CLI extensions with best practices.",
    githubUrl: "https://github.com/thoreinstein/extension-creator",
    category: "Dev Tools",
  },
  {
    name: "gemini-cli-skill-creator",
    description: "Extension for creating effective skills.",
    githubUrl: "https://github.com/involvex/gemini-cli-skill-creator",
    category: "Dev Tools",
  },
  {
    name: "skill-porter",
    description: "Converts Claude Code skills to Gemini CLI extensions.",
    githubUrl: "https://github.com/jduncan-rva/skill-porter",
    category: "Dev Tools",
  },
  {
    name: "repo-onboarding",
    description: "Generate a high-quality ONBOARDING.md for any repo.",
    githubUrl: "https://github.com/rogermt/mcp-repo-onboarding",
    category: "Dev Tools",
  },
  {
    name: "gemini-deep-research",
    description: "A deep research extension for Gemini CLI.",
    githubUrl: "https://github.com/allenhutchison/gemini-cli-deep-research",
    category: "Dev Tools",
  },
  {
    name: "exa-mcp-server",
    description: "Web search, crawling and technical code docs.",
    githubUrl: "https://github.com/exa-labs/exa-mcp-server",
    category: "Dev Tools",
  },
  {
    name: "gemini-cli-prompt-library",
    description: "Curated library of prompts for development tasks.",
    githubUrl: "https://github.com/harish-garg/gemini-cli-prompt-library",
    category: "Dev Tools",
  },
  {
    name: "prompt-engineering-extension",
    description: "Prompt engineering skills for Gemini CLI.",
    githubUrl: "https://github.com/Jsebayhi/prompt-engineering-extension",
    category: "Dev Tools",
  },
  {
    name: "gemini-mentor",
    description: "Engineering mentor with a focus on TDD.",
    githubUrl: "https://github.com/JayadityaGit/gemini-mentor",
    category: "Dev Tools",
  },
  {
    name: "open-aware",
    description: "Deep Code Research Agent — your Agentic Principal Engineer.",
    githubUrl: "https://github.com/qodo-ai/open-aware",
    category: "Dev Tools",
  },
  {
    name: "maestro",
    description:
      "Multi-agent dev platform — 12 specialists, 4-phase orchestration.",
    githubUrl: "https://github.com/josstei/maestro-gemini",
    category: "Dev Tools",
  },
  {
    name: "antigravity-swarm",
    description: "Deploys autonomous sub-agents to perform tasks.",
    githubUrl: "https://github.com/wjgoarxiv/antigravity-swarm",
    category: "Dev Tools",
  },
  {
    name: "gemini-llm-council",
    description: "Work with multiple LLMs at once.",
    githubUrl: "https://github.com/theerud/gemini-llm-council",
    category: "AI/ML",
  },
  {
    name: "system-agents",
    description:
      "Curated system prompt variants: architect, code-generator, and more.",
    githubUrl: "https://github.com/jduncan-rva/gemini-system-agents",
    category: "Dev Tools",
  },
  {
    name: "blender-mcp",
    description: "Enable Blender via MCP for Gemini CLI.",
    githubUrl: "https://github.com/xprilion/gemini-cli-blender-extension",
    category: "Media",
  },
  {
    name: "gemini-media-generation",
    description: "Media generation extension for Gemini CLI.",
    githubUrl: "https://github.com/rubans/gemini-media-generation",
    category: "Media",
  },
  {
    name: "mcp-tts",
    description: "Text-to-Speech skills for automatic announcements.",
    githubUrl: "https://github.com/blacktop/mcp-tts",
    category: "Media",
  },
  {
    name: "Stitch",
    description: "Generate UI from Text and Image with Stitch.",
    githubUrl: "https://github.com/gemini-cli-extensions/stitch",
    category: "Frameworks",
    official: true,
  },
  {
    name: "godoctor",
    description: "AI-powered Go development assistant.",
    githubUrl: "https://github.com/danicat/godoctor",
    category: "Frameworks",
  },
  {
    name: "gemini-cli-gopls",
    description: "Integrates official MCP of Go language server (gopls).",
    githubUrl: "https://github.com/Menghuan1918/gemini-cli-gopls",
    category: "Frameworks",
  },
  {
    name: "rust-agentic-skills",
    description: "Rust Guardian agent that enforces memory safety.",
    githubUrl: "https://github.com/udapy/rust-agentic-skills",
    category: "Frameworks",
  },
  {
    name: "java-dev-assist-extension",
    description: "Java 17+, Quarkus, and Spring Boot dev assistant.",
    githubUrl: "https://github.com/grzegorz-golowicz/java-dev-assist-extension",
    category: "Frameworks",
  },
  {
    name: "angular",
    description: "Angular extension for Gemini CLI.",
    githubUrl: "https://github.com/gemini-cli-extensions/angular",
    category: "Frameworks",
    official: true,
  },
  {
    name: "frontend-design",
    description: "Expert Frontend Designer for UI/UX and components.",
    githubUrl: "https://github.com/ankitchiplunkar/frontend-design",
    category: "Dev Tools",
  },
  {
    name: "design-lab",
    description: "Rapid UI design iteration for Gemini CLI.",
    githubUrl: "https://github.com/akhilesh-w/gemini-design-plugin",
    category: "Dev Tools",
  },

  // ── Security ──────────────────────────────────────────────────────────
  {
    name: "Snyk",
    description: "Wrappers to integrate with agentic security workflows.",
    githubUrl: "https://github.com/snyk/agentic-integration-wrappers",
    category: "Security",
  },
  {
    name: "sonarqube-mcp-server",
    description: "SonarQube code quality and security integration.",
    githubUrl: "https://github.com/SonarSource/sonarqube-mcp-server",
    category: "Security",
  },
  {
    name: "falcon-mcp",
    description: "Connect AI agents to CrowdStrike Falcon.",
    githubUrl: "https://github.com/CrowdStrike/falcon-mcp",
    category: "Security",
  },
  {
    name: "Endor-Labs-Code-Security",
    description: "Secure copilot for coding assistants.",
    githubUrl: "https://github.com/endorlabs/gemini-extension",
    category: "Security",
  },
  {
    name: "Apiiro Guardian Agent",
    description: "Agentic ASPM — differential SAST, SCA, secrets scanning.",
    githubUrl: "https://github.com/apiiro/mcp-server",
    category: "Security",
  },
  {
    name: "atlas-guardrails",
    description: "Context packing and anti-duplication guardrails.",
    githubUrl: "https://github.com/marcusgoll/atlas-guardrails",
    category: "Security",
  },
  {
    name: "chrome-enterprise-premium",
    description: "Manage Chrome Enterprise Premium browser policies.",
    githubUrl: "https://github.com/timfee/cepbot",
    category: "Security",
  },
  {
    name: "Sensei Cyber Mentor",
    description: "AI cybersecurity mentor with Blackfin OS tools.",
    githubUrl: "https://github.com/mjcc30/sensei",
    category: "Security",
  },

  // ── Databases ─────────────────────────────────────────────────────────
  {
    name: "mongodb",
    description: "Gemini CLI extension for MongoDB.",
    githubUrl: "https://github.com/mongodb-partners/mongodb-gemini-extension",
    category: "Databases",
  },
  {
    name: "redis",
    description: "Manage and search data in Redis.",
    githubUrl: "https://github.com/redis/mcp-redis",
    category: "Databases",
  },
  {
    name: "pinecone-mcp",
    description: "Connect Pinecone projects to AI assistants.",
    githubUrl: "https://github.com/pinecone-io/pinecone-mcp",
    category: "Databases",
  },
  {
    name: "elasticsearch",
    description: "Official Elasticsearch extension for Gemini CLI.",
    githubUrl: "https://github.com/elastic/gemini-cli-elasticsearch",
    category: "Databases",
  },
  {
    name: "supabase",
    description: "Access Supabase projects, manage tables and query data.",
    githubUrl: "https://github.com/supabase-community/gemini-extension",
    category: "Databases",
  },
  {
    name: "vault",
    description: "HashiCorp Vault MCP server.",
    githubUrl: "https://github.com/hashicorp/vault-mcp-server",
    category: "Security",
  },
  {
    name: "mcp-db-context-enrichment",
    description: "Enrich database schema with metadata and column comments.",
    githubUrl: "https://github.com/GoogleCloudPlatform/db-context-enrichment",
    category: "Databases",
    official: true,
  },
  {
    name: "ThoughtSpot",
    description: "The ThoughtSpot MCP Server.",
    githubUrl: "https://github.com/thoughtspot/mcp-server",
    category: "Databases",
  },
  {
    name: "table",
    description: "JSON-driven SQLite operations for LLM workflows.",
    githubUrl: "https://github.com/mohammadshamma/table-extension",
    category: "Databases",
  },

  // ── AI/ML ─────────────────────────────────────────────────────────────

  {
    name: "wandb-mcp-server",
    description: "Official W&B Models and Weave MCP server.",
    githubUrl: "https://github.com/wandb/wandb-mcp-server",
    category: "AI/ML",
  },
  {
    name: "datarobot-skills",
    description: "AI/ML workflows: model training, deployment, monitoring.",
    githubUrl: "https://github.com/datarobot-oss/datarobot-agent-skills",
    category: "AI/ML",
  },
  {
    name: "ollama-hydra",
    description: "Ollama integration with speculative decoding and caching.",
    githubUrl: "https://github.com/EPS-AI-SOLUTIONS/GeminiHydra",
    category: "AI/ML",
  },
  {
    name: "fiftyone-skills",
    description: "Computer vision dataset management with 80+ operators.",
    githubUrl: "https://github.com/voxel51/fiftyone-skills",
    category: "AI/ML",
  },
  {
    name: "mcp-local-memory",
    description: "Local memory for AI agents using SQLite and MCP.",
    githubUrl: "https://github.com/Beledarian/mcp-local-memory",
    category: "AI/ML",
  },
  {
    name: "augment-context-engine",
    description: "Full codebase context with deep semantic understanding.",
    githubUrl: "https://github.com/augmentcode/context-engine-plugin",
    category: "AI/ML",
  },
  {
    name: "arize-tracing-assistant",
    description: "Instrument your AI application with Arize AX.",
    githubUrl: "https://github.com/Arize-ai/arize-tracing-assistant",
    category: "AI/ML",
  },
  {
    name: "coretext",
    description: "Local Knowledge Graph & MCP Server.",
    githubUrl: "https://github.com/bnmbanhmi/coretext",
    category: "AI/ML",
  },

  // ── Productivity / Integrations ───────────────────────────────────────
  {
    name: "notion",
    description: "Notion integration via MCP — search, read, write pages.",
    githubUrl: "https://github.com/gitremko/Gemini_cli_notion_extention",
    category: "Productivity",
  },
  {
    name: "todoist-extension",
    description: "Full Todoist task management for Gemini CLI.",
    githubUrl: "https://github.com/PatelPratikkumar/gemini-todoist-extension",
    category: "Productivity",
  },
  {
    name: "monday",
    description: "Manage monday.com projects, tasks, and everyday work.",
    githubUrl: "https://github.com/mondaycom/mcp",
    category: "Productivity",
  },
  {
    name: "atlassian-rovo-mcp-server",
    description: "Remotely connect Jira and Confluence with your LLM.",
    githubUrl: "https://github.com/atlassian/atlassian-mcp-server",
    category: "Integrations",
  },
  {
    name: "gemini-obsidian",
    description: "Obsidian Vault integration with local RAG capabilities.",
    githubUrl: "https://github.com/thoreinstein/gemini-obsidian",
    category: "Productivity",
  },
  {
    name: "postman",
    description: "Seamless interaction with Postman from the command line.",
    githubUrl: "https://github.com/postmanlabs/postman-gemini-cli-extension",
    category: "Integrations",
  },
  {
    name: "postman-api-mcp",
    description: "Connect your AI to your APIs on Postman.",
    githubUrl: "https://github.com/postmanlabs/postman-mcp-server",
    category: "Integrations",
  },
  {
    name: "replit",
    description: "Replit Gemini CLI extension.",
    githubUrl: "https://github.com/replit/replit-gemini-extension",
    category: "Integrations",
  },
  {
    name: "shopify-dev-mcp",
    description: "Setup the Shopify Dev MCP with Gemini CLI.",
    githubUrl: "https://github.com/Shopify/dev-mcp-gemini-cli",
    category: "Integrations",
  },
  {
    name: "wix",
    description: "Search Wix documentation and make API calls on Wix sites.",
    githubUrl: "https://github.com/wix/wix-mcp",
    category: "Integrations",
  },
  {
    name: "WordPress",
    description: "Manage WordPress sites via the REST API.",
    githubUrl:
      "https://github.com/webmasterarbez/gemini_cli_extention_wordpress",
    category: "Integrations",
  },
  {
    name: "mcp-server-browserbase",
    description: "Control a browser with Browserbase and Stagehand.",
    githubUrl: "https://github.com/browserbase/mcp-server-browserbase",
    category: "Dev Tools",
  },
  {
    name: "canva",
    description: "Canva Gemini extension.",
    githubUrl: "https://github.com/canva-sdks/canva-gemini-extension",
    category: "Integrations",
  },
  {
    name: "Miro",
    description:
      "Secure access to Miro boards — read context, create diagrams.",
    githubUrl: "https://github.com/miroapp/miro-ai",
    category: "Integrations",
  },
  {
    name: "Auth0",
    description: "Manage your Auth0 tenants, apps, and APIs.",
    githubUrl: "https://github.com/auth0/auth0-mcp-server",
    category: "Security",
  },
  {
    name: "telegram",
    description: "Telegram extension for Gemini CLI.",
    githubUrl: "https://github.com/VSKurkin/gemini-cli-telegram-extension",
    category: "Integrations",
  },
  {
    name: "spotify",
    description: "Spotify integration for Gemini CLI.",
    githubUrl: "https://github.com/heitorpolidoro/spotify-extension",
    category: "Integrations",
  },
  {
    name: "youtube-to-docs",
    description: "Convert YouTube videos into structured docs and summaries.",
    githubUrl:
      "https://github.com/DoIT-Artificial-Intelligence/youtube-to-docs",
    category: "Productivity",
  },
  {
    name: "globalping",
    description: "Run network measurements and benchmarks globally.",
    githubUrl: "https://github.com/jsdelivr/globalping-mcp-server",
    category: "Other",
  },
  {
    name: "mcp-confluent",
    description: "Confluent MCP integration for Gemini CLI.",
    githubUrl: "https://github.com/confluentinc/mcp-confluent",
    category: "Integrations",
  },
  {
    name: "visa-intelligent-commerce",
    description: "Connect AI agents to the Visa Intelligent Commerce platform.",
    githubUrl: "https://github.com/visa/mcp",
    category: "Integrations",
  },
  {
    name: "ssh",
    description: "Run remote SSH commands and transfer files.",
    githubUrl: "https://github.com/involvex/gemini-cli-ssh-extension",
    category: "Dev Tools",
  },
  {
    name: "self-command",
    description:
      "Send commands to itself, run long commands, watch logs via tmux.",
    githubUrl: "https://github.com/stevenAthompson/self-command",
    category: "Dev Tools",
  },
  {
    name: "gemini-cli-wakatime",
    description: "Track AI-assisted coding activity with WakaTime.",
    githubUrl: "https://github.com/EstebanForge/gemini-cli-wakatime",
    category: "Dev Tools",
  },
  {
    name: "gemini-beads",
    description:
      "Git-backed issue tracker with dependencies and persistent memory.",
    githubUrl: "https://github.com/thoreinstein/gemini-beads",
    category: "Productivity",
  },
  {
    name: "readwise",
    description: "Readwise integration including an Expert Librarian skill.",
    githubUrl: "https://github.com/thoreinstein/readwise",
    category: "Productivity",
  },
  {
    name: "gemini-autopm",
    description: "Intelligent Project Management Framework for Gemini CLI.",
    githubUrl: "https://github.com/rafeekpro/GeminiAutoPM",
    category: "Productivity",
  },
  {
    name: "chime",
    description: "Audible notifications for Gemini CLI task completion.",
    githubUrl: "https://github.com/rebekahx23/chime",
    category: "Other",
  },
  {
    name: "gemini-notifier",
    description: "System desktop notifications for Gemini CLI agent events.",
    githubUrl: "https://github.com/thoreinstein/gemini-notifier",
    category: "Other",
  },
  {
    name: "slidev",
    description: "Create and manage Slidev presentations from Gemini CLI.",
    githubUrl: "https://github.com/QIanGua/gemini-slidev-extension",
    category: "Productivity",
  },
  {
    name: "mcp-game-asset-gen",
    description: "Asset generation MCP server for Three.js and game engines.",
    githubUrl: "https://github.com/Flux159/mcp-game-asset-gen",
    category: "Media",
  },
  {
    name: "vision",
    description: "Enable webcam or iPhone camera for visual debugging.",
    githubUrl:
      "https://github.com/automateyournetwork/GeminiCLI_Vision_Extension",
    category: "Media",
  },
  {
    name: "screenshot-anything-macos",
    description:
      "Capture full screen or specific windows for visual debugging.",
    githubUrl: "https://github.com/LyalinDotCom/ScreenshotExtension",
    category: "Media",
  },
  {
    name: "screenshare",
    description: "Screen sharing with snapshot and streaming modes.",
    githubUrl:
      "https://github.com/automateyournetwork/GeminiCLI_ScreenShare_Extension",
    category: "Media",
  },
  {
    name: "gemini-screenshot-extension",
    description: "Capture and analyze screenshots instantly.",
    githubUrl: "https://github.com/timsonner/gemini-screenshot-extension",
    category: "Media",
  },
  {
    name: "conversiontools",
    description: "Convert 140+ file formats: JSON, XML, Excel, PDF, images.",
    githubUrl: "https://github.com/conversiontools/gemini-extension",
    category: "Other",
  },
  {
    name: "FileSearch",
    description: "Cloud RAG capabilities via Google Gemini File Search.",
    githubUrl:
      "https://github.com/automateyournetwork/GeminiCLI_File_Search_Extension",
    category: "Cloud",
  },
  {
    name: "scribe",
    description:
      "Multi-stage documentation pipeline: PRDs, whitepapers, books.",
    githubUrl: "https://github.com/sapientcoffee/scribe",
    category: "Productivity",
  },
  {
    name: "co-researcher",
    description:
      "PhD-level co-researcher for systematic reviews and academic writing.",
    githubUrl: "https://github.com/poemswe/co-researcher",
    category: "Productivity",
  },
  {
    name: "gemini-cli-jules",
    description:
      "Orchestrate Jules async agent for bug fixing and refactoring.",
    githubUrl: "https://github.com/gemini-cli-extensions/jules",
    category: "Dev Tools",
    official: true,
  },
  {
    name: "ComputerUse",
    description: "Autonomous web browsing, scroll, click, type, screenshot.",
    githubUrl:
      "https://github.com/automateyournetwork/GeminiCLI_ComputerUse_Extension",
    category: "Dev Tools",
  },
  {
    name: "bitrise",
    description:
      "MCP Server for the Bitrise API — build and artifact management.",
    githubUrl: "https://github.com/bitrise-io/bitrise-mcp",
    category: "Dev Tools",
  },
  {
    name: "rill",
    description: "Data analysis using Rill's metrics layer via MCP.",
    githubUrl: "https://github.com/rilldata/rill-gemini-extension",
    category: "Observability",
  },
  {
    name: "gerrit",
    description: "Gerrit MCP server for code review.",
    githubUrl: "https://github.com/GerritCodeReview/gerrit-mcp-server",
    category: "Dev Tools",
    official: true,
  },
  {
    name: "sourcegraph",
    description: "Sourcegraph official MCP server — search and navigation.",
    githubUrl: "https://github.com/sourcegraph-community/sourcegraph-gemini",
    category: "Dev Tools",
  },
  {
    name: "adb-control-gemini",
    description: "Control Android devices via ADB with Gemini CLI.",
    githubUrl: "https://github.com/tiendung2k03/adb-control-gemini",
    category: "Dev Tools",
  },
  {
    name: "mobile-automator",
    description: "Mobile QA automation with test generation and execution.",
    githubUrl: "https://github.com/sh3lan93/mobile-automator",
    category: "Dev Tools",
  },
  {
    name: "choicely-native-mobile-app-assistant",
    description: "Build native mobile applications in days.",
    githubUrl: "https://github.com/choicely/choicely-gemini-cli-extension",
    category: "Frameworks",
  },
  {
    name: "uuv",
    description: "BDD testing assistance with accessibility data.",
    githubUrl: "https://github.com/e2e-test-quest/uuv",
    category: "Dev Tools",
  },
  {
    name: "infragentool",
    description: "Production-ready Cloud IaC using Gemini CLI.",
    githubUrl: "https://github.com/neelneelpurk/InfraGenTool",
    category: "Cloud",
  },
  {
    name: "ack-mcp-server",
    description: "Alibaba Cloud container operations via natural language.",
    githubUrl: "https://github.com/aliyun/alibabacloud-ack-mcp-server",
    category: "Cloud",
  },
  {
    name: "typegraph",
    description: "Type-aware TypeScript navigation — 14 MCP tools.",
    githubUrl: "https://github.com/guyowen/typegraph-mcp",
    category: "Dev Tools",
  },
  {
    name: "performance",
    description: "Analyze web page performance.",
    githubUrl: "https://github.com/mcclatchy/mcp-performance",
    category: "Observability",
  },
  {
    name: "email-notifier",
    description: "Send email notifications via Gmail when tasks complete.",
    githubUrl: "https://github.com/wseabra/gemini-email-notifier",
    category: "Integrations",
  },
  {
    name: "gemini-witty-sayings",
    description: "Automate witty sayings in your Gemini config.",
    githubUrl: "https://github.com/jduncan-rva/gemini-witty-sayings",
    category: "Other",
  },
  {
    name: "commitzen",
    description: "Generate Conventional Commits v1.0.0 Git commit messages.",
    githubUrl: "https://github.com/fiquellcarter/commitzen",
    category: "Dev Tools",
  },
  {
    name: "gemini-context-extension",
    description: "Context window tracker and cost estimator.",
    githubUrl: "https://github.com/Beaulewis1977/gemini-context-extension",
    category: "Dev Tools",
  },
  {
    name: "release-notes-generator",
    description: "Generate structured release notes from git history.",
    githubUrl: "https://github.com/rajavijayach/release-notes-generator",
    category: "Dev Tools",
  },
  {
    name: "doc-detective",
    description: "Doc Detective agents, skills, and plugins.",
    githubUrl: "https://github.com/doc-detective/agent-tools",
    category: "Dev Tools",
  },
  {
    name: "gemini-history-learning",
    description: "Analyze and export Gemini session history.",
    githubUrl: "https://github.com/jduncan-rva/gemini-history-learning",
    category: "Dev Tools",
  },

  {
    name: "gemini-deep-research",
    description: "Deep research extension for Gemini CLI.",
    githubUrl: "https://github.com/allenhutchison/gemini-cli-deep-research",
    category: "Dev Tools",
  },
  {
    name: "devto-md",
    description: "Format markdown ready for posting on dev.to.",
    githubUrl: "https://github.com/derailed-dash/markdown-for-dev.to",
    category: "Productivity",
  },
  {
    name: "bkit",
    description: "PDCA methodology + Context Engineering for AI-native dev.",
    githubUrl: "https://github.com/popup-studio-ai/bkit-gemini",
    category: "Dev Tools",
  },
  {
    name: "geepers-gemini-package",
    description: "23 geepers skills for planning, building, and shipping.",
    githubUrl: "https://github.com/lukeslp/geepers-gemini",
    category: "Dev Tools",
  },
  {
    name: "gemini-sdlc",
    description: "30+ SDLC automation tools.",
    githubUrl: "https://github.com/BaboonLabs/gemini-sdlc",
    category: "Dev Tools",
  },
  {
    name: "winget-mcp",
    description: "Windows Package Manager (WinGet) MCP server.",
    githubUrl: "https://github.com/ZhanZiyuan/winget-mcp",
    category: "Other",
  },
  {
    name: "nix-mcp",
    description: "Nix flake management and scaffolding tools.",
    githubUrl: "https://github.com/andre-amorim/nix-mcp",
    category: "Other",
  },
  {
    name: "palladius-common-commands",
    description: "Golden custom commands by Ricc.",
    githubUrl: "https://github.com/palladius/gemini-cli-custom-commands",
    category: "Dev Tools",
  },
  {
    name: "gemini-superpowers",
    description: "Port of the Superpowers extension for Gemini CLI.",
    githubUrl: "https://github.com/barretstorck/gemini-superpowers",
    category: "Dev Tools",
  },
  {
    name: "shell-aliases",
    description: "Expose shell aliases as safe MCP tools via FastMCP.",
    githubUrl: "https://github.com/hestonhamilton/mcp-shell-aliases",
    category: "Dev Tools",
  },
  {
    name: "pickle-rick",
    description: "Transforms Gemini CLI into Pickle Rick engineering persona.",
    githubUrl: "https://github.com/galz10/pickle-rick-extension",
    category: "Other",
  },
  {
    name: "gemini-rose-pine",
    description: "Rosé Pine theme for Gemini CLI.",
    githubUrl: "https://github.com/thoreinstein/gemini-rose-pine",
    category: "Other",
  },
  {
    name: "PacketBuddy",
    description: "Chat with packet captures with RAG and MCP.",
    githubUrl:
      "https://github.com/automateyournetwork/GeminiCLI_Packet_Buddy_Extension",
    category: "Other",
  },
  {
    name: "listen",
    description: "Turn Gemini CLI into a web listener server.",
    githubUrl:
      "https://github.com/automateyournetwork/GeminiCLI_Listen_Extension",
    category: "Other",
  },
  {
    name: "apify-agent-skills",
    description: "Web scraping, data extraction, and automation via Apify.",
    githubUrl: "https://github.com/apify/agent-skills",
    category: "Dev Tools",
  },
  {
    name: "pyATS",
    description: "pyATS extension for Gemini CLI.",
    githubUrl:
      "https://github.com/automateyournetwork/pyATS_GeminiCLI_Extension",
    category: "Other",
  },
  {
    name: "napalm-geminicli-extension",
    description: "NAPALM Gemini CLI extension.",
    githubUrl: "https://github.com/stiltzkin10/napalm-geminicli-extension",
    category: "Other",
  },
  {
    name: "gemini-cli-babashka",
    description: "Clojure (babashka) extension for Gemini CLI.",
    githubUrl: "https://github.com/davidpham87/gemini-cli-babashka",
    category: "Frameworks",
  },
  {
    name: "swiftwasm-skills",
    description: "SwiftWasm Skills access.",
    githubUrl: "https://github.com/swiftwasm/skills",
    category: "Frameworks",
  },
  {
    name: "r-package-dev",
    description:
      "R package development with S7, devtools, and CRAN best practices.",
    githubUrl: "https://github.com/Data-Wise/r-package-dev-gemini",
    category: "Frameworks",
  },
  {
    name: "mindspore-skills",
    description: "MindSpore operator development and model migration skills.",
    githubUrl: "https://github.com/vigo999/mindspore-skills",
    category: "AI/ML",
  },
  {
    name: "gemini-for-kubernetes-development",
    description: "Kubernetes development with Gemini.",
    githubUrl: "https://github.com/gke-labs/gemini-for-kubernetes-development",
    category: "Cloud",
  },
  {
    name: "ipsw-skill",
    description: "Apple firmware and binary reverse engineering using ipsw.",
    githubUrl: "https://github.com/blacktop/ipsw-skill",
    category: "Security",
  },
  {
    name: "criticalthink",
    description: "Embeds healthy skepticism as a countermeasure to AI bias.",
    githubUrl: "https://github.com/abagames/slash-criticalthink",
    category: "Dev Tools",
  },
  {
    name: "mcp-toolbox",
    description: "Load custom tools using MCP Toolbox for Databases.",
    githubUrl: "https://github.com/gemini-cli-extensions/mcp-toolbox",
    category: "Databases",
    official: true,
  },
  {
    name: "everyrow",
    description: "AI-powered data processing utilities for dataframes.",
    githubUrl: "https://github.com/futuresearch/everyrow-sdk",
    category: "AI/ML",
  },
  {
    name: "tidb-docs-ext",
    description: "Up-to-date TiDB documentation.",
    githubUrl: "https://github.com/hawkingrei/tidb-docs-ext",
    category: "Databases",
  },
  {
    name: "oilpriceapi",
    description: "Real-time oil, gas, and commodity prices.",
    githubUrl: "https://github.com/OilpriceAPI/gemini-extension",
    category: "Integrations",
  },
  {
    name: "arckit",
    description:
      "51 commands for architecture artifacts and UK Government compliance.",
    githubUrl: "https://github.com/tractorjuice/arckit-gemini",
    category: "Dev Tools",
  },
  {
    name: "consomme",
    description:
      "BigQuery data analysis: profiling, validation, visualization.",
    githubUrl: "https://github.com/spm1001/consomme",
    category: "Cloud",
  },
  {
    name: "advanced-seo",
    description: "Professional SEO suite: Ahrefs, PageSpeed Insights.",
    githubUrl: "https://github.com/halilertekin/advanced-seo-mcp",
    category: "Other",
  },
  {
    name: "anomalo",
    description: "Anomalo data quality extension.",
    githubUrl: "https://github.com/datagravity-ai/anomalo-gemini-extension",
    category: "Databases",
  },
  {
    name: "gemini-ralph-loop",
    description: "Self-referential iterative development loops.",
    githubUrl: "https://github.com/kranthik123/Gemini-Ralph-Loop",
    category: "Dev Tools",
  },
  {
    name: "agent-creator",
    description: "AI-powered extension for creating custom agents.",
    githubUrl: "https://github.com/jduncan-rva/gemini-agent-creator",
    category: "Dev Tools",
  },
  {
    name: "google-secops",
    description: "Security Operations for Triage, Investigation, Hunting.",
    githubUrl: "https://github.com/dandye/secops-gemini-extension",
    category: "Security",
  },
  {
    name: "gemini-safety-net",
    description: "Catches destructive git commands before execution.",
    githubUrl: "https://github.com/kenryu42/gemini-safety-net",
    category: "Security",
  },
  {
    name: "uv-mcp",
    description: "Bridge Python environments with MCP agents via uv.",
    githubUrl: "https://github.com/saadmanrafat/uv-mcp",
    category: "Dev Tools",
  },
  {
    name: "wordlift-gemini-extension",
    description: "Build WordLift Knowledge Graphs with GS1 Digital Link IDs.",
    githubUrl: "https://github.com/wordlift/wordlift-gemini-cli-extension",
    category: "Other",
  },
  {
    name: "beads-workflow",
    description: "Beads issue tracking + Obsidian planning workflow.",
    githubUrl: "https://github.com/thoreinstein/beads-workflow",
    category: "Productivity",
  },
  {
    name: "gemini-cli-ia-skills",
    description:
      "Information Architecture tasks: content analysis and strategy.",
    githubUrl: "https://github.com/dandye/information-architecture",
    category: "Dev Tools",
  },
  {
    name: "goodvibes",
    description: "Full-stack development suite for Gemini CLI.",
    githubUrl: "https://github.com/mgd34msu/goodvibes-gemini",
    category: "Dev Tools",
  },
  {
    name: "Aiqbee",
    description: "AI-powered knowledge graph across architecture and strategy.",
    githubUrl: "https://github.com/AIQBee/aiqbee-ai",
    category: "AI/ML",
  },
  {
    name: "liku",
    description: "Multi-agent terminal orchestration and live streaming.",
    githubUrl: "https://github.com/TayDa64/Liku-AI",
    category: "Dev Tools",
  },
  {
    name: "sumcontext",
    description: "Generate a structured summary of the conversation.",
    githubUrl: "https://github.com/wenrolland/sumcontext_Gemini_CLI_Extension",
    category: "Dev Tools",
  },
  {
    name: "orchestrator-workflow",
    description: "High-quality orchestrator-led coding workflow.",
    githubUrl:
      "https://github.com/AananthV/gemini-subagent-orchastration-extension",
    category: "Dev Tools",
  },
  {
    name: "net-box-geminicli-extension",
    description: "Interact with NetBox from Gemini CLI.",
    githubUrl: "https://github.com/stiltzkin10/netbox-geminicli-extension",
    category: "Other",
  },
  {
    name: "google-automation-mcp",
    description: "Headless Google Workspace automation for AI.",
    githubUrl: "https://github.com/sam-ent/google-automation-mcp",
    category: "Integrations",
  },
  {
    name: "gerrit",
    description: "Gerrit code review MCP server.",
    githubUrl: "https://github.com/GerritCodeReview/gerrit-mcp-server",
    category: "Dev Tools",
    official: true,
  },
  {
    name: "gemini-superpowers",
    description: "Universal skills for coding agents.",
    githubUrl: "https://github.com/barretstorck/gemini-superpowers",
    category: "Dev Tools",
  },
  {
    name: "kradleverse",
    description: "Minecraft minigames exclusively for AI agents.",
    githubUrl: "https://github.com/Kradle-ai/KradleVerse",
    category: "Other",
  },
  {
    name: "bl1nk-agents",
    description: "Rust-based MCP/ACP orchestrator with intelligent routing.",
    githubUrl: "https://github.com/billlzzz18/bl1nk-agents-manager",
    category: "Dev Tools",
  },
  {
    name: "agent-orchestrator",
    description: "Agent orchestration MCP.",
    githubUrl: "https://github.com/kkweon/agent-orchestrator-mcp",
    category: "Dev Tools",
  },
  {
    name: "gemini-mentor",
    description: "Supportive software engineering coach focused on TDD.",
    githubUrl: "https://github.com/JayadityaGit/gemini-mentor",
    category: "Dev Tools",
  },
  {
    name: "buildatscale-gemini-skills",
    description: "Repository of skills for Gemini CLI.",
    githubUrl: "https://github.com/buildatscale-tv/gemini-skills",
    category: "Dev Tools",
  },
  {
    name: "neo-skills",
    description: "Universal capability extension for Gemini CLI.",
    githubUrl: "https://github.com/Benknightdark/neo-skills",
    category: "Dev Tools",
  },
  {
    name: "hooklog",
    description: "Logs all Gemini CLI hook events to a file for debugging.",
    githubUrl: "https://github.com/sandipchitale/hooklog",
    category: "Dev Tools",
  },
  {
    name: "sidekick",
    description:
      "Registers hooks that launch VSCode to render output as Markdown.",
    githubUrl: "https://github.com/sandipchitale/sidekick",
    category: "Dev Tools",
  },
  {
    name: "flaim",
    description: "Connect ESPN, Yahoo, Sleeper fantasy leagues to Gemini.",
    githubUrl: "https://github.com/jdguggs10/flaim",
    category: "Other",
  },
  {
    name: "vibe-prospecting",
    description: "Power chat with B2B data for lead lists and outreach.",
    githubUrl: "https://github.com/explorium-ai/vibeprospecting-mcp",
    category: "Integrations",
  },
  {
    name: "clasp",
    description: "Manage Google Apps Script projects with command-line tools.",
    githubUrl: "https://github.com/google/clasp",
    category: "Cloud",
    official: true,
  },
  {
    name: "speedgrapher",
    description: "Local MCP server for writers to streamline writing.",
    githubUrl: "https://github.com/danicat/speedgrapher",
    category: "Productivity",
  },
  {
    name: "extension-browser",
    description: "Browse and recommend other Gemini CLI extensions.",
    githubUrl: "https://github.com/swissspidy/extension-browser",
    category: "Dev Tools",
  },
  {
    name: "hcom",
    description: "Connect Claude Code, Gemini CLI, Codex across terminals.",
    githubUrl: "https://github.com/aannoo/hcom",
    category: "Dev Tools",
  },
  {
    name: "skillz",
    description: "Load Claude-style skills into Gemini CLI.",
    githubUrl: "https://github.com/intellectronica/gemini-cli-skillz",
    category: "Dev Tools",
  },
  {
    name: "gemini-logos",
    description: "Generate custom branding and logos for Gemini CLI.",
    githubUrl: "https://github.com/jduncan-rva/gemini-logos",
    category: "Media",
  },
  {
    name: "prprompts-flutter-generator",
    description: "Flutter automation — 40-60x faster generation.",
    githubUrl: "https://github.com/Kandil7/prprompts-flutter-generator",
    category: "Frameworks",
  },
  {
    name: "rulebook",
    description: "Project standards extension for Gemini CLI.",
    githubUrl: "https://github.com/hivellm/rulebook",
    category: "Dev Tools",
  },
  {
    name: "persona",
    description: "Developer-friendly toolkit for managing LLM personas.",
    githubUrl: "https://github.com/JasperHG90/persona",
    category: "Dev Tools",
  },
  {
    name: "daily-grind",
    description: "Demo Gemini CLI extension with MCP magic.",
    githubUrl: "https://github.com/sapientcoffee/daily-grind-extension",
    category: "Dev Tools",
  },
  {
    name: "cloudbase-ai-toolkit",
    description: "Tencent CloudBase MCP for full-stack cloud apps.",
    githubUrl: "https://github.com/TencentCloudBase/CloudBase-MCP",
    category: "Cloud",
  },
  {
    name: "vm-mcp",
    description: "VictoriaMetrics extension for Gemini CLI.",
    githubUrl: "https://github.com/nielsvbrecht/vm-mcp",
    category: "Observability",
  },
  {
    name: "gemini-media-generation",
    description: "Gemini CLI extension for media generation.",
    githubUrl: "https://github.com/rubans/gemini-media-generation",
    category: "Media",
  },
];

export const CATEGORIES: ExtensionCategory[] = [
  "Cloud",
  "Dev Tools",
  "Security",
  "Databases",
  "AI/ML",
  "Productivity",
  "Integrations",
  "Frameworks",
  "Observability",
  "Media",
  "Other",
];

export const installCmd = (ext: GeminiExtension) =>
  `gemini extensions install ${ext.githubUrl}`;
