/**
 * Copyright (c) 2026 Inso Code
 * 
 * Adversarial Dual-Review / Maker-Checker Service
 * Enforces strict segregation of duties (Banking/Finance/SOX).
 * Before any AI agent commits code or executes a production change,
 * an independent Adversarial Auditor Agent must review and approve it.
 */

import { GeminiAiService } from '../gemini/gemini.service.js';
import { logger } from '../../../shared/logger.js';

class AuditorService {
    /**
     * Conducts an independent adversarial review of a proposed change.
     * @param {string} proposedCode The code or command generated by the primary agent
     * @param {string} context The context of the task
     * @returns {Promise<boolean>} true if approved, false if rejected
     */
    async enforceDualReview(proposedCode, context) {
        if (process.env.NODE_ENV !== 'production' && process.env.ENABLE_DUAL_REVIEW !== 'true') {
            return true;
        }

        logger.info('[AUDITOR] Initiating Adversarial Dual-Review (Maker-Checker)...');

        const prompt = `
        You are an independent, highly critical Adversarial Auditor Agent.
        Your job is to act as the "Checker" in a strict Maker-Checker workflow for a bank.
        Another AI agent has proposed the following code/action for context: ${context}.
        
        Proposed Payload:
        \`\`\`
        ${proposedCode.substring(0, 5000)}
        \`\`\`

        Review for:
        1. Security vulnerabilities (injection, XSS, insecure crypto, logging secrets).
        2. Financial logic flaws (race conditions, integer overflows in money handling).
        3. Compliance violations (unauthorized data exfiltration, missing audit trails).
        
        If you find ANY critical issue, respond EXACTLY with "REJECTED" followed by the reason.
        If the payload is safe and meets strict financial compliance, respond EXACTLY with "APPROVED".
        `;

        try {
            const response = await GeminiAiService.generateContent(prompt);
            const verdict = response.trim().toUpperCase();

            if (verdict.startsWith('APPROVED')) {
                logger.info('[AUDITOR] Secondary AI approval GRANTED.');
                return true;
            } else {
                logger.warn(`[AUDITOR] Secondary AI approval DENIED: ${verdict}`);
                return false;
            }
        } catch (error) {
            logger.error(`[AUDITOR] Dual-Review failed: ${error.message}`);
            // Fail closed for maximum security in finance
            return false;
        }
    }
}

export const auditorService = new AuditorService();
