import { ApiGatewayServiceClient } from '@google-cloud/api-gateway';
import { logger } from '../../../shared/logger.js';
import config from '../../../../config/index.js';

/**
 * Google Cloud API Gateway Service.
 * Grants the Swarm the ability to programmatically deploy and expose its own
 * generated microservices securely to the world, utilizing native GCP API Gateway capabilities.
 * This is crucial for beating Cursor/Windsurf by not just writing code, but natively deploying infrastructure.
 */
class GoogleApiGatewayService {
    constructor() {
        try {
            this.client = new ApiGatewayServiceClient();
            this.locationPath = this.client.locationPath(config.gcp.project_id, config.gcp.location || 'us-central1');
            logger.info('🚪 [API Gateway] Google Cloud API Gateway Client initialized.');
        } catch (error) {
            logger.warn('⚠️ [API Gateway] Could not initialize API Gateway Client.');
        }
    }

    /**
     * Programmatically creates an API Gateway for a new microservice generated by the Swarm.
     * @param {string} apiId - The unique ID of the API
     * @param {string} displayName - Human-readable name
     */
    async createApi(apiId, displayName) {
        logger.info(`🚪 [API Gateway] Swarm is autonomously creating a public API Gateway: ${apiId}...`);
        
        try {
            const apiPath = this.client.apiPath(config.gcp.project_id, 'global', apiId);
            
            const [operation] = await this.client.createApi({
                parent: this.client.locationPath(config.gcp.project_id, 'global'),
                apiId: apiId,
                api: {
                    displayName: displayName,
                    // Typically managed configs are required here, simplified for abstraction
                },
            });

            logger.info(`⏳ [API Gateway] Waiting for API Gateway deployment operation...`);
            const [response] = await operation.promise();
            
            logger.info(`✅ [API Gateway] API Gateway deployed successfully! Name: ${response.name}`);
            return response;
        } catch (error) {
            logger.error(`❌ [API Gateway] Failed to create API Gateway:`, error.message);
            return null;
        }
    }
}

export const apiGatewayService = new GoogleApiGatewayService();
