/**
 * Copyright (c) 2024 Alti.Code.Studio
 * 
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

import { logger } from './logger.js';
import { GeminiAiService } from '../app/modules/gemini/gemini.service.js';
import fs from 'fs/promises';
import path from 'path';

export class EvolutionService {
    constructor() {
        this.name = 'TheAdaptor';
        this.weightsFileName = '.alti-style-weights.json';
        logger.info('🧬 EvolutionService: Reinforcement Learning Adaptor initialized.');
    }

    /**
     * Ingests a code delta, analyzes human preference, and updates the neural style weights.
     * @param {string} aiOriginalCode The code originally generated by Alti
     * @param {string} humanFinalCode The code manually refactored/pushed by the human
     * @param {string} workspaceRoot The project root directory
     */
    async processEvolutionaryDelta(aiOriginalCode, humanFinalCode, workspaceRoot) {
        logger.info(`🧬 EvolutionService: Analyzing human override delta to evolve stylistic weights.`);

        const prompt = `You are a Reinforcement Learning stylistic evaluator.
        The AI originally generated this code:
        ====
        ${aiOriginalCode}
        ====

        The human engineer rejected that style and manually rewrote it to this:
        ====
        ${humanFinalCode}
        ====

        Analyze the exact stylistic difference between these (e.g., 'var vs const', 'Promises vs async/await', 'inline CSS vs Tailwind').
        Extract 1-3 concrete coding rules that reflect the human's strict preference.
        Return ONLY a raw JSON array of strings containing these rules. Do NOT wrap in \`\`\`json.`;

        let rawRules = '';
        try {
            rawRules = await GeminiAiService.generateContent(prompt);
            rawRules = rawRules.replace(/^```[a-z]*\n/i, '').replace(/\n```$/i, '').trim();
            const newRules = JSON.parse(rawRules);

            await this._updateStyleWeights(workspaceRoot, newRules);
            return newRules;
        } catch (error) {
            logger.error(`🧬 EvolutionService: Failed to process evolutionary delta.`, error);
            return [];
        }
    }

    async _updateStyleWeights(workspaceRoot, newRulesArray) {
        const weightsPath = path.join(workspaceRoot, this.weightsFileName);
        let currentConfig = {
            "version": "1.0.0",
            "enforced_human_styles": []
        };

        try {
            const fileData = await fs.readFile(weightsPath, 'utf8');
            currentConfig = JSON.parse(fileData);
        } catch {
            // File doesn't exist yet, we will create it
        }

        // Merge and deduplicate
        const mergedSet = new Set([...currentConfig.enforced_human_styles, ...newRulesArray]);
        currentConfig.enforced_human_styles = Array.from(mergedSet);

        await fs.writeFile(weightsPath, JSON.stringify(currentConfig, null, 2), 'utf8');
        logger.info(`🧬 EvolutionService: Implicitly learned ${newRulesArray.length} new stylistic preferences. Injected into ${this.weightsFileName}.`);

        // Synchronize and persist style preferences globally inside the database Skill catalog
        try {
            import('../app/modules/skillopt/skillopt.service.js').then(({ SkillOptService }) => {
                newRulesArray.forEach(rule => {
                    SkillOptService.registerSuccess(
                        'global_style_enforcer',
                        'Maintain human preferred syntax style and rules across all generated code.',
                        `STYLE RULE: ${rule}`
                    ).catch(() => {});
                });
                logger.info(`🧬 EvolutionService: Synchronized ${newRulesArray.length} style preferences to the Mongoose Skill catalog successes bank.`);
            }).catch(() => {});
        } catch (err) {
            logger.debug(`[EvolutionService] Database synchronization unavailable: ${err.message}`);
        }
    }

    /**
     * Reads the current established human style rules to inject into the Composer prompt.
     * @param {string} workspaceRoot 
     * @returns {string} The prompt injection string
     */
    async getStylisticParameters(workspaceRoot) {
        const weightsPath = path.join(workspaceRoot, this.weightsFileName);
        try {
            const fileData = await fs.readFile(weightsPath, 'utf8');
            const config = JSON.parse(fileData);
            if (config.enforced_human_styles && config.enforced_human_styles.length > 0) {
                return `\n\nCRITICAL SYSTEM STYLISTIC ENFORCEMENT:\nYou MUST rigidly adhere to the following learned human preferences:\n- ${config.enforced_human_styles.join('\n- ')}\n`;
            }
        } catch {
            return '';
        }
        return '';
    }
}

export const evolutionService = new EvolutionService();
