apiVersion: batch/v1
kind: CronJob
metadata:
  name: chaos-monkey
  namespace: kube-system
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: chaos-monkey-sa
          containers:
          - name: chaos-monkey
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - "kubectl delete pods --all -n default --field-selector status.phase=Running | head -n 1"
          restartPolicy: OnFailure
