apiVersion: batch/v1
kind: CronJob
metadata:
  name: chaos-io-stress
  namespace: kube-system
spec:
  schedule: "*/55 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: stress-ng
            image: polinux/stress-ng
            command: ["stress-ng", "--hdd", "1", "--hdd-bytes", "1G", "--timeout", "60s"]
            volumeMounts:
            - name: host-fs
              mountPath: /host
          volumes:
          - name: host-fs
            hostPath:
              path: /
          restartPolicy: Never
