apiVersion: batch/v1
kind: CronJob
metadata:
  name: chaos-dns
  namespace: kube-system
spec:
  schedule: "*/45 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: chaos-monkey-sa
          containers:
          - name: chaos-dns
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - "kubectl scale deployment coredns --replicas=0 -n kube-system && sleep 30 && kubectl scale deployment coredns --replicas=2 -n kube-system"
          restartPolicy: OnFailure
