apiVersion: batch/v1
kind: CronJob
metadata:
  name: chaos-eviction
  namespace: kube-system
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: chaos-monkey-sa
          containers:
          - name: chaos-eviction
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - "kubectl get nodes -o name | head -n 1 | xargs -I {} kubectl drain {} --ignore-daemonsets --delete-emptydir-data --force && sleep 60 && kubectl uncordon {}"
          restartPolicy: OnFailure
