apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: chaos-network
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: chaos-network
  template:
    metadata:
      labels:
        name: chaos-network
    spec:
      hostNetwork: true
      containers:
      - name: chaos-network
        image: alpine:latest
        securityContext:
          privileged: true
        command: ["/bin/sh", "-c"]
        args:
        - "apk add iproute2 && tc qdisc add dev eth0 root netem delay 50ms || true && sleep infinity"
