"use client";

import React, { useEffect, useState } from "react";
import {
  Table,
  TableHeader,
  TableColumn,
  TableBody,
  TableRow,
  TableCell,
} from "@heroui/table";
import { Card, CardBody, CardHeader } from "@heroui/card";
import { Chip } from "@heroui/chip";

import { API_URL } from "@/lib/config";

export default function MemoryDashboardPage() {
  const [memories, setMemories] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`${API_URL}/memory?limit=100`)
      .then((r) => r.json())
      .then((data) => {
        if (data.success && Array.isArray(data.data)) {
          setMemories(data.data);
        }
        setLoading(false);
      })
      .catch((err) => {
        console.error("Failed to fetch memory", err);
        setLoading(false);
      });
  }, [API_URL]);

  return (
    <div className="p-8 w-full max-w-[1400px] mx-auto">
      <Card className="bg-background/60 dark:bg-default-100/50 backdrop-blur-lg backdrop-saturate-150">
        <CardHeader className="flex flex-col items-start px-6 pt-6 pb-2">
          <h1 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-secondary">
            Enterprise Vector Memory
          </h1>
          <p className="text-sm text-default-500 mt-1">
            Long-term semantic context generated by The Historian and
            Orchestrator
          </p>
        </CardHeader>
        <CardBody className="px-6 pb-6 pt-2">
          <Table
            aria-label="Vector Memory Log"
            classNames={{
              wrapper: "max-h-[700px] bg-transparent",
              td: "border-b border-divider py-3",
              th: "bg-default-100/50 text-default-600",
            }}
          >
            <TableHeader>
              <TableColumn>ENTRY ID</TableColumn>
              <TableColumn>AGENT / SOURCE</TableColumn>
              <TableColumn>ACTION</TableColumn>
              <TableColumn>SEMANTIC DOCUMENT</TableColumn>
            </TableHeader>
            <TableBody
              emptyContent={
                loading
                  ? "Loading memory bank..."
                  : "No memories found in the database."
              }
              isLoading={loading}
              items={memories}
            >
              {(item: any) => (
                <TableRow key={item.id}>
                  <TableCell className="font-mono text-xs text-default-400">
                    {item.id.substring(0, 18)}...
                  </TableCell>
                  <TableCell>
                    <Chip color="primary" size="sm" variant="flat">
                      {item.metadata?.agent ||
                        item.metadata?.source ||
                        "System"}
                    </Chip>
                  </TableCell>
                  <TableCell>
                    <span className="text-sm font-medium">
                      {item.metadata?.action || "Indexed"}
                    </span>
                  </TableCell>
                  <TableCell>
                    <div className="text-sm text-default-600 max-w-xl truncate">
                      {item.document}
                    </div>
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardBody>
      </Card>
    </div>
  );
}
