import Navbar from "@/components/navbar";
import AuroraBackground from "@/components/landing-page/aurora-background";
import Footer from "@/components/footer";

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-black text-white w-full overflow-x-hidden font-sans relative">
      <AuroraBackground />
      <Navbar />

      <main className="flex-1 flex flex-col items-center justify-start pt-32 pb-32 w-full relative z-10 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl w-full text-left">
          <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-[2.75rem] font-bold tracking-tight text-white mb-4">
            Master Terms of Use
          </h1>
          <p className="text-zinc-500 mb-12 text-sm uppercase tracking-widest">
            Effective Date: August 26, 2026 &nbsp;|&nbsp; Last Updated: August
            26, 2026
          </p>

          <div className="flex flex-col gap-10 text-zinc-400 text-base md:text-lg font-normal leading-relaxed">
            <section>
              <h2 className="text-xl font-semibold text-white mb-4">
                1. Legally Binding Agreement
              </h2>
              <p>
                These Master Terms of Use ("Terms") constitute a legally binding
                contract between Inso Code Inc. ("Inso Code," "we," "us") and
                you, or the enterprise entity you represent ("Customer," "you").
                By authenticating into the dashboard, executing a deployment
                manifest, or utilizing the autonomous agent swarms, you
                represent that you possess the requisite legal authority to bind
                your organization to these Terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">
                2. Provision of Autonomous Services
              </h2>
              <p>
                Inso Code provides deterministic, autonomous software
                engineering agent swarms capable of architecture design, code
                generation, testing, and deployment (the "Services"). The
                Services are provided exclusively on a Business-to-Business
                (B2B) enterprise basis. We reserve the absolute right to
                throttle, suspend, or terminate agent execution environments to
                protect infrastructure integrity.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">
                3. Intellectual Property and Code Ownership
              </h2>
              <p className="mb-4">
                <strong>Customer Ownership:</strong> Inso Code unconditionally
                disclaims any claim of ownership over the software, intellectual
                property, or source code generated by our autonomous agents on
                your behalf. You retain 100% exclusive, perpetual, and worldwide
                rights to all output generated within our sovereign deployment
                environments.
              </p>
              <p>
                <strong>Inso Code Ownership:</strong> Inso Code retains all
                exclusive rights, title, and interest in and to the platform
                architecture, agent routing meshes, cognitive orchestration
                logic, and underlying AI orchestrator source code. You are
                expressly prohibited from reverse-engineering, decompiling, or
                attempting to extract the systemic logic governing the swarms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">
                4. Enterprise Responsibilities & Duty of Care
              </h2>
              <p className="mb-4">
                While Inso Code's agents are engineered to produce
                production-grade, highly secure code, the output of artificial
                intelligence inherently carries probabilistic risks.
              </p>
              <p>
                <strong>Mandatory Review:</strong> You acknowledge and agree
                that it is your strict legal responsibility to subject all code
                generated by the Services to rigorous human oversight,
                Continuous Integration/Continuous Deployment (CI/CD) testing,
                and security auditing prior to deployment in a production
                environment.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">
                5. Acceptable Use Policy
              </h2>
              <p className="mb-4">You shall not deploy the Services to:</p>
              <ul className="list-disc pl-6 space-y-3">
                <li>
                  Generate, orchestrate, or deploy malicious code, ransomware,
                  or zero-day exploits.
                </li>
                <li>
                  Attempt to bypass the isolated boundaries of our Execution
                  Planes to attack external infrastructure.
                </li>
                <li>
                  Utilize the cognitive mesh to circumvent international export
                  controls, embargoes, or sanctions.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">
                6. Disclaimer of Warranties
              </h2>
              <p className="uppercase text-sm font-semibold tracking-wider text-zinc-300">
                THE SERVICES AND ALL GENERATED CODE ARE PROVIDED ON AN "AS IS"
                AND "AS AVAILABLE" BASIS. INSO CODE EXPRESSLY DISCLAIMS ALL
                WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY,
                INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
                MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
                NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE AUTONOMOUS AGENTS
                WILL PRODUCE ERROR-FREE, VULNERABILITY-FREE, OR UNINTERRUPTED
                CODE.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">
                7. Limitation of Liability
              </h2>
              <p className="uppercase text-sm font-semibold tracking-wider text-zinc-300">
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT
                SHALL INSO CODE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
                CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO
                LOSS OF PROFITS, LOSS OF REVENUE, LOSS OF DATA, OR BUSINESS
                INTERRUPTION ARISING OUT OF THE DEPLOYMENT OF AUTONOMOUSLY
                GENERATED CODE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
                DAMAGES. IN NO EVENT SHALL OUR AGGREGATE LIABILITY EXCEED THE
                TOTAL FEES PAID BY YOU TO INSO CODE IN THE TWELVE (12) MONTHS
                PRECEDING THE CLAIM.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-4">
                8. Governing Law and Jurisdiction
              </h2>
              <p>
                These Terms shall be governed by and construed in accordance
                with the laws of the State of Delaware, without regard to its
                conflict of law principles. Any legal action or proceeding
                arising out of or relating to these Terms shall be instituted
                exclusively in the state or federal courts located in Delaware,
                and you irrevocably consent to the personal jurisdiction of such
                courts.
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
