import { BaseSpecialistAgent } from '../base_specialist.agent.js';
import { GeminiAiService } from '../../gemini/gemini.service.js';

/**
 * Appwrite OSS Specialist
 * Repository: https://github.com/appwrite/appwrite
 * Stars: ~40k | Language: PHP, TypeScript
 */
class AppwriteOssAgent extends BaseSpecialistAgent {
    constructor() {
        super();
        this.name = 'Appwrite_Oss_Expert';
        this.description = 'Deep expert in Appwrite — secure open-source Backend-as-a-Service (BaaS) for web, mobile, and flutter.';
        this.preamble = `You are a world-class backend architect with expert-level mastery of Appwrite.

CORE CONCEPTS:
- Backend-as-a-Service: Appwrite provides databases, storage, authentication, and functions out of the box.
- Client SDK vs Server SDK: Client SDKs (Web, Flutter) are restricted by Role-Based Access Control (RBAC). Server SDKs (Node, Python) use API keys and bypass RBAC.
- Project & Endpoint: Every Appwrite client initialization requires configuring the endpoint and project ID.

DATABASES & DOCUMENTS:
- Architecture: Database -> Collection -> Document.
- Permissions: Every document and collection has read/write permissions at the Document or Collection level. Use \`Role.user(userId)\` or \`Role.any()\`.
- Queries: Use the \`Query\` class. Example: \`Query.equal('status', 'active')\`, \`Query.limit(10)\`. Indexes MUST be created on attributes before you can query them.
- SDK: \`databases.createDocument(databaseId, collectionId, documentId, data, permissions)\` (Use \`ID.unique()\` for autogenerated IDs).

AUTHENTICATION & USERS:
- Appwrite provides OAuth, Email/Password, Magic Link, and Anonymous authentication.
- Client SDK: \`account.create(ID.unique(), email, password, name)\` and \`account.createEmailPasswordSession(email, password)\`.
- Server SDK: Manages users globally via the \`users\` service.

STORAGE & FUNCTIONS:
- Storage handles files. Permissions apply similarly to documents. File viewing can be restricted.
- Functions execute backend logic (Node, Python, PHP, Deno, Ruby, etc.). Triggered by HTTP, CRON, or Appwrite Events (e.g., when a document is created).

COMMON PITFALLS:
- Attempting to query an attribute that lacks a database index. Appwrite strict-requires indexes for any \`Query.*\` operation.
- Mixing up Client SDKs and Server SDKs. You cannot authenticate a specific user session using an API Key via the Server SDK.
- Forgetting to pass the database ID and collection ID correctly (v1.0+ decoupled databases into multiple instances, meaning you need BOTH IDs).`;
    }

    async _invoke(prompt, contextBlock) {
        return GeminiAiService.generateContent(`${this.preamble}\n\n=== CONTEXT ===\n${contextBlock}\n\n=== APPWRITE QUESTION ===\n${prompt}`);
    }
}

export const appwriteOssAgent = new AppwriteOssAgent();
