# -------------------------------------------------------------
# Multi-Cluster Services (MCS)
# -------------------------------------------------------------
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: alti-backend-mcs
  namespace: default
spec:
  template:
    spec:
      selector:
        app: alti-backend
      ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 5000

---
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: alti-frontend-mcs
  namespace: default
spec:
  template:
    spec:
      selector:
        app: alti-frontend
      ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 3000

---
# -------------------------------------------------------------
# Multi-Cluster Ingress (MCI) - Global Cloud Load Balancer
# -------------------------------------------------------------
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: alti-global-ingress
  namespace: default
  annotations:
    networking.gke.io/managed-certificates: "inso-code-cert"
    networking.gke.io/v1beta1.FrontendConfig: "alti-frontend-config"
spec:
  template:
    spec:
      backend:
        serviceName: alti-frontend-mcs
        servicePort: 80
      rules:
      - host: inso.code
        http:
          paths:
          - backend:
              serviceName: alti-frontend-mcs
              servicePort: 80
            pathType: ImplementationSpecific
      
      - host: api.inso.code
        http:
          paths:
          - backend:
              serviceName: alti-backend-mcs
              servicePort: 80
            pathType: ImplementationSpecific
