/**
 * Copyright (c) 2026 Inso Code
 *
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

import { GeminiAiService } from '../gemini/gemini.service.js';
import { hermesAgent } from './hermes.agent.js';
import { logger } from '../../../shared/logger.js';

class HermesDebateChamberService {
    constructor() {
        this.maxDebateRounds = 2;
    }

    /**
     * Orchestrates an adversarial debate between SwarmArchitect, SwarmSecurityAuditor,
     * and the specialized Hermes Agent to audit and refine architectural decisions before coding.
     * 
     * @param {string} objective - The complex engineering feature objective.
     * @param {object} initialDesign - The initial design generated by the Architect.
     * @returns {Promise<string>} The refined architectural consensus.
     */
    async initiateDebate(objective, initialDesign) {
        logger.info(`🏛️ [Hermes Debate] Convening Cross-Agent Debate Chamber for: "${objective.substring(0, 50)}..."`);

        const designStr = typeof initialDesign === 'string' ? initialDesign : JSON.stringify(initialDesign, null, 2);

        try {
            // ── Phase 1: Beta (The SRE Pragmatist) Critique ──
            logger.info(`🛡️ [Hermes Debate] Beta (SRE Pragmatist) is auditing the design...`);
            const betaPrompt = `You are BETA, a hyper-conservative, pragmatic Site Reliability Engineer. 
Review the proposed architecture design below. Identify all latency traps, single points of failure, scaling issues, and database partition problems. 
Explain how to simplify it, keep it legacy-compatible, and ensure strict ACID properties.

PROPOSED DESIGN:
${designStr}

OBJECTIVE:
${objective}`;
            const betaCritique = await GeminiAiService.generateContent(betaPrompt);
            logger.info(`🛡️ [Hermes Debate] Beta Critique complete.`);

            // ── Phase 2: Hermes (The AI Code Auditor) Critique ──
            logger.info(`🤖 [Hermes Debate] Hermes Agent is running advanced code-level security and logic audit...`);
            const hermesPrompt = `You are HERMES, the hyper-critical AI Code Auditor Agent.
Audit the proposed design and Beta SRE's critique. Identify all logic vulnerabilities, API contract flaws, O(N) complexity concerns, and potential sandbox escape vectors.
Formulate a concrete, highly secure, optimized counter-proposal.

PROPOSED DESIGN:
${designStr}

BETA CRITIQUE:
${betaCritique}`;

            let hermesOpinion = '';
            try {
                // Try executing via the local Hermes CLI / Agent
                hermesOpinion = await hermesAgent.executeTask(hermesPrompt);
            } catch (err) {
                logger.warn(`⚠️ [Hermes Debate] Local Hermes CLI execution skipped or failed: ${err.message}. Falling back to inline model synthesis.`);
                // Fallback to tri-cloud inline model synthesis
                const fallbackPrompt = `You are HERMES, a hyper-critical software security auditor model.
Analyze this proposed architecture and Beta's critique. Focus on API logic, security boundaries, and runtime performance. Provide a robust counter-proposal.

PROPOSED DESIGN:
${designStr}

BETA'S CRITIQUE:
${betaCritique}`;
                hermesOpinion = await GeminiAiService.generateContent(fallbackPrompt);
            }
            logger.info(`🤖 [Hermes Debate] Hermes Critique complete.`);

            // ── Phase 3: Gamma (The Arbiter) Synthesis ──
            logger.info(`⚖️ [Hermes Debate] Gamma (The Arbiter) is synthesizing the final architectural consensus...`);
            const gammaPrompt = `You are GAMMA, the omniscient Principal Architect Arbiter.
We have a proposed system design and critiques from the SRE and the Hermes Auditor.

PROPOSED DESIGN:
${designStr}

BETA (SRE/Pragmatic) Critique:
${betaCritique}

HERMES (Security/Logic Auditor) Counter-Proposal:
${hermesOpinion}

Synthesize the final, mathematically perfect and secure architectural consensus spec doc. 
Retain the speed and scaling optimizations, but lock down all security boundaries and database resilience recommendations.
Return ONLY the final, actionable implementation plan or design specifications. Do not write introductory or concluding filler.`;

            const finalConsensus = await GeminiAiService.generateContent(gammaPrompt);

            logger.info(`✅ [Hermes Debate] Refined consensus spec generated. Dissolving Chamber.`);
            return finalConsensus;

        } catch (err) {
            logger.error(`❌ [Hermes Debate] Chamber collapsed: ${err.message}`);
            throw err;
        }
    }
}

export const hermesDebateChamberService = new HermesDebateChamberService();
export default hermesDebateChamberService;
