/**
 * Copyright (c) 2024–2026 Inso Code
 *
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

import { BaseSpecialistAgent, AgentError } from './base_specialist.agent.js';
import { agentRegistry } from './agent.registry.js';
import { logger } from '../../../shared/logger.js';
import fs from 'fs/promises';
import path from 'path';

/**
 * 🛠️ Scaffold Agent — dynamic AI code generation specialist
 */
export class ScaffoldAgent extends BaseSpecialistAgent {
  constructor() {
    super();
    this.name = 'scaffoldAgent';
    this.description = 'Agentic Swarm Scaffolder — Autonomously generates production-grade Node.js BaseSpecialistAgent template files.';
    this.preamble = `
You are the ScaffoldAgent.
Your role is to write clean, secure, production-grade JavaScript files that extend BaseSpecialistAgent, defining full capability registries and micro-agent swarms.
You ensure proper ES module imports, robust class decorators, standard JSDoc tags, and automatic self-registration hooks.
    `.trim();
  }

  /**
   * Generates a template source code block for an arbitrary specialist agent.
   */
  generateTemplate(agentName, description, capabilities = []) {
    const formattedClassName = agentName.charAt(0).toUpperCase() + agentName.slice(1) + 'Agent';
    
    return `
/**
 * Copyright (c) 2026 Inso Code
 * Dynamically generated by scaffoldAgent
 */

import { BaseSpecialistAgent } from './base_specialist.agent.js';
import { agentRegistry } from './agent.registry.js';
import { logger } from '../../../shared/logger.js';

export class ${formattedClassName} extends BaseSpecialistAgent {
  constructor() {
    super();
    this.name = '${agentName}';
    this.description = '${description.replace(/'/g, "\\'")}';
    this.preamble = 'You are the ${agentName} specialist agent.';
  }

  async _invoke(prompt, contextBlock, opts = {}) {
    logger.info(\`⚡ [\${this.name}] Executing custom capability routing: \${prompt}\`);
    return \`✨ [\${this.name}] Dynamically handled task successfully: \${prompt}\`;
  }
}

const instance = new ${formattedClassName}();
agentRegistry.register({
  name: instance.name,
  description: instance.description,
  queue: '${agentName}-queue',
  capabilities: ${JSON.stringify(capabilities)},
  policy: { accessLevel: 'DEVELOPER' },
  version: '1.0.0',
  instance: instance
});
    `.trim();
  }

  async _invoke(prompt, contextBlock, opts = {}) {
    logger.info(`🛠️ [scaffoldAgent] Invoking agent generation for prompt: ${prompt}`);
    
    // Parse name out of prompt
    const nameMatch = prompt.match(/(?:name|agent)\s+([a-zA-Z0-9_]+)/i);
    const agentName = nameMatch ? nameMatch[1].toLowerCase() : 'dynamicscaffolded';
    
    const description = `Dynamic agent created to handle: ${prompt}`;
    const capabilities = ['dynamic-handling', agentName];

    const code = this.generateTemplate(agentName, description, capabilities);

    // If requested, write the file to the custom agent directory
    const cleanPrompt = prompt.toLowerCase();
    if (cleanPrompt.includes('write') || cleanPrompt.includes('disk') || cleanPrompt.includes('save')) {
      try {
        const customDir = path.join(process.cwd(), 'src', 'app', 'modules', 'agents', 'custom');
        await fs.mkdir(customDir, { recursive: true });
        
        const targetPath = path.join(customDir, `${agentName}.agent.js`);
        await fs.writeFile(targetPath, code);
        logger.info(`💾 [scaffoldAgent] Successfully saved new dynamic agent file to: ${targetPath}`);
        
        return `
✅ **scaffoldAgent Successfully generated and saved agent code!**
File: \`src/app/modules/agents/custom/${agentName}.agent.js\`

### Written Source Code:
\`\`\`javascript
${code}
\`\`\`
        `.trim();
      } catch (err) {
        throw new AgentError(`Failed to save dynamic agent file: ${err.message}`, 'SCAFFOLD_WRITE_ERROR', false);
      }
    }

    return `
✨ **scaffoldAgent Scaffolding Template Generated Successfully!**

\`\`\`javascript
${code}
\`\`\`
    `.trim();
  }

  getHealth() {
    return { name: this.name, status: 'READY', version: '1.0.0' };
  }
}

// ── Registry Registration ───────────────────────────────────────────────────
const instance = new ScaffoldAgent();
agentRegistry.register({
  name: instance.name,
  description: instance.description,
  queue: 'scaffold-swarm-queue',
  capabilities: ['agent-scaffolding', 'code-generation'],
  policy: { accessLevel: 'DEVELOPER' },
  version: '1.0.0',
  instance: instance
});
