export interface TeamMember {
  id: string;
  name: string;
  role: string;
  type:
    | "language"
    | "framework"
    | "role"
    | "cloud"
    | "integration"
    | "database"
    | "mobile"
    | "gamedev"
    | "frontend"
    | "backend"
    | "security"
    | "devops"
    | "productivity";
  category: string;
  specialties: string[];
  bio: string;
  status: "idle" | "active" | "testing" | "compiling";
  statusText: string;
  accentColor: string;
  icon?: string;
}

export const teamMembers: TeamMember[] = [
  {
    id: "amazonaws-expert",
    name: "AWS",
    role: "AWS Architect",
    type: "devops",
    category: "Cloud",
    specialties: ["API Integration", "Webhooks", "SDK Configuration"],
    bio: "Integrates and configures AWS services into your application.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#232F3E",
    icon: "logos:aws",
  },
  {
    id: "googlecloud-expert",
    name: "Google Cloud",
    role: "Google Cloud Architect",
    type: "devops",
    category: "Cloud",
    specialties: ["API Integration", "Webhooks", "SDK Configuration"],
    bio: "Integrates and configures Google Cloud services into your application.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4285F4",
    icon: "simple-icons:googlecloud",
  },
  {
    id: "microsoftazure-expert",
    name: "Microsoft Azure",
    role: "Microsoft Azure Architect",
    type: "devops",
    category: "Cloud",
    specialties: ["API Integration", "Webhooks", "SDK Configuration"],
    bio: "Integrates and configures Microsoft Azure services into your application.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#0089D6",
    icon: "simple-icons:microsoftazure",
  },
  {
    id: "alibaba-cloud-expert",
    name: "Alibaba Cloud",
    role: "Alibaba Cloud Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["ECS & ACK", "Infrastructure", "Scaling"],
    bio: "Provisions and maintains robust systems on Alibaba Cloud.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#FF6600",
    icon: "simple-icons:alibabacloud",
  },
  {
    id: "oracle-cloud-expert",
    name: "Oracle Cloud",
    role: "OCI Database Dev",
    type: "cloud",
    category: "Cloud",
    specialties: ["Autonomous DB", "Oracle APEX", "Bare Metal"],
    bio: "Maintains high-performance Oracle Cloud Infrastructure (OCI) and enterprise databases.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F80000",
    icon: "logos:oracle",
  },
  {
    id: "ibm-cloud-expert",
    name: "IBM Cloud Systems",
    role: "IBM Cloud Architect",
    type: "cloud",
    category: "Cloud",
    specialties: ["Watson AI", "Db2", "Red Hat OpenShift"],
    bio: "Deploys hybrid cloud solutions utilizing IBM Cloud and enterprise-grade data services.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#052FAD",
    icon: "logos:ibm",
  },
  {
    id: "javascript-expert",
    name: "JavaScript",
    role: "JavaScript Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors JavaScript code for ES6/Node.js event loops, promises, dynamic scopes, and ecosystem tools.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#6B8A14",
    icon: "logos:javascript",
  },
  {
    id: "typescript-expert",
    name: "TypeScript",
    role: "TypeScript Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors TypeScript code for Strict-mode interfaces, mapped types, advanced generics, and tsconfig optimizations.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#CA61FA",
    icon: "logos:typescript-icon",
  },
  {
    id: "python-expert",
    name: "Python",
    role: "Python Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors Python code for Async FastAPI, Django, type-safe Pydantic models, data science pipelines, and packaging.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#144233",
    icon: "logos:python",
  },
  {
    id: "java-expert",
    name: "Java",
    role: "Java Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors Java code for JVM runtime optimization, virtual threads, records, sealed classes, and Spring Boot 3.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#4B49CC",
    icon: "logos:java",
  },
  {
    id: "cpp-expert",
    name: "C++",
    role: "C++ Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors C++ code for Modern C++23 template metaprogramming, RAII safety, STL concurrency, and memory management.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#2AE95C",
    icon: "logos:c",
  },
  {
    id: "csharp-expert",
    name: "C#",
    role: "C# Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors C# code for C# 12/.NET 8 async workflows, LINQ queries, EF Core database mappings, and ASP.NET Core.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F532ED",
    icon: "logos:c",
  },
  {
    id: "golang-expert",
    name: "Go",
    role: "Go Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors Go code for Goroutines, CSP channels, standard library microservices, and gRPC communication protocols.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#DEDEFD",
    icon: "logos:go",
  },
  {
    id: "c-expert",
    name: "C",
    role: "C Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors C code for Low-level procedural system programming, manual memory allocators, POSIX wrappers, and compiler flags.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#E494C8",
    icon: "logos:c",
  },
  {
    id: "php-expert",
    name: "PHP",
    role: "PHP Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors PHP code for Modern PHP 8.3 OOP structures, Laravel web framework pipelines, and Pest testing.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#00FB10",
    icon: "logos:php",
  },
  {
    id: "ruby-expert",
    name: "Ruby",
    role: "Ruby Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors Ruby code for Rails backend convention structures, ActiveRecord queries, metaprogramming, and RSpec.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#AB8378",
    icon: "logos:ruby",
  },
  {
    id: "swift-expert",
    name: "Swift",
    role: "Swift Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors Swift code for SwiftUI mobile interfaces, Swift 6 actor model concurrency, and native Apple runtimes.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#DFAF1A",
    icon: "logos:swift",
  },
  {
    id: "kotlin-expert",
    name: "Kotlin",
    role: "Kotlin Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors Kotlin code for Android JVM application runtimes, Coroutines, Flow structures, and Kotlin Multiplatform (KMP).",
    status: "idle",
    statusText: "Idle",
    accentColor: "#8DFB02",
    icon: "logos:kotlin-icon",
  },
  {
    id: "sql-expert",
    name: "SQL",
    role: "SQL Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors SQL code for Relational database querying: advanced CTEs, window functions, query plans, and index strategies.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#DBE497",
    icon: "vscode-icons:file-type-sql",
  },
  {
    id: "bash-expert",
    name: "Bash",
    role: "Bash Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors Bash code for Shell automation pipelines, command-line system scripting, and container automation.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#2C206B",
    icon: "logos:bash-icon",
  },
  {
    id: "rust-expert",
    name: "Rust",
    role: "Rust Engineer",
    type: "language",
    category: "Language",
    specialties: ["Syntax Analysis", "Compilation", "Idiomatic Code"],
    bio: "Expertly writes, analyzes, and refactors Rust code for Memory safety guarantees without garbage collection, borrow checker semantics, lifetimes, and cargo packaging.",
    status: "idle",
    statusText: "Idle",
    accentColor: "#F9DDD0",
    icon: "logos:rust",
  },
];
