import { CertificateAuthorityServiceClient } from '@google-cloud/security-private-ca';
import { logger } from '../../../shared/logger.js';
import config from '../../../../config/index.js';

/**
 * Google Cloud Certificate Authority Service.
 * To ensure absolute Zero-Trust within the Swarm, the backend acts as a Root Certificate Authority.
 * It autonomously mints custom mTLS (Mutual TLS) certificates for every single parallel Cloud Run 
 * Agent it spawns, mathematically preventing rogue nodes from accessing the RAG or the codebase.
 */
class GoogleCaService {
    constructor() {
        try {
            this.client = new CertificateAuthorityServiceClient();
            
            // Assume the CA Pool is pre-configured via Terraform
            this.caPoolName = this.client.caPoolPath(
                config.gcp.project_id,
                config.gcp.location || 'us-central1',
                config.gcp.ca_pool_id || 'alti-swarm-ca-pool'
            );
            
            logger.info('🔐 [CA Service] Google Cloud Certificate Authority Service initialized.');
        } catch (error) {
            logger.warn('⚠️ [CA Service] Could not initialize CA Client.');
        }
    }

    /**
     * Mints a custom mTLS certificate for a newly spawned agent node.
     * @param {string} agentId - The unique identifier of the agent node
     * @param {string} publicKeyPem - The PEM-encoded public key generated by the agent
     */
    async mintAgentCertificate(agentId, publicKeyPem) {
        logger.info(`🔐 [CA Service] Swarm is minting a cryptographic identity for Agent [${agentId}]...`);
        
        try {
            const request = {
                parent: this.caPoolName,
                certificate: {
                    name: `${this.caPoolName}/certificates/${agentId}-${Date.now()}`,
                    lifetime: { seconds: 3600 }, // Short-lived certs (1 hour) for extreme security
                    config: {
                        publicKey: {
                            key: Buffer.from(publicKeyPem),
                            format: 'PEM',
                        },
                        subjectConfig: {
                            subject: {
                                commonName: `agent-${agentId}.alti.code.studio`,
                                organization: 'Inso Code Swarm',
                            },
                        },
                        x509Config: {
                            keyUsage: {
                                baseKeyUsage: {
                                    digitalSignature: true,
                                    keyEncipherment: true,
                                },
                                extendedKeyUsage: {
                                    clientAuth: true, // Crucial for mTLS
                                    serverAuth: true,
                                },
                            },
                        },
                    },
                },
            };

            const [response] = await this.client.createCertificate(request);
            logger.info(`✅ [CA Service] mTLS Certificate minted successfully. Identity verified.`);
            return response.pemCertificate;
        } catch (error) {
            logger.error(`❌ [CA Service] Failed to mint agent certificate:`, error.message);
            return null;
        }
    }
}

export const caService = new GoogleCaService();
