import { librarianService } from '../src/app/modules/librarian/librarian.service.js';
import { logger } from '../src/shared/logger.js';
import { aiProvider } from '../src/app/modules/ai/ai.provider.js';
import fs from 'fs/promises';

const runVerification = async () => {
    logger.info("Starting Librarian Agent Verification...");

    // Mock AI Provider
    aiProvider.generate = async (prompt) => {
        logger.info("Mock AI: Providing Documentation...");
        if (prompt.includes("JSDoc")) {
            return `
            /**
             * Adds two numbers.
             * @param {number} a
             * @param {number} b
             * @returns {number}
             */
            export const add = (a, b) => a + b;
            `;
        }
        return "# Mock README\n\nGenerated by Librarian.";
    };

    try {
        // 1. Verify Document File
        const dummyFile = 'scripts/dummy_lib.js';
        await fs.writeFile(dummyFile, 'export const add = (a,b) => a+b;');

        logger.info("1. Testing File Documentation...");
        await librarianService.documentFile(dummyFile);

        const content = await fs.readFile(dummyFile, 'utf-8');
        logger.info("Documented Content:\n", content);

        if (!content.includes('@returns')) {
            throw new Error("Documentation not applied.");
        }

        // 2. Verify Helper
        // (Skipping updateReadme for brevity in this simple check, verifying 1 method is enough to prove wiring)

        // Cleanup
        await fs.unlink(dummyFile);

        logger.info("Librarian Verification Complete.");
        process.exit(0);

    } catch (error) {
        logger.error("Verification Failed", error);
        process.exit(1);
    }
};

runVerification();
