import { logger } from '../../../shared/logger.js';

/**
 * Google Wireit (Apache 2.0) Autonomous Injection Service.
 * Automatically injects Google's advanced 'wireit' caching engine into the build 
 * pipelines of all applications generated by the Swarm.
 * This grants all Swarm-generated codebases instant, highly optimized local caching
 * and parallel execution capabilities without any human configuration.
 */
class GoogleWireitService {
    /**
     * Augments a raw package.json string with Google Wireit configuration.
     * @param {string} packageJsonStr - The raw package.json generated by the Swarm.
     * @returns {string} The augmented package.json with Wireit enabled.
     */
    injectWireitConfig(packageJsonStr) {
        try {
            const pkg = JSON.parse(packageJsonStr);
            
            // If the package.json doesn't exist or is malformed, skip
            if (!pkg || typeof pkg !== 'object') return packageJsonStr;

            // Ensure scripts object exists
            pkg.scripts = pkg.scripts || {};
            
            // Only inject if there are build or test scripts
            let injected = false;
            const wireitConfig = {};

            const targetScripts = ['build', 'test', 'lint', 'start', 'dev'];

            targetScripts.forEach(script => {
                if (pkg.scripts[script] && pkg.scripts[script] !== 'wireit') {
                    // Move the original command to the wireit block
                    wireitConfig[script] = {
                        command: pkg.scripts[script]
                    };

                    // Add smart dependencies
                    if (script === 'build' && pkg.scripts['lint']) {
                        wireitConfig[script].dependencies = ['lint'];
                    }

                    // Add aggressive caching rules
                    if (script === 'build') {
                        wireitConfig[script].files = ["src/**/*", "public/**/*", "*.config.js"];
                        wireitConfig[script].output = ["dist/**", "build/**", ".next/**"];
                    }

                    // Override the original script to use Google Wireit
                    pkg.scripts[script] = "wireit";
                    injected = true;
                }
            });

            if (injected) {
                // Ensure wireit is in devDependencies
                pkg.devDependencies = pkg.devDependencies || {};
                if (!pkg.devDependencies['wireit']) {
                    pkg.devDependencies['wireit'] = "^0.14.0";
                }

                // Append the wireit configuration block
                pkg.wireit = wireitConfig;

                logger.info(`⚡ [Wireit] Injected Google Wireit aggressive caching into generated project.`);
                return JSON.stringify(pkg, null, 2);
            }

            return packageJsonStr;
        } catch (error) {
            logger.error(`❌ [Wireit] Failed to inject Wireit config:`, error.message);
            // Graceful fallback to the un-augmented package.json
            return packageJsonStr;
        }
    }
}

export const wireitService = new GoogleWireitService();
