/**
 * Copyright (c) 2024 Inso Code
 *
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

import vm from 'node:vm';
import { logger } from '../../../shared/logger.js';

class HolodeckService {
    constructor() {
        this.timeoutMs = 5000; // Hard kill switch to prevent infinite loops from AI
    }

    /**
     * Executes AI-generated code in an isolated, secure V8 context.
     * Captures stdout, stderr, and strict runtime errors.
     * 
     * @param {string} sourceCode - The raw Javascript code generated by the Swarm.
     * @returns {Promise<{success: boolean, logs: string[], error: string|null, result: any}>}
     */
    async simulateExecution(sourceCode) {
        logger.info(`🧪 [Holodeck] Spinning up isolated V8 Sandbox for predictive execution...`);

        const logs = [];
        
        // Mock the console to capture AI output without polluting the main thread
        const virtualConsole = {
            log: (...args) => logs.push(`[LOG]: ${args.join(' ')}`),
            error: (...args) => logs.push(`[ERR]: ${args.join(' ')}`),
            warn: (...args) => logs.push(`[WARN]: ${args.join(' ')}`),
            info: (...args) => logs.push(`[INFO]: ${args.join(' ')}`),
        };

        // Create a pristine environment (No access to 'process', 'require', or 'fs')
        const sandbox = {
            console: virtualConsole,
            setTimeout,
            clearTimeout,
            Buffer,
            Math,
            JSON,
            Promise
        };

        vm.createContext(sandbox);

        try {
            // Execute the AI code. It is mathematically contained within the V8 Isolate.
            // If the AI wrote an infinite loop (e.g. while(true)), the timeout will kill it.
            const script = new vm.Script(sourceCode);
            const executionResult = script.runInContext(sandbox, {
                timeout: this.timeoutMs,
                displayErrors: true
            });

            logger.info(`✅ [Holodeck] Simulation Successful. Code is flawless.`);
            return {
                success: true,
                logs,
                error: null,
                result: executionResult
            };

        } catch (err) {
            logger.warn(`🛑 [Holodeck] Simulation FAILED! The Swarm generated broken code.`);
            logger.warn(`   -> Trace: ${err.message}`);
            
            return {
                success: false,
                logs,
                error: err.stack || err.message,
                result: null
            };
        }
    }
}

export const holodeckService = new HolodeckService();
