/**
 * Copyright (c) 2024 Alti.Code.Studio
 *
 * session.sync.js — Desktop App Persistent Session Synchronizer
 *
 * This background worker is designed to integrate with Open-Claude Co-Work.
 * It reads the local SQLite database generated by Open-Claude's desktop usage,
 * and streams the memory (tool executions, context) up to the 
 * Alti.Code.Studio Cortex Vector Store in the cloud.
 */

const fs = require('fs');
const path = require('path');
const https = require('https');

const safeLog = (...args) => { try { console.log(...args); } catch(e) { if(e.code !== 'EPIPE') throw e; } };
const safeWarn = (...args) => { try { console.warn(...args); } catch(e) { if(e.code !== 'EPIPE') throw e; } };
const safeError = (...args) => { try { console.error(...args); } catch(e) { if(e.code !== 'EPIPE') throw e; } };

// We simulate connecting to the Open-Claude SQLite database.
// In actual Open-Claude, sessions reside in an sqlite db.
class OpenClaudeSessionSyncer {
    constructor() {
        this.syncIntervalMs = 60000; // Sync every 1 minute
        this.cloudApiUrl = process.env.ALTI_CLOUD_URL || 'http://localhost:3000/api/v1';
        this.apiKey = process.env.ALTI_API_KEY || 'demo-desktop-key';
        this.dbPath = path.join(process.env.APPDATA || process.env.HOME || '', 'open-claude', 'sessions.sqlite');
    }

    start() {
        safeLog(`📡 [SessionSync] Initializing local memory sync for Open-Claude sessions: ${this.dbPath}`);
        this.interval = setInterval(() => this.syncNow(), this.syncIntervalMs);
    }

    stop() {
        if (this.interval) clearInterval(this.interval);
    }

    async syncNow() {
        safeLog(`📡 [SessionSync] Scanning local SQLite database for new chat/tool history...`);

        // Simulating DB read 
        let newMemories = [];
        try {
            if (fs.existsSync(this.dbPath)) {
                // If the real DB existed, we'd query it with `better-sqlite3` or similar.
                // We mock it for the architectural implementation.
                newMemories.push({
                    sessionId: "open-claude-session-9080",
                    timestamp: new Date().toISOString(),
                    type: "tool_execution",
                    agent: "Claude 3.5 Sonnet",
                    tool: "Composio.Jira.GetIssue",
                    app: "Jira",
                    summary: "Retrieved PROJ-123 to understand the current login bug context."
                });
            } else {
                // Return hypothetical memories for platform simulation
                newMemories.push({
                    sessionId: "demo-session-1234",
                    timestamp: new Date().toISOString(),
                    type: "desktop_chat",
                    agent: "Local Surrogate",
                    summary: "User asked to verify the Salesforce lead data."
                });
            }

            if (newMemories.length > 0) {
                await this.pushToCloudCortex(newMemories);
            }
        } catch (error) {
            safeError(`❌ [SessionSync] DB read failed:`, error.message);
        }
    }

    async pushToCloudCortex(memories) {
        return new Promise((resolve) => {
            const data = JSON.stringify({ source: 'desktop-open-claude', memories });
            const url = new URL(`${this.cloudApiUrl}/wiki/sync`);

            const options = {
                hostname: url.hostname,
                port: url.port,
                path: url.pathname,
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Content-Length': Buffer.byteLength(data),
                    'Authorization': `Bearer ${this.apiKey}`
                }
            };

            // To support both http for dev and https for prod
            const reqLib = url.protocol === 'https:' ? https : require('http');

            const req = reqLib.request(options, (res) => {
                if (res.statusCode === 200 || res.statusCode === 201) {
                    safeLog(`✅ [SessionSync] Successfully injected ${memories.length} desktop memories into Cloud Cortex.`);
                } else {
                    safeWarn(`⚠️ [SessionSync] Cloud rejected sync payload (Status: ${res.statusCode})`);
                }
                resolve();
            });

            req.on('error', (e) => {
                safeError(`❌ [SessionSync] Network error pushing to cloud: ${e.message}`);
                resolve(); // We swallow network errors to avoid crashing electron
            });

            req.write(data);
            req.end();
        });
    }
}

module.exports = { OpenClaudeSessionSyncer };
