apiVersion: v1
kind: Service
metadata:
  name: alti-backend-service
spec:
  headers:
    app: alti-backend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: alti-backend
  type: LoadBalancer
